### ISSUE TITLE
KSQLDB client requires kafka-streams dependency to work

### ISSUE THREAD

**Issue by antonmos** [confluentinc/ksql#10047]
When using `streamQuery` or `executeQuery`, the following error is thrown.

```
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/streams/errors/StreamsException
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at io.confluent.ksql.api.client.impl.ClientImpl.streamQuery(ClientImpl.java:131)
at io.confluent.ksql.api.client.impl.ClientImpl.streamQuery(ClientImpl.java:123)
```

see https://github.com/confluentinc/ksql/issues/8942 for reproduce steps

This is happening because `kafka-streams` jar is not a dependency of `ksqldb-api-client`.
Right now, the users can work around by adding `kafka-streams` in the project but it is not documented. 
Moreover, this seems like an excessive dependency for ksqldb-api-client.

**Comment by suhas-satish** [comment]
@JimGalasyn , can we document this for users? ie instructing them to add kafka-streams jar explicitly since ksqldb-api-client needs it?

**Comment by JimGalasyn** [comment]
@suhas-satish Tracking with internal ticket DOCS-25118.
