### ISSUE TITLE
Can't start ksqldb

### ISSUE THREAD

**Issue by iomari** [confluentinc/ksql#10074]
Whether I use docker-compose or the taball, I get the an error: Here is the last part om y startup output:

`ksqldb-server  |  (org.apache.kafka.clients.admin.AdminClientConfig:369)
ksqldb-server  | [2023-09-22 17:46:05,955] INFO These configurations '[metrics.context.resource.version, metrics.context.resource.commit.id]' were supplied but are not used yet. (org.apache.kafka.clients.admin.AdminClientConfig:378)
ksqldb-server  | [2023-09-22 17:46:05,958] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:05,958] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:06,060] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:06,060] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:06,161] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:06,162] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:06,363] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:06,363] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:06,767] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:06,767] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:07,672] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:07,672] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:08,882] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:08,882] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:10,092] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:10,092] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:11,101] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:11,101] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:12,311] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:12,312] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:13,320] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:13,320] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:14,528] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:14,528] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:15,533] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:15,533] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:16,538] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:16,539] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:17,447] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:17,447] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:18,456] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:18,456] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:19,364] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:19,364] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:20,473] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:20,473] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:21,582] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:21,583] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:22,690] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:22,690] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:23,897] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:23,897] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:25,105] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:25,106] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:26,316] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:26,316] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:27,224] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:27,225] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:28,433] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:28,434] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:29,544] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:29,545] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:30,552] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:30,553] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:31,560] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:31,560] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:32,767] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:32,767] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:33,773] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:33,774] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:34,681] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:34,682] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:35,689] INFO [AdminClient clientId=adminclient-2] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:976)
ksqldb-server  | [2023-09-22 17:46:35,689] WARN [AdminClient clientId=adminclient-2] Connection to node -1 (localhost/172.26.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:814)
ksqldb-server  | [2023-09-22 17:46:35,957] INFO [AdminClient clientId=adminclient-2] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager:235)
ksqldb-server  | org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: fetchMetadata
ksqldb-server  | [2023-09-22 17:46:35,960] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:96)
ksqldb-server  | java.lang.RuntimeException: Failed to get Kafka cluster information
ksqldb-server  | 	at io.confluent.ksql.services.KafkaClusterUtil.getKafkaClusterId(KafkaClusterUtil.java:107)
ksqldb-server  | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:631)
ksqldb-server  | 	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:225)
ksqldb-server  | 	at io.confluent.ksql.rest.server.KsqlServerMain.lambda$main$1(KsqlServerMain.java:82)
ksqldb-server  | 	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:115)
ksqldb-server  | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:94)
ksqldb-server  | Caused by: java.util.concurrent.TimeoutException
ksqldb-server  | 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
ksqldb-server  | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
ksqldb-server  | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
ksqldb-server  | 	at io.confluent.ksql.services.KafkaClusterUtil.getKafkaClusterId(KafkaClusterUtil.java:105)
ksqldb-server  | 	... 5 more
ksqldb-server exited with code 255`

**Comment by xmlking** [comment]
same issue for me.

**Comment by xmlking** [comment]
debug logs

```
DEBUG [AdminClient clientId=adminclient-1] Connection with  xxx/xx.xx.xx.xxx (channelId=-1) disconnected (org.apache.kafka.common.network.Selector)                                      │
│ java.io.EOFException                                                                                                                                                                                                                                                                                   │
│     at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:109)                                                                                                                                                                                                                │
│     at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)                                                                                                                                                                                                                     │
│     at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)                                                                                                                                                                                                                        │
│     at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)                                                                                                                                                                                                                         │
│     at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)                                                                                                                                                                                                                   │
│     at org.apache.kafka.common.network.Selector.poll(Selector.java:481)                                                                                                                                                                                                                                │
│     at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)                                                                                                                                                                                                                             │
│     at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)                                                                                                                                                                                 │
│     at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)                                                                                                                                                                                             │
│     at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                                                                                                                                 │
```
