### ISSUE TITLE
Intermittent test failure: SecureIntegrationTest.shouldRunQueryWithChangeLogsAgainstKafkaClusterWithAcls

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1007]
This test fails occasionally with the following error:
```
io.confluent.ksql.util.KsqlException: Kafka topic does not exist: orders_topic
	at io.confluent.ksql.integration.SecureIntegrationTest.execInitCreateStreamQueries(SecureIntegrationTest.java:410)
	at io.confluent.ksql.integration.SecureIntegrationTest.givenTestSetupWithConfig(SecureIntegrationTest.java:343)
	at io.confluent.ksql.integration.SecureIntegrationTest.shouldRunQueryWithChangeLogsAgainstKafkaClusterWithAcls(SecureIntegrationTest.java:212)
```

**Comment by apurvam** [comment]
cc @big-andy-coates
