### ISSUE TITLE
Intermittent test failure: SecureIntegrationTest.shouldRunQueryWithChangeLogsAgainstKafkaClusterWithAclsWhereTopicsPreexist

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1008]
The `SecureIntegrationTest.shouldRunQueryWithChangeLogsAgainstKafkaClusterWithAclsWhereTopicsPreexist` fails intermittently with:

```
java.lang.AssertionError: 

Expected: a collection with size a value greater than <0>
     but: collection size <0> was equal to <0>
	at io.confluent.ksql.integration.SecureIntegrationTest.assertCanRunKsqlQuery(SecureIntegrationTest.java:367)
	at io.confluent.ksql.integration.SecureIntegrationTest.assertCanRunRepartitioningKsqlQuery(SecureIntegrationTest.java:352)
	at io.confluent.ksql.integration.SecureIntegrationTest.shouldRunQueryWithChangeLogsAgainstKafkaClusterWithAclsWhereTopicsPreexist(SecureIntegrationTest.java:261)
```

**Comment by apurvam** [comment]
cc @big-andy-coates

**Comment by dguy** [comment]
seems the change to the suffix has broken it. I think it will be fixed with my PR: https://github.com/confluentinc/ksql/pull/999
