### ISSUE TITLE
Combination of ksql.queries.file and ksql.streams.rocksdb.config.setter config options results in exception at startup time

### ISSUE THREAD

**Issue by nvp152** [confluentinc/ksql#10121]
**Description**
When one combines both **ksql.queries.file** and **ksql.streams.rocksdb.config.setter** config options an exception is thrown a startup which results in internal consumers to experience a "consumer poll timeout has expired" and getting kicked out of the group and never been able to rejoin the group. 

This is the first error
```
[2023-11-16 17:52:16,190] ERROR stream-client [_confluent-ksql-default_query_CTAS_LATEST_FINDING_0-f2fe0af5-7bec-4066-af88-ae8756f87f0c] Replacing thread in the streams uncaught exception handler (org.apache.kafka.streams.KafkaStreams:530)
org.apache.kafka.streams.errors.StreamsException: java.lang.IllegalStateException: Cannot use KsqlBoundedMemoryRocksDBConfigSetter before it's been configured.
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:657)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579)
Caused by: java.lang.IllegalStateException: Cannot use KsqlBoundedMemoryRocksDBConfigSetter before it's been configured
```
This is the consumer poll timeout message
```
[2023-11-16 17:58:16,482] WARN [Consumer clientId=_confluent-ksql-default_query_CTAS_LATEST_FINDING_0-f2fe0af5-7bec-4066-af88-ae8756f87f0c-StreamThread-5-consumer, groupId=_confluent-ksql-default_query_CTAS_LATEST_FINDING_0] consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1481)
```

This is one of the never ending errors that keeps showing up and never allows the ksqldb consumer to rejoin the group.
```
[2023-11-16 18:15:56,271] INFO [Consumer clientId=_confluent-ksql-default_query_CTAS_LATEST_FINDING_0-f2fe0af5-7bec-4066-af88-ae8756f87f0c-StreamThread-5-consumer, groupId=_confluent-ksql-default_query_CTAS_LATEST_FINDING_0] Request joining group due to: group is already rebalancing (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1072)
```

**Environment:**

KSQL 0.29 in docker

**Comment by cadonna** [comment]
This bug is fixed from `7.0.x` to `master`.
