### ISSUE TITLE
UDAF with GROUP BY not working properly - NullPointerException

### ISSUE THREAD

**Issue by AleksandarTokarev** [confluentinc/ksql#10202]
**Describe the bug**
Hello,  
We are using KSQLDB to run a pipeline with an UDAF - where we want to filter out some items which do not satisfy a condition that we have. 
The function seems to work properly - but when sending the same key for the message - it seems to bug and the aggregate function AGGREGATE list seems to be NULL - which causes NullPointerException

**To Reproduce**
Steps to reproduce the behavior, include:
KSQLDB Version 0.29

a) Create topic `users.items`
b) Create table on top of the topic
```
CREATE TABLE USERS_ITEMS_INITIAL (F_KEY STRING PRIMARY KEY, USERID BIGINT, NAME STRING, DESCRIPTION STRING, AMOUNT DOUBLE, UPDATED BIGINT) WITH (KAFKA_TOPIC='users.items', KEY_FORMAT='KAFKA', VALUE_FORMAT='JSON');
```
c) Use a custom `COLLECT_ITEMS` UDAF which filters out not updated items in the last 5 minutes
```
CREATE TABLE IF NOT EXISTS ITEMS_PER_USER_TABLE WITH (KAFKA_TOPIC='ITEMS_PER_USER_TABLE', PARTITIONS=3, VALUE_FORMAT='JSON') AS SELECT USERS_ITEMS_INITIAL.USERID USERID,
  COLLECT_ITEMS(STRUCT(`NAME`:=USERS_ITEMS_INITIAL.NAME, `DESCRIPTION`:=USERS_ITEMS_INITIAL.DESCRIPTION, `AMOUNT`:=USERS_ITEMS_INITIAL.AMOUNT, `UPDATED`:=USERS_ITEMS_INITIAL.UPDATED)) ACTIVE_ITEMS
FROM USERS_ITEMS_INITIAL
GROUP BY USERS_ITEMS_INITIAL.USERID
EMIT CHANGES;
```

Do some insertions in the `users.items` topic

```
Key
10-T-TOM

Value
{
    "name": "TOMATOES",
    "description": "They are tasty",
    "amount": 1,
    "updated": 1905906822314,
    "userId": 10
}

Key
10-T-POT

Value
{
    "name": "Potatoes",
    "description": "They are tasty too",
    "amount": 2,
    "updated": 1905906822314,
    "userId": 10
}


Key
10-T-POT

Value
{
    "name": "Potatoes",
    "description": "They are tasty too",
    "amount": 3,
    "updated": 1905906822314,
    "userId": 10
}
```

`collect_items` code
```
package example;

import com.google.common.collect.Lists;
import io.confluent.ksql.function.udaf.TableUdaf;
import io.confluent.ksql.function.udaf.UdafDescription;
import io.confluent.ksql.function.udaf.UdafFactory;
import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.apache.kafka.connect.data.Struct;

import java.util.List;

@UdafDescription(   name = "collect_items", category = "test",
        author = "Aleksandar Tokarev", description = "User defined function")
    public class CollectItemsUdaf {

    public static final String INPUT_SCHEMA_DESCRIPTOR = "STRUCT<`NAME` STRING, `DESCRIPTION` STRING, `AMOUNT` DOUBLE, `UPDATED` BIGINT>";

    public static final Schema INPUT_SCHEMA = SchemaBuilder.struct().optional()
            .field("NAME", Schema.OPTIONAL_STRING_SCHEMA)
            .field("DESCRIPTION", Schema.OPTIONAL_STRING_SCHEMA)
            .field("AMOUNT", Schema.OPTIONAL_FLOAT32_SCHEMA)
            .field("UPDATED", Schema.OPTIONAL_INT64_SCHEMA)
            .build();

    public static final String AGGREGATE_SCHEMA_DESCRIPTOR = "ARRAY<STRUCT<`NAME` STRING, `DESCRIPTION` STRING, `AMOUNT` DOUBLE, `UPDATED` BIGINT>>";
    public static final String RETURN_SCHEMA_DESCRIPTOR = "ARRAY<STRUCT<`NAME` STRING, `DESCRIPTION` STRING, `AMOUNT` DOUBLE, `UPDATED` BIGINT>>";

    @UdafFactory(description = "Test"
            , paramSchema = INPUT_SCHEMA_DESCRIPTOR
            , aggregateSchema = AGGREGATE_SCHEMA_DESCRIPTOR
            , returnSchema = RETURN_SCHEMA_DESCRIPTOR
    )
    public static TableUdaf<Struct, List<Struct>, List<Struct>> createUdaf() {
        return new ItemUdafImpl();
    }


    private static class ItemUdafImpl implements TableUdaf<Struct, List<Struct>, List<Struct>> {
        @Override
        public List<Struct> initialize() {
            System.out.println("INSIDE INITIALIZE");
            return Lists.newArrayList();
        }

        @Override
        public List<Struct> aggregate(Struct current, List<Struct> aggregate) {
            System.out.println("CURRENT ITEM2:");
            System.out.println(current);
            System.out.println((long) current.get("UPDATED"));
            System.out.println("LIST:" + aggregate);
            System.out.println("BEFORE ITEM");
            if ((long) current.get("UPDATED") > System.currentTimeMillis()) {
                aggregate.add(current);
            }
            System.out.println("AFTER ITEM");
            return aggregate;
        }

        @Override
        public List<Struct> merge(final List<Struct> aggOne, final List<Struct> aggTwo) {
            System.out.println("TRYING TO DO MERGING!!!");
            return aggOne;
        }

        @Override
        public List<Struct> map(final List<Struct> agg) {
            System.out.println("BEFORE MAP RETURN");
            return agg;
        }

        @Override
        public List<Struct> undo(Struct valueToUndo, List<Struct> aggregateValue) {
            return null;
        }
    }
}
```

**Expected behavior**
The issue occurs when sending the third message - aggregate list is NULL - therefore it fails with NullPointer.
What I am expecting is the third message to `overwrite` the first one and the aggregation to happen only for the second and third messages. This should result in the following output in the last table:
```
{
	"ACTIVE_ITEMS": [
		{
			"NAME": "TOMATOES",
			"DESCRIPTION": "They are tasty",
			"AMOUNT": 1,
			"UPDATED": 1905906822314
		},
		{
			"NAME": "Potatoes",
			"DESCRIPTION": "They are tasty too",
			"AMOUNT": 3,
			"UPDATED": 1905906822314
		}
	]
}
```

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. No issues on the CLI
2. Error messages - NullPointerException
3. KSQL logs 
```
2024-01-22 12:26:35  (c910f9f8-fc36-3bac-a269-be12b546114a): CREATE TABLE IF NOT EXISTS table1WITH (CLEANUP_POLICY='[string]', KAFKA_TOPIC='[string]', PARTITIONS='0', REPLICAS='0', RETENTION_MS='0', VALUE_FORMAT='[string]') AS SELECT column1, udf1 FROM source1 GROUP BY column1 EMIT CHANGES; (io.confluent.ksql.logging.query.QueryLogger:96)
2024-01-22 12:26:35 [2024-01-22 11:26:35,381] ERROR Unhandled exception caught in streams thread _confluent-ksql-kafka-ksqldbquery_CTAS_ITEMS_PER_USER_TABLE_3-e690f685-1306-463f-875f-11d3e0a7aa20-StreamThread-1. (UNKNOWN) (io.confluent.ksql.util.QueryMetadataImpl:209)
2024-01-22 12:26:35 org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=1_1, processor=KSTREAM-SOURCE-0000000009, topic=_confluent-ksql-kafka-ksqldbquery_CTAS_ITEMS_PER_USER_TABLE_3-Aggregate-GroupBy-repartition, partition=1, offset=3, stacktrace=java.lang.NullPointerException
2024-01-22 12:26:35     at example.CollectItemsUdaf$ItemUdafImpl.aggregate(CollectItemsUdaf.java:54)
2024-01-22 12:26:35     at example.CollectItemsUdaf$ItemUdafImpl.aggregate(CollectItemsUdaf.java:39)
```

**Comment by AleksandarTokarev** [comment]
Ok it seems the issue was with 
```
@Override
        public List<Struct> undo(Struct valueToUndo, List<Struct> aggregateValue) {
            return null;
        }
```
When a record is sent to a partition and a previous record for that key is there in the partition - we need to implement the undo method - the same one as collect list does the job fine.
https://github.com/confluentinc/ksql/blob/master/ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/array/CollectListUdaf.java#L116-L128
