### ISSUE TITLE
Unable to verify if the value schema for topic -- PROTOBUF -- Reason: null

### ISSUE THREAD

**Issue by ja-softdevel** [confluentinc/ksql#10269]
**Versions**
cp-ksqldb-server:7.5.3-1-ubi8
cp-schema-registry:7.6.0-2-ubi8
cp-server:7.5.2

**Describe the bug**
Trying to create a stream from a topic with a Protobuf schema, I keep getting that error. The schema is very, very large. The schema is owned by a 3rd party and I can not modify it. Also, unfortunately, I can not post it here. I know it would be useful to have it for debugging.

I took the original .proto file and removed all comments and flatten it to 1 line. Then I created the json around it for posting to schema registry REST endpoint. `wc -m` for that file returns `23857 chars`. So now I'm wondering if ksql is hitting a limit on the schema size.

Ksql cli doesn't report much on the error. So I am including the docker logs for ksqldb for this error.
I did try it with `syntax = proto2 & proto3` just to see if the proto version was an issue. It wasn't.

````[2024-03-25 14:59:46,990] INFO Received: KsqlRequest{configOverrides={auto.offset.reset=earliest}, requestProperties={}, commandSequenceNumber=Optional[-1]} (58bd2c38-a934-3757-812d-935dd648d25a): CREATE STREAM stream1 WITH (KAFKA_TOPIC='[string]', VALUE_FORMAT='[string]', VALUE_SCHEMA_FULL_NAME='[string]'); (io.confluent.ksql.logging.query.QueryLogger)
[2024-03-25 14:59:46,991] INFO There are no queries assigned to Gen 2 runtimes yet. (io.confluent.ksql.engine.RuntimeAssignor)
[2024-03-25 14:59:46,991] INFO ProcessingLogConfig values: 
	ksql.logging.processing.rows.include = false
	ksql.logging.processing.stream.auto.create = false
	ksql.logging.processing.stream.name = KSQL_PROCESSING_LOG
	ksql.logging.processing.topic.auto.create = false
	ksql.logging.processing.topic.name = 
	ksql.logging.processing.topic.partitions = 1
	ksql.logging.processing.topic.replication.factor = 1
 (io.confluent.ksql.logging.processing.ProcessingLogConfig)
[2024-03-25 14:59:46,992] INFO KsqlConfig values: 
	ksql.access.validator.enable = auto
	ksql.assert.schema.default.timeout.ms = 1000
	ksql.assert.topic.default.timeout.ms = 1000
	ksql.authorization.cache.expiry.time.secs = 30
	ksql.authorization.cache.max.entries = 10000
	ksql.cast.strings.preserve.nulls = true
	ksql.client.ip_port.configuration.enabled = false
	ksql.connect.basic.auth.credentials.file = 
	ksql.connect.basic.auth.credentials.reload = false
	ksql.connect.basic.auth.credentials.source = NONE
	ksql.connect.request.headers.plugin = null
	ksql.connect.request.timeout.ms = 5000
	ksql.connect.url = http://localhost:8083
	ksql.connect.worker.config = 
	ksql.create.or.replace.enabled = true
	ksql.endpoint.migrate.query = true
	ksql.error.classifier.regex = 
	ksql.extension.dir = ext
	ksql.fetch.remote.hosts.max.timeout.seconds = 10
	ksql.headers.columns.enabled = true
	ksql.hidden.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
	ksql.insert.into.values.enabled = true
	ksql.internal.topic.min.insync.replicas = 1
	ksql.internal.topic.replicas = 1
	ksql.json_sr.converter.deserializer.enabled = true
	ksql.lambdas.enabled = true
	ksql.metastore.backup.location = 
	ksql.metrics.extension = null
	ksql.metrics.tags.custom = 
	ksql.nested.error.set.null = true
	ksql.new.query.planner.enabled = false
	ksql.output.topic.name.prefix = 
	ksql.persistence.default.format.key = KAFKA
	ksql.persistence.default.format.value = null
	ksql.persistence.wrap.single.values = null
	ksql.persistent.prefix = query_
	ksql.properties.overrides.denylist = []
	ksql.pull.queries.enable = true
	ksql.query.cleanup.shutdown.timeout.ms = 30000
	ksql.query.error.max.queue.size = 10
	ksql.query.persistent.active.limit = 2147483647
	ksql.query.persistent.max.bytes.buffering.total = -1
	ksql.query.pull.enable.standby.reads = false
	ksql.query.pull.forwarding.timeout.ms = 20000
	ksql.query.pull.interpreter.enabled = true
	ksql.query.pull.limit.clause.enabled = true
	ksql.query.pull.max.allowed.offset.lag = 9223372036854775807
	ksql.query.pull.max.concurrent.requests = 2147483647
	ksql.query.pull.max.hourly.bandwidth.megabytes = 2147483647
	ksql.query.pull.max.qps = 2147483647
	ksql.query.pull.metrics.enabled = true
	ksql.query.pull.range.scan.enabled = true
	ksql.query.pull.router.thread.pool.size = 50
	ksql.query.pull.stream.enabled = true
	ksql.query.pull.table.scan.enabled = true
	ksql.query.pull.thread.pool.size = 50
	ksql.query.push.v2.alos.enabled = true
	ksql.query.push.v2.catchup.consumer.msg.window = 50
	ksql.query.push.v2.continuation.tokens.enabled = false
	ksql.query.push.v2.enabled = false
	ksql.query.push.v2.interpreter.enabled = true
	ksql.query.push.v2.latest.reset.age.ms = 30000
	ksql.query.push.v2.max.catchup.consumers = 5
	ksql.query.push.v2.max.hourly.bandwidth.megabytes = 2147483647
	ksql.query.push.v2.metrics.enabled = true
	ksql.query.push.v2.new.latest.delay.ms = 5000
	ksql.query.push.v2.registry.installed = false
	ksql.query.retry.backoff.initial.ms = 15000
	ksql.query.retry.backoff.max.ms = 900000
	ksql.query.status.running.threshold.seconds = 300
	ksql.query.transient.max.bytes.buffering.total = -1
	ksql.queryanonymizer.cluster_namespace = null
	ksql.queryanonymizer.logs_enabled = true
	ksql.readonly.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
	ksql.runtime.feature.shared.enabled = false
	ksql.schema.registry.url = http://kafka-registry:8081
	ksql.security.extension.class = null
	ksql.service.id = default_
	ksql.shared.runtimes.count = 2
	ksql.sink.window.change.log.additional.retention = 1000000
	ksql.source.table.materialization.enabled = true
	ksql.streams.shutdown.timeout.ms = 300000
	ksql.suppress.buffer.size.bytes = -1
	ksql.suppress.enabled = true
	ksql.timestamp.throw.on.invalid = false
	ksql.transient.prefix = transient_
	ksql.transient.query.cleanup.service.enable = true
	ksql.transient.query.cleanup.service.initial.delay.seconds = 600
	ksql.transient.query.cleanup.service.period.seconds = 600
	ksql.udf.collect.metrics = false
	ksql.udf.enable.security.manager = true
	ksql.udfs.enabled = true
	ksql.variable.substitution.enable = true
	ksql.websocket.connection.max.timeout.ms = 3600000
	metric.reporters = []
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
 (io.confluent.ksql.util.KsqlConfig)
[2024-03-25 14:59:47,005] INFO ProtobufDataConfig values: 
	enhanced.protobuf.schema.support = true
	generalized.sum.type.support = false
	generate.index.for.unions = true
	generate.struct.for.nulls = false
	ignore.default.for.nullables = false
	int.for.enums = false
	optional.for.nullables = false
	optional.for.proto2 = true
	schemas.cache.config = 1000
	scrub.invalid.names = false
	wrapper.for.nullables = false
	wrapper.for.raw.primitives = true
 (io.confluent.connect.protobuf.ProtobufDataConfig)
[2024-03-25 14:59:47,008] INFO Processed unsuccessfully: KsqlRequest{configOverrides={auto.offset.reset=earliest}, requestProperties={}, commandSequenceNumber=Optional[-1]} (58bd2c38-a934-3757-812d-935dd648d25a): CREATE STREAM stream1 WITH (KAFKA_TOPIC='[string]', VALUE_FORMAT='[string]', VALUE_SCHEMA_FULL_NAME='[string]'); (io.confluent.ksql.logging.query.QueryLogger)
io.confluent.ksql.util.KsqlStatementException: Unable to verify if the value schema for topic: <topic-name> is compatible with ksqlDB.
Reason: null

Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already known.
If not, please log a new issue, including this full error message.
Schema:syntax = "proto3";
<rest of schema>
````
some more errors for logs after the schema was listed
````
at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.getSchema(DefaultSchemaInjector.java:345)
	at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.getValueSchema(DefaultSchemaInjector.java:320)
	at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.forCreateStatement(DefaultSchemaInjector.java:260)
	at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.inject(DefaultSchemaInjector.java:124)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:176)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:129)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:310)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:183)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$24(KsqlServerEndpoints.java:348)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$23(KsqlServerEndpoints.java:334)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.confluent.ksql.util.KsqlException: Unable to verify if the value schema for topic: <topic-name> is compatible with ksqlDB.
Reason: null

Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already known.
If not, please log a new issue, including this full error message.
Schema:syntax = "proto3";
<rest of schema>
````
It listed the full schema again and then gave a bit more errors.
````
at io.confluent.ksql.schema.ksql.inference.SchemaRegistryTopicSchemaSupplier.notCompatible(SchemaRegistryTopicSchemaSupplier.java:260)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegistryTopicSchemaSupplier.fromParsedSchema(SchemaRegistryTopicSchemaSupplier.java:154)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegistryTopicSchemaSupplier.getSchema(SchemaRegistryTopicSchemaSupplier.java:109)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegistryTopicSchemaSupplier.getValueSchema(SchemaRegistryTopicSchemaSupplier.java:82)
	at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.getSchema(DefaultSchemaInjector.java:340)
	... 18 more
Caused by: java.lang.NullPointerException
	at io.confluent.connect.protobuf.ProtobufData.toUnwrappedSchema(ProtobufData.java:1618)
	at io.confluent.connect.protobuf.ProtobufData.toConnectSchema(ProtobufData.java:1410)
	at io.confluent.connect.protobuf.ProtobufData.toConnectSchema(ProtobufData.java:1401)
	at io.confluent.ksql.serde.protobuf.ProtobufSchemaTranslator.toConnectSchema(ProtobufSchemaTranslator.java:97)
	at io.confluent.ksql.serde.connect.ConnectFormatSchemaTranslator.toColumns(ConnectFormatSchemaTranslator.java:75)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegistryTopicSchemaSupplier.fromParsedSchema(SchemaRegistryTopicSchemaSupplier.java:148)
	... 21 more
[2024-03-25 14:59:47,012] WARN 127.0.0.1 - - [Mon, 25 Mar 2024 14:59:47 GMT] "POST /ksql HTTP/1.1" 400 30439 "-" "-" 275 (io.confluent.ksql.api.server.LoggingHandler)
````

**Comment by ja-softdevel** [comment]
I closed this out because I figured out that error was related to something else.
I can not perform SELECTS on a STREAM if I have assigned a schema to the stream.
