### ISSUE TITLE
"LIMIT reached for the partition." in QueuedSchemaKStream$QueuePopulator

### ISSUE THREAD

**Issue by threedliteguy** [confluentinc/ksql#1032]
I created a new stream out of a source stream left joined to a table.  Both source topics have 10 partitions and the table has about 500k entries.  The join is not on the keys of the topics.  Only the first approx 2100 rows in the resulting stream are populated correctly and then the stream processing stops with the following error in the kstreams log:

[2018-03-22 16:32:16,636] ERROR stream-thread [ksql_transient_786021887816342001_1521736336091-da0c0910-91e7-41d5-bfa2-c9815873e928-StreamThread-43] Failed to process stream task 0_5 due to the following error: (org.apache.kafka.streams.processor.internals.AssignedStreamsTasks:105)
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_5, processor=KSTREAM-SOURCE-0000000000, topic=S_ATABLETOPIC, partition=5, offset=1544
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:238)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:422)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:924)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:804)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:756)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:726)
Caused by: io.confluent.ksql.util.KsqlException: LIMIT reached for the partition.
        at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:182)
        at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:159)
        at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:106)
        at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:83)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.ForwardingCacheFlushListener.apply(ForwardingCacheFlushListener.java:42)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putAndMaybeForward(CachingKeyValueStore.java:96)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.access$000(CachingKeyValueStore.java:38)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore$1.apply(CachingKeyValueStore.java:83)
        at org.apache.kafka.streams.state.internals.NamedCache.flush(NamedCache.java:142)
        at org.apache.kafka.streams.state.internals.NamedCache.evict(NamedCache.java:233)
        at org.apache.kafka.streams.state.internals.ThreadCache.maybeEvict(ThreadCache.java:243)
        at org.apache.kafka.streams.state.internals.ThreadCache.put(ThreadCache.java:153)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putInternal(CachingKeyValueStore.java:223)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:215)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:38)

Later when restarting ksql server I get a NPE: 

Exception in thread "ksql_query_CSAS_RESULT-d28e6fe3-e01c-4bc7-85c3-bf400c356592-StreamThread-11" java.lang.NullPointerException
	at io.confluent.ksql.structured.SchemaKStream.lambda$selectKey$3(SchemaKStream.java:248)
	at io.confluent.ksql.structured.SchemaKStream$$Lambda$70/1626852381.apply(Unknown Source)
	at org.apache.kafka.streams.kstream.internals.KStreamImpl$2.apply(KStreamImpl.java:159)
	at org.apache.kafka.streams.kstream.internals.KStreamImpl$2.apply(KStreamImpl.java:156)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamKTableJoinProcessor.process(KStreamKTableJoinProcessor.java:58)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:169)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:222)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:422)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:924)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:804)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:756)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:726)

**Comment by apurvam** [comment]
Can you share all the statements that result in this error?

**Comment by threedliteguy** [comment]
The scrubbed version is:
SET 'auto.offset.reset'='earliest';
CREATE STREAM fact_data (a bigint, b bigint, `TOPIC` varchar, c bigint, d varchar, e varchar, f bigint, g bigint, h bigint, i bigint, j bigint) WITH (kafka_topic='source_fact_topic', value_format='JSON', key='e');
CREATE STREAM fact_data_by_e with (partitions=10) as select * from fact_data  partition by e;

CREATE STREAM dimension (id string, a string, b string, c string, d string, e string, f string, g string, h string, i string, j string) WITH (kafka_topic='dimension_topic', value_format='JSON', key='id');
CREATE STREAM dimension_by_d with (partitions=10) as select * from dimension partition by d
CREATE TABLE t_dimension_by_d (id string, a string, b string, c string, d string, e string, f string, g string, h string, i string, j string) WITH (kafka_topic='DIMENSION_BY_D', value_format='JSON', key='d');

CREATE STREAM result with (partitions=10) as select f.*, d.id from fact_data_by_e f left join t_dimension_by_d d on f.e=d.d partition by D_A;

In the rest of the app, are multiple dimension table joins that need to be done on non-key fields which are surrogate keys (1 to 1 with primary id).  The repartitioning is for efficiency downstream.  Also without it I was getting nulls for the left part of the join, regardless of SET 'auto.offset.reset'='earliest'; .

**Comment by threedliteguy** [comment]
This seems fixed in the GA release - I can no longer recreate the problem, so looks good.

**Comment by apurvam** [comment]
That's great! closing this out!
