### ISSUE TITLE
Generated 'CREATE STREAM' statement should add backquote for KSQL keywords

### ISSUE THREAD

**Issue by aylei** [confluentinc/ksql#1043]
Hello folks,
I get an error when I try to CREATE STREAM from an AVRO format topic in KSQL 0.5, here's my statement:
```sql
CREATE STREAM ask_stream WITH (KAFKA_TOPIC='vimur2.ask', VALUE_FORMAT='AVRO');
```
And the error log from KSQL server:
```bash
[2018-03-24 17:12:05,976] INFO Executing statement: CREATE STREAM ASK_STREAM
(ASKID BIGINT, USERID BIGINT, LASTCMTID BIGINT, TITLE VARCHAR, DETAIL VARCHAR, ITEMID BIGINT, ASKCAT INT, ALBUMID BIGINT, CMTCOUNT BIGINT, FAVORCOUNT BIGINT, VIEWCOUNT BIGINT, COLLECTCOUNT BIGINT, FOCUSCOUNT BIGINT, INVITECOUNT INT, RECOMMEND BOOLEAN, DELETED BOOLEAN, LASTMODIFIED VARCHAR, CREATED VARCHAR, ACTIVETIME VARCHAR, LASTEDITTIME VARCHAR, FROM VARCHAR, CITYID BIGINT, ADDRESS VARCHAR, HIDE BOOLEAN, ASKTYPE INT, BAIDUID VARCHAR, RCMDTIME VARCHAR, COVERIMAGE VARCHAR, MAINGROUP BIGINT) WITH (KAFKA_TOPIC='vimur2.ask', VALUE_FORMAT='AVRO', AVRO_SCHEMA_ID='5829'); (io.confluent.ksql.rest.server.computation.CommandRunner:103)
[2018-03-24 17:12:05,980] ERROR Failed to handle: Command{statement='CREATE STREAM ASK_STREAM
(ASKID BIGINT, USERID BIGINT, LASTCMTID BIGINT, TITLE VARCHAR, DETAIL VARCHAR, ITEMID BIGINT, ASKCAT INT, ALBUMID BIGINT, CMTCOUNT BIGINT, FAVORCOUNT BIGINT, VIEWCOUNT BIGINT, COLLECTCOUNT BIGINT, FOCUSCOUNT BIGINT, INVITECOUNT INT, RECOMMEND BOOLEAN, DELETED BOOLEAN, LASTMODIFIED VARCHAR, CREATED VARCHAR, ACTIVETIME VARCHAR, LASTEDITTIME VARCHAR, FROM VARCHAR, CITYID BIGINT, ADDRESS VARCHAR, HIDE BOOLEAN, ASKTYPE INT, BAIDUID VARCHAR, RCMDTIME VARCHAR, COVERIMAGE VARCHAR, MAINGROUP BIGINT) WITH (KAFKA_TOPIC='vimur2.ask', VALUE_FORMAT='AVRO', AVRO_SCHEMA_ID='5829');', streamsProperties={AVROSCHEMA={"type":"record","name":"Value","namespace":"vimur2.ask","fields":[{"name":"askid","type":"long"},{"name":"userid","type":"long"},{"name":"lastcmtid","type":["null","long"],"default":null},{"name":"title","type":"string"},{"name":"detail","type":["null","string"],"default":null},{"name":"itemid","type":["null","long"],"default":null},{"name":"askcat","type":{"type":"int","connect.type":"int16"}},{"name":"albumid","type":["null","long"],"default":null},{"name":"cmtcount","type":"long"},{"name":"favorcount","type":"long"},{"name":"viewcount","type":"long"},{"name":"collectcount","type":"long"},{"name":"focuscount","type":"long"},{"name":"invitecount","type":{"type":"int","connect.type":"int16"}},{"name":"recommend","type":"boolean"},{"name":"deleted","type":"boolean"},{"name":"lastmodified","type":{"type":"string","connect.version":1,"connect.name":"io.debezium.time.ZonedTimestamp"}},{"name":"created","type":{"type":"string","connect.version":1,"connect.name":"io.debezium.time.ZonedTimestamp"}},{"name":"activetime","type":{"type":"string","connect.version":1,"connect.name":"io.debezium.time.ZonedTimestamp"}},{"name":"lastedittime","type":["null",{"type":"string","connect.version":1,"connect.name":"io.debezium.time.ZonedTimestamp"}],"default":null},{"name":"from","type":["null","string"],"default":null},{"name":"cityid","type":["null","long"],"default":null},{"name":"address","type":["null","string"],"default":null},{"name":"hide","type":"boolean"},{"name":"asktype","type":{"type":"int","connect.type":"int16"}},{"name":"baiduid","type":["null","string"],"default":null},{"name":"rcmdtime","type":["null",{"type":"string","connect.version":1,"connect.name":"io.debezium.time.ZonedTimestamp"}],"default":null},{"name":"coverimage","type":["null","string"],"default":null},{"name":"maingroup","type":["null","long"],"default":null}],"connect.name":"vimur2.ask.Value"}, application.id=ksql_}} (io.confluent.ksql.rest.server.computation.StatementExecutor:207)
io.confluent.ksql.parser.exception.ParseFailedException: line 2:351: extraneous input 'FROM' expecting {'ADD', 'APPROXIMATE', 'AT', 'CONFIDENCE', 'NO', 'SUBSTRING', 'POSITION', 'TINYINT', 'SMALLINT', 'INTEGER', 'DATE', 'TIME', 'TIMESTAMP', 'INTERVAL', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'ZONE', 'OVER', 'PARTITION', 'RANGE', 'ROWS', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'ROW', 'VIEW', 'REPLACE', 'GRANT', 'REVOKE', 'PRIVILEGES', 'PUBLIC', 'OPTION', 'EXPLAIN', 'ANALYZE', 'FORMAT', 'TYPE', 'TEXT', 'GRAPHVIZ', 'LOGICAL', 'DISTRIBUTED', 'TRY', 'SHOW', 'TABLES', 'SCHEMAS', 'CATALOGS', 'COLUMNS', 'COLUMN', 'USE', 'PARTITIONS', 'FUNCTIONS', 'TO', 'SYSTEM', 'BERNOULLI', 'POISSONIZED', 'TABLESAMPLE', 'RESCALED', 'ARRAY', 'MAP', 'SET', 'RESET', 'SESSION', 'DATA', 'START', 'TRANSACTION', 'COMMIT', 'ROLLBACK', 'WORK', 'ISOLATION', 'LEVEL', 'SERIALIZABLE', 'REPEATABLE', 'COMMITTED', 'UNCOMMITTED', 'READ', 'WRITE', 'ONLY', 'CALL', 'NFD', 'NFC', 'NFKD', 'NFKC', 'IF', 'NULLIF', 'COALESCE', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
	at io.confluent.ksql.parser.KsqlParser.buildAst(KsqlParser.java:62)
	at io.confluent.ksql.KsqlEngine.getStatements(KsqlEngine.java:431)
	at io.confluent.ksql.rest.server.StatementParser.parseSingleStatement(StatementParser.java:32)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatementWithTerminatedQueries(StatementExecutor.java:198)
	at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatement(StatementExecutor.java:108)
	at io.confluent.ksql.rest.server.computation.CommandRunner.executeStatement(CommandRunner.java:105)
	at io.confluent.ksql.rest.server.computation.CommandRunner.fetchAndRunCommands(CommandRunner.java:88)
	at io.confluent.ksql.rest.server.computation.CommandRunner.run(CommandRunner.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.confluent.ksql.parser.ParsingException: line 2:351: extraneous input 'FROM' expecting {'ADD', 'APPROXIMATE', 'AT', 'CONFIDENCE', 'NO', 'SUBSTRING', 'POSITION', 'TINYINT', 'SMALLINT', 'INTEGER', 'DATE', 'TIME', 'TIMESTAMP', 'INTERVAL', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'ZONE', 'OVER', 'PARTITION', 'RANGE', 'ROWS', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'ROW', 'VIEW', 'REPLACE', 'GRANT', 'REVOKE', 'PRIVILEGES', 'PUBLIC', 'OPTION', 'EXPLAIN', 'ANALYZE', 'FORMAT', 'TYPE', 'TEXT', 'GRAPHVIZ', 'LOGICAL', 'DISTRIBUTED', 'TRY', 'SHOW', 'TABLES', 'SCHEMAS', 'CATALOGS', 'COLUMNS', 'COLUMN', 'USE', 'PARTITIONS', 'FUNCTIONS', 'TO', 'SYSTEM', 'BERNOULLI', 'POISSONIZED', 'TABLESAMPLE', 'RESCALED', 'ARRAY', 'MAP', 'SET', 'RESET', 'SESSION', 'DATA', 'START', 'TRANSACTION', 'COMMIT', 'ROLLBACK', 'WORK', 'ISOLATION', 'LEVEL', 'SERIALIZABLE', 'REPEATABLE', 'COMMITTED', 'UNCOMMITTED', 'READ', 'WRITE', 'ONLY', 'CALL', 'NFD', 'NFC', 'NFKD', 'NFKC', 'IF', 'NULLIF', 'COALESCE', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
	at io.confluent.ksql.parser.KsqlParser$1.syntaxError(KsqlParser.java:124)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:349)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:513)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:238)
	at io.confluent.ksql.parser.SqlBaseParser.identifier(SqlBaseParser.java:8263)
	at io.confluent.ksql.parser.SqlBaseParser.tableElement(SqlBaseParser.java:1930)
	at io.confluent.ksql.parser.SqlBaseParser.statement(SqlBaseParser.java:1486)
	at io.confluent.ksql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:305)
	at io.confluent.ksql.parser.SqlBaseParser.statements(SqlBaseParser.java:253)
	at io.confluent.ksql.parser.KsqlParser.getParseTree(KsqlParser.java:107)
	at io.confluent.ksql.parser.KsqlParser.buildAst(KsqlParser.java:47)
	... 8 more
```
Looks like the generated statement contains a KSQL keyword 'FROM' because my AVRO schema contains a field called 'from', after checking the ANTLR grammar, I add backquote for the 'FROM' keyword, and the following statement works:
```sql
CREATE STREAM ASK_STREAM \
(ASKID BIGINT, \
`FROM` VARCHAR, \
.....)  \
WITH (KAFKA_TOPIC='vimur2.ask', VALUE_FORMAT='AVRO');
```
I am wondering if we should add backquote for KSQL keywords for the generated 'CREATE STREAM | CREATE TABLE' statement when using AVRO format or there is some other way to avoid this issue. Any help would be greatly appreciated

**Comment by apurvam** [comment]
This seems to be a dup of #677

**Comment by aylei** [comment]
@apurvam Not quite, my latter statement do escape the keyword `from` and works properly:
```
CREATE STREAM ASK_STREAM \
(ASKID BIGINT, \
`FROM` VARCHAR, \
.....)  \
WITH (KAFKA_TOPIC='vimur2.ask', VALUE_FORMAT='AVRO');
```
which means #677 occasionally works in this case, but the statement generated using AVRO schema have not made use of this feature to escape keywords.

**Comment by gjimher** [comment]
I submitted a PR  #1050 . Please be patient. It is my first one ;-)

**Comment by aylei** [comment]
@gjimher great! many thanks to you
