### ISSUE TITLE
FR: Support or fix multiple left joins in select expression.

### ISSUE THREAD

**Issue by aylei** [confluentinc/ksql#1044]
Hello folks,
I get the following error when I try to `left join` more than one table:
```
[2018-03-24 22:45:29,017] ERROR Failed to handle POST:io.confluent.ksql.rest.entity.KsqlRequest@db73b024 (io.confluent.ksql.rest.server.resources.KsqlResource:151)
io.confluent.ksql.parser.exception.ParseFailedException
	at io.confluent.ksql.parser.KsqlParser.buildAst(KsqlParser.java:62)
	at io.confluent.ksql.KsqlEngine.getStatements(KsqlEngine.java:431)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:135)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:408)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:583)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:524)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:461)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.confluent.ksql.util.DataSourceExtractor.visitJoinRelation(DataSourceExtractor.java:119)
	at io.confluent.ksql.util.DataSourceExtractor.visitJoinRelation(DataSourceExtractor.java:42)
	at io.confluent.ksql.parser.SqlBaseParser$JoinRelationContext.accept(SqlBaseParser.java:3543)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.util.DataSourceExtractor.visitQuerySpecification(DataSourceExtractor.java:66)
	at io.confluent.ksql.util.DataSourceExtractor.visitQuerySpecification(DataSourceExtractor.java:42)
	at io.confluent.ksql.parser.SqlBaseParser$QuerySpecificationContext.accept(SqlBaseParser.java:2416)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQueryPrimaryDefault(SqlBaseBaseVisitor.java:251)
	at io.confluent.ksql.parser.SqlBaseParser$QueryPrimaryDefaultContext.accept(SqlBaseParser.java:2234)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQueryTermDefault(SqlBaseBaseVisitor.java:244)
	at io.confluent.ksql.parser.SqlBaseParser$QueryTermDefaultContext.accept(SqlBaseParser.java:2162)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQueryNoWith(SqlBaseBaseVisitor.java:237)
	at io.confluent.ksql.parser.SqlBaseParser$QueryNoWithContext.accept(SqlBaseParser.java:2088)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitQuery(SqlBaseBaseVisitor.java:209)
	at io.confluent.ksql.parser.SqlBaseParser$QueryContext.accept(SqlBaseParser.java:1871)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitCreateStreamAs(SqlBaseBaseVisitor.java:146)
	at io.confluent.ksql.parser.SqlBaseParser$CreateStreamAsContext.accept(SqlBaseParser.java:710)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitSingleStatement(SqlBaseBaseVisitor.java:27)
	at io.confluent.ksql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:293)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.util.DataSourceExtractor.extractDataSources(DataSourceExtractor.java:144)
	at io.confluent.ksql.parser.KsqlParser.buildAst(KsqlParser.java:53)
	... 46 more
```
and I think the reason is same as #18 . I don't know if this is a bug or KSQL has never support multiple joins (I suppose the latter one). 
So, is there any plans to support or fix multiple joins?

**Comment by rodesai** [comment]
You are right - KSQL currently does not support multiple joins contained within a single statement. You can split this into multiple statements for the time being. Also, until this is implemented we should return a clearer error message. I'll file another issue to track that.

**Comment by rmoff** [comment]
Tracking issue for multi-join support: #1891
