### ISSUE TITLE
About ksql-cluster mode synchronization

### ISSUE THREAD

**Issue by ws2003gq** [confluentinc/ksql#1047]
I had 5 ksql-server(k1~k5) nodes depended on the same kafka env.
1. When I created a stream in k1, I can not find the new stream info in others ksql-servers.
Is that right?

 
2. I found some queries will be dead after running some days, but I also can see the query's describe by ksql-cli. How can i avoid it?

3. After I TERMINATE a query, How can I start it again?
Now I need to delete the attached stream,and create a new one.

**Comment by apurvam** [comment]
Regarding 1, this should not happen if all the servers are correctly configured to read and write to the command topic. Can you share the following:

1. The ksql.properties files from all the servers and the command you used to start them. Are all the ksql server versions the same?
2. The ksql.log files from all the servers at the time you started _one_ of the missing queries?

Regarding 2, This can happen if the streams application died due to a background error (ie. it wasn't terminated by ksql). In this case, the metastore will not be updated to reflect the stopped query. It's metrics won't be cleaned up, etc.. This will result in the situation you describe. #812 tracks part of the problem. 

Regarding 3, you should be able to restart a query after terminating it. What error are you getting?

**Comment by apurvam** [comment]
Also we fixed a couple of bugs #779 and #788 in the latest master/4.1.x branch which could cause your first problem. In these cases, it is possible that the query fails execution on some nodes due to race conditions. 

The fixes will be part of the upcoming 4.1.0 release.

**Comment by ws2003gq** [comment]
Thx for you help, I found  several changes after tag 0.5, which branch is good? Master?

**Comment by miguno** [comment]
@ws2003gq : I'd use 4.1.x for the moment.

**Comment by ws2003gq** [comment]
OK, I got it, there has a issue, if I have 2 ksql-server-node running today, and create a stream,
then I will get it in any of nodes. But I set kafka will clean up the topic in 24 hours(kafka default topic setting),
When I add a new  ksql-server-node in the  second day, it will never get any exsited stream info, cause of 
the ksql_command has been cleaned up.

**Comment by miguno** [comment]
@ws2003gq : Which KSQL version have you been running where your described issue has been a problem?

**Comment by ws2003gq** [comment]
ksql 0.4

**Comment by big-andy-coates** [comment]
HI @ws2003gq,

I've had a poke about in the code and it looks to be doing the right thing. That is, it will create the command topic with custom retention:

https://github.com/confluentinc/ksql/blob/eea96453dea11cec678c4d8b8b0f868471ef55c7/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java#L382-L388

Setting the retention on the command topic was only  on the 15th of Feb under #735.

So, I'm wondering if you started your KSQL journey on an older version, which wouldn't of set the retention?

**Comment by big-andy-coates** [comment]
I've raised a PR to fix the retention when starting the server, should users previously have created the topic with a previous version.

**Comment by apurvam** [comment]
Well, the 4.1.x branch does the right thing. But it also changes the name of the command topic. So we can't really help older users with this.

**Comment by ws2003gq** [comment]
OK, I will try new version (4.1.x). After complied it. I got a package named **ksql-package-4.1.0-SNAPSHOT-package.tgz**
but it can not start by error below :
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/rest/RestConfig
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
What I missed ?

**Comment by apurvam** [comment]
That package isn't the right one for 4.1.x. See #1069 for instructions on how to run it from source.

**Comment by big-andy-coates** [comment]
Fix merged to master
