### ISSUE TITLE
Error on queries to Tables using WHERE clause

### ISSUE THREAD

**Issue by e2raptor** [confluentinc/ksql#1106]
I've being following the examples as shown in the [quickstart](https://github.com/confluentinc/ksql/tree/v0.5/docs/quickstart#quick-start) to start playing with KSQL. (Not using docker) on a MacBook Pro with High Sierra.

After creating the table USERS_ORIGINAL I started to do some queries on it and they worked well:

`SELECT gender,Count(gender) FROM USERS_ORIGINAL GROUP BY gender;`
`MALE | 1`
`FEMALE | 1`

`SELECT userid,gender,Count(*) FROM USERS_ORIGINAL GROUP BY userid,gender;`
`User_2 | MALE | 1`
`User_5 | FEMALE | 1`

As soon as I add a WHERE clause:

`SELECT gender,Count(gender) FROM USERS_ORIGINAL WHERE gender='MALE' GROUP BY gender;`
`task [0_0] Failed to flush state store KSTREAM-REDUCE-STATE-STORE-0000000003`
`Caused by: null`
`Query terminated`

Sometimes (almost never) before it fails it shows 1 or 2 results from the query and then it fails as I specified before.

This doesn't happen with STREAMS, I did similar with the PAGEVIEWS_ORIGINAL stream and everything worked ok.

What could be causing this? Perhaps I'm missing a configuration or something?

Is there anything I can do to provide more information?

**Comment by rodesai** [comment]
Are there any errors printed in the ksql server log?

**Comment by e2raptor** [comment]
Yes, this is what the log shows:

```
[2018-04-02 20:34:22,061] ERROR task [0_0] Failed to flush state store KSTREAM-REDUCE-STATE-STORE-0000000003:  (org.apache.kafka.streams.processor.internals.ProcessorStateManager:249)
java.lang.NullPointerException
[2018-04-02 20:34:22,061] ERROR stream-thread [ksql_transient_1239562501204584520_1522719257869-eb9008e4-745c-4e20-9f54-4d806b745dda-StreamThread-249] Failed to commit stream task 0_0 due to the following error: (org.apache.kafka.streams.processor.internals.AssignedStreamsTasks:380)
org.apache.kafka.streams.errors.ProcessorStateException: task [0_0] Failed to flush state store KSTREAM-REDUCE-STATE-STORE-0000000003
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:247)
	at org.apache.kafka.streams.processor.internals.AbstractTask.flushState(AbstractTask.java:195)
	at org.apache.kafka.streams.processor.internals.StreamTask.flushState(StreamTask.java:330)
	at org.apache.kafka.streams.processor.internals.StreamTask$1.run(StreamTask.java:310)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:305)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:295)
	at org.apache.kafka.streams.processor.internals.AssignedTasks$1.apply(AssignedTasks.java:67)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.applyToRunningTasks(AssignedTasks.java:369)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.commit(AssignedTasks.java:359)
	at org.apache.kafka.streams.processor.internals.TaskManager.commitAll(TaskManager.java:414)
	at org.apache.kafka.streams.processor.internals.StreamThread.maybeCommit(StreamThread.java:1000)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:817)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:756)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:726)
Caused by: java.lang.NullPointerException
[2018-04-02 20:34:22,905] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:105)
org.apache.kafka.streams.errors.ProcessorStateException: task [0_0] Failed to flush state store KSTREAM-REDUCE-STATE-STORE-0000000003
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:247)
	at org.apache.kafka.streams.processor.internals.AbstractTask.flushState(AbstractTask.java:195)
	at org.apache.kafka.streams.processor.internals.StreamTask.flushState(StreamTask.java:330)
	at org.apache.kafka.streams.processor.internals.StreamTask$1.run(StreamTask.java:310)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:305)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:295)
	at org.apache.kafka.streams.processor.internals.AssignedTasks$1.apply(AssignedTasks.java:67)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.applyToRunningTasks(AssignedTasks.java:369)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.commit(AssignedTasks.java:359)
	at org.apache.kafka.streams.processor.internals.TaskManager.commitAll(TaskManager.java:414)
	at org.apache.kafka.streams.processor.internals.StreamThread.maybeCommit(StreamThread.java:1000)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:817)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:756)
```

**Comment by apurvam** [comment]
I think the problem is that we don't support aggregations on tables. see #778 . So it should work if you drop the 'count' clause from your statement.

**Comment by e2raptor** [comment]
@apurvam You are completely right. It was the aggregation.

**Comment by miguno** [comment]
FYI: KSQL supports a `HAVING` clause however:

```sql
CREATE TABLE possible_fraud AS
  SELECT card_number, count(*)
  FROM authorization_attempts
  WINDOW TUMBLING (SIZE 5 SECONDS)
  GROUP BY card_number
  HAVING count(*) > 3;
```

**Comment by apurvam** [comment]
@e2raptor our handling of aggregations on table is inconsistent, as you have seen. We will have proper support for it soon, and you will then be able to execute any combination of the queries above. But until then, recent versions will explicitly not allow any type of aggregation on a tables.
