### ISSUE TITLE
"LIMIT reached for the partition" should not generate ERROR

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1215]
Operators never want to see WARN/ERROR, and definitely not when the underlying behavior is valid and working as designed from customer perspective.

Therefore, when using "LIMIT", it should not generate an error in the logs:

```
[2018-04-26 09:32:58,438] ERROR stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] Failed to process stream task 0_7 due to the following error: (org.apache.kafka.streams.processor.internals.AssignedStreamsTasks:105)
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_7, processor=KSTREAM-SOURCE-0000000000, topic=users, partition=7, offset=3
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:240)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:411)
	at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:923)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:803)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
Caused by: io.confluent.ksql.util.KsqlException: LIMIT reached for the partition.
	at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:184)
	at io.confluent.ksql.structured.QueuedSchemaKStream$QueuePopulator.apply(QueuedSchemaKStream.java:161)
	at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:106)
	at org.apache.kafka.streams.kstream.internals.KTableMapValues$KTableMapValuesProcessor.process(KTableMapValues.java:83)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.ForwardingCacheFlushListener.apply(ForwardingCacheFlushListener.java:42)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putAndMaybeForward(CachingKeyValueStore.java:101)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.access$000(CachingKeyValueStore.java:38)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore$1.apply(CachingKeyValueStore.java:83)
	at org.apache.kafka.streams.state.internals.NamedCache.flush(NamedCache.java:142)
	at org.apache.kafka.streams.state.internals.NamedCache.evict(NamedCache.java:233)
	at org.apache.kafka.streams.state.internals.ThreadCache.maybeEvict(ThreadCache.java:243)
	at org.apache.kafka.streams.state.internals.ThreadCache.put(ThreadCache.java:153)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putInternal(CachingKeyValueStore.java:228)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:221)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.put(CachingKeyValueStore.java:38)
	at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.put(InnerMeteredKeyValueStore.java:198)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.put(MeteredKeyValueBytesStore.java:117)
	at org.apache.kafka.streams.kstream.internals.KStreamReduce$KStreamReduceProcessor.process(KStreamReduce.java:80)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:169)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:224)
	... 6 more
[2018-04-26 09:32:58,438] INFO stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] State transition from RUNNING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:200)
[2018-04-26 09:32:58,438] INFO stream-thread [_confluent-ksql-default_transient_125079666238829150_1524749569292-30d1d562-4cc2-41de-a909-2480b5aa2e7f-StreamThread-13] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1109)
```

**Comment by big-andy-coates** [comment]
Yep, I've seen this too - totally agree 👍
