### ISSUE TITLE
java.lang.NoClassDefFoundError: io/confluent/rest/RestConfig

### ISSUE THREAD

**Issue by MikeThomsen** [confluentinc/ksql#1239]
I downloaded the latest master and did `mvn install`. Per [#1069](https://github.com/confluentinc/ksql/issues/1069) that should be build KSQL and get the package ready for me to try out. I tried `bin/ksql-server-start -daemon etc/ksqk/ksql-server.properties` and got the following stacktrace:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/rest/RestConfig
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:80)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:44)
Caused by: java.lang.ClassNotFoundException: io.confluent.rest.RestConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

I can't seem to find any way around this.

**Comment by miguno** [comment]
Closing this old issue because of inactivity.  Feel free to reopen if needed, @MikeThomsen .

**Comment by wdonne** [comment]
Perhaps you tried this within ksql-package/target/ksql-package.../bin, as I did. When I run it from bin in the top-level folder then it works.
