### ISSUE TITLE
Bad message handling in KSQL

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1261]
Load data to topic (note the unquoted `user`, which makes the JSON invalid): 

```
$ echo '{"loadDate":1525271132954,"code":"Foo42",user:"Rick"}'|kafkacat -P -b localhost:9092 -t sensor_events
```

Register topic in KSQL: 

```
ksql> CREATE STREAM SENSOR_EVENTS (code VARCHAR, user VARCHAR) WITH (KAFKA_TOPIC='sensor_events',VALUE_FORMAT='JSON');

 Message
----------------
 Stream created
----------------
```

Set offset to earliest and try to query the stream: 
```
ksql> SET 'auto.offset.reset' = 'earliest';
Successfully changed local property 'auto.offset.reset' from 'earliest' to 'earliest'

ksql> SELECT * FROM SENSOR_EVENTS;
```

At this point nothing is returned by KSQL. The user is left with a hanging query and has to Ctrl-C. 

Digging about in the logs (located using `ps -ef|grep ksql-server|tr ' ' \n|grep log.dir`), I found `ksql-server.stdout` in the folder above, and within it: 

```
[2018-05-02 16:51:52,104] WARN Exception caught during Deserialization, taskId: 0_0, topic: sensor_events, partition: 0, offset: 0 (org.apache.kafka.streams.processor.internals.StreamThread:36)
org.apache.kafka.common.errors.SerializationException: KsqlJsonDeserializer failed to deserialize data for topic: sensor_events
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('u' (code 117)): was expecting double-quote to start field name
 at [Source: (byte[])"{"loadDate":1525274132954,"code":"Foo42",user:"Rick"}"; line: 1, column: 43]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:1991)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1642)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1000)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:247)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2559)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.getGenericRow(KsqlJsonDeserializer.java:74)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.deserialize(KsqlJsonDeserializer.java:63)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.deserialize(KsqlJsonDeserializer.java:39)
        at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65)
        at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55)
        at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:56)
        at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:51)
        at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:91)
        at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
        at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:560)
        at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:901)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
```

==> **This kind of error should be floated back up to the user**; they are not going to go digging around log files for it, they'll just assume that no data is present in the topic (and then get puzzled and frustrated when they realise that there is data in the topic…)

**Comment by rmoff** [comment]
To be clear - the cause of the error is a JSON snafu. This issue is raised to track the fact that the error is not thrown back to the user.

**Comment by miguno** [comment]
Did `DESCRIBE EXTENDED SENSOR_EVENTS ` show you that there are errors for this stream?

The behavior is the result of the current default behavior of KSQL, where it silently skips over malformatted data (= deserialization errors).  KSQL does track error/failure metrics as mentioned above (cf. `DESCRIBE EXTENDED` and `EXPLAIN <query>`), but we are not bubbling this up "pro-actively" into the CLI -- the user must check herself.

What would you have expected to happen here, @rmoff? Should we, for example, consider to notify the KSQL CLI user when (a) the user runs a non-persistent query (`SELECT ...` but not CS/CT/CSAS/CTAS) *and* (b) 100% of messages read by the query are failing to be deserialized?

**Comment by rmoff** [comment]
Sorry yes I should have said : `DESCRIBE EXTENDED SENSOR_EVENTS` show failed message count.

```
ksql> describe extended sensor_events;

Type                 : STREAM
Key field            :
Timestamp field      : Not set - using <ROWTIME>
Key format           : STRING
Value format         : JSON
Kafka output topic   : sensor_events (partitions: 1, replication: 1)

 Field    | Type
--------------------------------------
 ROWTIME  | BIGINT           (system)
 ROWKEY   | VARCHAR(STRING)  (system)
 LOADDATE | BIGINT
 CODE     | VARCHAR(STRING)
 USER     | VARCHAR(STRING)
--------------------------------------

Local runtime statistics
------------------------
messages-per-sec:         0   total-messages:         0     last-message:       n/a
 failed-messages:        10 failed-messages-per-sec:      0.06      last-failed: 02/05/18 16:45:25 BST
(Statistics of the local KSQL server interaction with the Kafka topic sensor_events)
```

It's a good point about silent dropping of messages. I would be inclined to say: 

1. by default bad data will abort the process and throw the error to the user. 
2. user can specify an optional threshold in the `WITH` parameters to say how many bad records can be skipped before aborting, or indeed, whether to just always drop bad records and continue regardless

        CREATE STREAM FOO WITH (KAFKA_TOPIC='BAR', VALUE_FORMAT='AVRO', BADMSG='IGNORE')
        CREATE STREAM FOO WITH (KAFKA_TOPIC='BAR', VALUE_FORMAT='AVRO', BADMSG='FAIL') <--default 

Expanding on (1) : Most of the time users will not realise they have bad data, and by 'pretending' that all is OK it causes more ambiguity. For example, if a user has 10 rows of data of which 2 are bad - when they run a query they're going to expect to see 10, and if not then a warning of 2 dropped, or an abort. By silently dropping them the user just sees 8 rows of data and wonders where the rest has gone. 

Maybe the runtime stats (or at least, failed count) should also be shown for `DESCRIBE` (not just `DESCRIBE EXTENDED`)? At this stage users with KSQL are generally not going to know where to go and look to realise there's a problem, so the more we can put it in front of them wherever they look, the better. Or, for a `SELECT` can the deserialisation errors be sent to the console just as a warning (suggestion (a) of yours above)?

**Comment by antonmos** [comment]
We ran into the same issue. It was extremely confusing because the query did not fail fast, and instead returned an empty result. 
Please please prioritize give the option to fail fast - it is very difficult to debug issues without errors.

**Comment by spena** [comment]
Query errors can be viewed from the `KSQL_PROCESSING_LOG`. We cannot fail-fast a query for one invalid row. I tested this and found the error in the processing log.

```
ksql> select * from ksql_processing_log;
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|LOGGER                                           |LEVEL                                            |TIME                                             |MESSAGE                                          |
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|processing.transient_SENSOR_EVENTS_88503869215582|ERROR                                            |1663617239411                                    |{TYPE=0, DESERIALIZATIONERROR={TARGET=value, ERRO|
|51795.KsqlTopic.Source.deserializer              |                                                 |                                                 |RMESSAGE=Failed to deserialize value from topic: |
|                                                 |                                                 |                                                 |sensor_events. Unexpected character ('u' (code 11|
|                                                 |                                                 |                                                 |7)): was expecting double-quote to start field na|
|                                                 |                                                 |                                                 |me, RECORDB64=null, CAUSE=[Unexpected character (|
|                                                 |                                                 |                                                 |'u' (code 117)): was expecting double-quote to st|
|                                                 |                                                 |                                                 |art field name], topic=sensor_events}, RECORDPROC|
|                                                 |                                                 |                                                 |ESSINGERROR=null, PRODUCTIONERROR=null, SERIALIZA|
|                                                 |                                                 |                                                 |TIONERROR=null, KAFKASTREAMSTHREADERROR=null}    |
```

**Comment by spena** [comment]
I'll close this ticket as there is no plan to fail-fast a query. This issue is from 2018 and the processing log was introduced in 2019/2020 I think.

**Comment by spena** [comment]
@colinhicks are there plans to fail-fast a query when a row cannot be deserialized?

**Comment by antonmos** [comment]
Could you please reopen this?  KSQL_PROCESSING_LOG allows to know why queries are silently returning incorrect data, but for some use cases absence of data can cause the system to behave incorrectly, e.g. "check if children of an entity are present in a compacted stream; if there aren't any, delete the parent".
