### ISSUE TITLE
KSQL Table select operation throws could not initialize class org.rocksdb.Options

### ISSUE THREAD

**Issue by sdandey** [confluentinc/ksql#1288]
After I performed a select query on a TABLE I created using a stream I get the following error.
`ksql> SELECT * FROM KAN_REQUEST_T LIMIT 5;
Could not initialize class org.rocksdb.Options
Query terminated`

on KSQL-server logs I see following exception.  Did any one ran through this issue before?

```
 (org.apache.kafka.streams.KafkaStreams:413)
[2018-05-17 00:31:36,987] INFO stream-thread [_confluent-ksql-default_transient_4910876246781346212_1526531496723-60e5e745-29b4-46ef-be23-fe8a4ddd7c61-StreamThread-47] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1129)
[2018-05-17 00:31:37,745] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:105)
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
        at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:116)
        at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:167)
        at org.apache.kafka.streams.state.internals.ChangeLoggingKeyValueBytesStore.init(ChangeLoggingKeyValueBytesStore.java:40)
        at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:63)
        at org.apache.kafka.streams.state.internals.InnerMeteredKeyValueStore.init(InnerMeteredKeyValueStore.java:160)
        at org.apache.kafka.streams.state.internals.MeteredKeyValueBytesStore.init(MeteredKeyValueBytesStore.java:102)
        at org.apache.kafka.streams.processor.internals.AbstractTask.registerStateStores(AbstractTask.java:225)
        at org.apache.kafka.streams.processor.internals.StreamTask.initializeStateStores(StreamTask.java:162)
        at org.apache.kafka.streams.processor.internals.AssignedTasks.initializeNewTasks(AssignedTasks.java:88)
        at org.apache.kafka.streams.processor.internals.TaskManager.updateNewAndRestoringTasks(TaskManager.java:316)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:794)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
[2018-05-17 00:31:37,750] INFO stream-client [_confluent-ksql-default_transient_4910876246781346212_1
```

**Comment by sdandey** [comment]
Using Linux

**Comment by smur89** [comment]
I experienced this issue while running on base docker image of openjdk:alpine. I reverted from Alpine and no longer had the issue, if that helps

**Comment by apurvam** [comment]
See: #1332

**Comment by jacoolw** [comment]
I applied the steps in #1332, but still get the error, java.io.tmpdir is set to /tmp and /tmp is writable. Is there anything else that could cause this error? (KSQL is running in a docker)

**Comment by jacoolw** [comment]
@miguno : No, the problem resolved once we removed the Docker.

**Comment by miguno** [comment]
> See #1332 for an explanation of what's going on, and for a solution.

Closing this thread for now.  Please report further issues in #1332 if needed.
