### ISSUE TITLE
PRINT skips record with ö character value

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1293]
Source topic: 

```
$ kafkacat -b localhost:9092 -t purchases -C
{"order_id":57,"customer_name":"Danya Kubiczek","date_of_birth":"1993-06-07T06:48:34Z","product":"Waffle Stix","order_total_usd":"1.47","town":"Augsburg","country":"Germany"}
{"order_id":58,"customer_name":"Deerdre Collen","date_of_birth":"1981-09-22T05:22:56Z","product":"Wine - Magnotta - Cab Franc","order_total_usd":"1.60","town":"Köln","country":"Germany"}
{"order_id":59,"customer_name":"Oralee Gillitt","date_of_birth":"1944-01-30T00:35:16Z","product":"Wine - Trimbach Pinot Blanc","order_total_usd":"1.13","town":"Alexandria","country":"United States"}
```

KSQL: 
```
ksql> print 'purchases' from beginning;{"ROWTIME":1525960258302,"ROWKEY":"null","order_id":57,"customer_name":"Danya Kubiczek","date_of_birth":"1993-06-07T06:48:34Z","product":"Waffle Stix","order_total_usd":"1.47","town":"Augsburg","country":"Germany"}
Unrecognized character escape 'x' (code 120)
 at [Source: (String)"{"order_id":58,"customer_name":"Deerdre Collen","date_of_birth":"1981-09-22T05:22:56Z","product":"Wine - Magnotta - Cab Franc","order_total_usd":"1.60","town":"K\xC3\xB6ln","country":"Germany"}"; line: 1, column: 164]
ksql>
```

**Comment by rmoff** [comment]
As of 5.0.0-SNAPSHOT the `PRINT` command doesn't barf, but it doesn't show the data either: 

```
ksql> print 'purchases' from beginning;
Format:JSON
{"ROWTIME":1529080116591,"ROWKEY":"null","order_id":57,"customer_name":"Danya Kubiczek","date_of_birth":"1993-06-07T06:48:34Z","product":"Waffle Stix","order_total_usd":"1.47","town":"Augsburg","country":"Germany"}
{"ROWTIME":1529080119097,"ROWKEY":"null","order_id":59,"customer_name":"Oralee Gillitt","date_of_birth":"1944-01-30T00:35:16Z","product":"Wine - Trimbach Pinot Blanc","order_total_usd":"1.13","town":"Alexandria","country":"United States"}
[ end of output ]
```

Topic contents: 
```
 kafkacat -b localhost:9092 -t purchases -C                                                                            
{"order_id":57,"customer_name":"Danya Kubiczek","date_of_birth":"1993-06-07T06:48:34Z","product":"Waffle Stix","order_total_usd":"1.47","town":"Augsburg","country":"Germany"}
{"order_id":58,"customer_name":"Deerdre Collen","date_of_birth":"1981-09-22T05:22:56Z","product":"Wine - Magnotta - Cab Franc","order_total_usd":"1.60","town":"Köln","country":"Germany"}
{"order_id":59,"customer_name":"Oralee Gillitt","date_of_birth":"1944-01-30T00:35:16Z","product":"Wine - Trimbach Pinot Blanc","order_total_usd":"1.13","town":"Alexandria","country":"United States"}
% Reached end of topic purchases [0] at offset 3
```

**Comment by rmoff** [comment]
Works fine with `SELECT`

```
ksql> CREATE STREAM PURCHASES (town varchar) WITH (KAFKA_TOPIC='purchases', VALUE_FORMAT='JSON');

 Message
----------------
 Stream created
----------------
ksql> SET 'auto.offset.reset' = 'earliest';
Successfully changed local property 'auto.offset.reset' from 'earliest' to 'earliest'
ksql> SELECT * FROM PURCHASES;
1529080116591 | null | Augsburg
1529080116965 | null | Köln
1529080119097 | null | Alexandria
```

**Comment by rmoff** [comment]
Still broken in 5.1. `PRINT` skips the record, and server logs an error: 

```
[2019-02-06 12:38:41,105] INFO Printing topic 'purchases' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:132)
[2019-02-06 12:38:41,134] WARN Exception formatting record (io.confluent.ksql.rest.server.resources.streaming.TopicStream$RecordFormatter:77)
com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'x' (code 120)
 at [Source: (String)"{"order_id":58,"customer_name":"Deerdre Collen","date_of_birth":"1981-09-22T05:22:56Z","product":"Wine - Magnotta - Cab Franc","order_total_usd":"1.60","town":"K\xC3\xB6ln","country":"Germany"}"; line: 1, column: 164]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._handleUnrecognizedCharacterEscape(ParserMinimalBase.java:646)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._decodeEscaped(ReaderBasedJsonParser.java:2522)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2043)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2016)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:264)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4056)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2551)
```

**Comment by agavra** [comment]
Still broken as of c0bfa41

**Comment by spena** [comment]
This is fixed and not reproducible in the latest master branch (0.11.0)
```
ksql> print 'purchases' from beginning;
Key format: ¯\_(ツ)_/¯ - no data processed
Value format: JSON or KAFKA_STRING
rowtime: 2020/06/22 18:16:09.077 Z, key: <null>, value: {"order_id":57,"customer_name":"Danya Kubiczek","date_of_birth":"1993-06-07T06:48:34Z","product":"Waffle Stix","order_total_usd":"1.47","town":"Augsburg","country":"Germany"}
rowtime: 2020/06/22 18:16:14.559 Z, key: <null>, value: {"order_id":58,"customer_name":"Deerdre Collen","date_of_birth":"1981-09-22T05:22:56Z","product":"Wine - Magnotta - Cab Franc","order_total_usd":"1.60","town":"Köln","country":"
Germany"}
rowtime: 2020/06/22 18:16:19.801 Z, key: <null>, value: {"order_id":59,"customer_name":"Oralee Gillitt","date_of_birth":"1944-01-30T00:35:16Z","product":"Wine - Trimbach Pinot Blanc","order_total_usd":"1.13","town":"Alexandria","coun
try":"United States"}
```
