### ISSUE TITLE
KSQL with IBM MessageHub Not Working

### ISSUE THREAD

**Issue by biswanathmukherjee** [confluentinc/ksql#1326]
Hello,
I am facing issue in connecting to IBM MessageHub using KSQL. IBM MessageHub is currently based on Kafka 0.10.2 whereas KSQL 4.1 is compatible with Kafka 0.11.x. Hence I am trying with KSQL 0.4.x branch. Please help!
Here are the issues:
i) KSQL 0.4.x branch does not compile out of the box. It throws the below error on mvn clean compile install -DskipTests. Please note I am able to build 4.1 branch as-is. So there is no firewall or mvn setup issue in my system.

The project io.confluent.ksql:ksql-parent:4.1.0-SNAPSHOT (/home/biswanath/ksql/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent.ksql:ksql-parent:4.1.0-SNAPSHOT: Could not find artifact io.confluent:common:pom:4.1.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]

ii) I somehow managed to build 0.4.x branch by modifying pom.xml (almost replacing the pom.xmls from 4.1 branch). But now, when I run: ./bin/ksql-server-start ./config/ksqlserver.properties
I am getting the below error:

Exception in thread "main" io.confluent.ksql.util.KsqlException: Could not fetch broker information. KSQL cannot initialize AdminCLient.
        at io.confluent.ksql.util.KafkaTopicClientImpl.init(KafkaTopicClientImpl.java:211)
        at io.confluent.ksql.util.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:54)
        at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:237)
        at io.confluent.ksql.rest.server.KsqlRestApplication.main(KsqlRestApplication.java:208)

Following is the content of ksqlserver.properties:
bootstrap.servers=ibm-mh-host1:port1,ibm-mh-host2:port2,ibm-mh-host13:port3,ibm-mh-host4:port4,ibm-mh-host5:port5
application.id=ksql_server_quickstart
ksql.command.topic.suffix=commands
listeners=http://localhost:8080
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
ssl.protocol=TLSv1.2
ssl.enabled.protocols=TLSv1.2
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="xxxxx" password="yyyyyy";
ksql.sink.replications.default=3

**Comment by miguno** [comment]
> IBM MessageHub is currently based on Kafka 0.10.2 whereas KSQL 4.1 is compatible with Kafka 0.11.x. Hence I am trying with KSQL 0.4.x branch. 

This was actually a bug in the documentation IIRC.  All prior KSQL versions including 0.4 only worked with Kafka 0.11 and later. They never worked with 0.10.2.

**Comment by agavra** [comment]
Hello @biswanathmukherjee - please let me know if using Kafka 0.11 helped solve your issue!
