### ISSUE TITLE
ksql launched with no parameters should give a nicer error message

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1443]
This is pretty yucky. We should catch the error and be much kinder to the user. Tell them the options for launching ksql, point to the docs, etc.

```
Robin@asgard02 ~> ksql
Exception in thread "main" javax.validation.ConstraintViolationException: Unrecognized field: kafkaClusterId
	at io.confluent.rest.validation.ConstraintViolations.simpleException(ConstraintViolations.java:50)
	at io.confluent.rest.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at io.confluent.ksql.rest.client.KsqlRestClient.makeRequest(KsqlRestClient.java:134)
	at io.confluent.ksql.rest.client.KsqlRestClient.getServerInfo(KsqlRestClient.java:119)
	at io.confluent.ksql.rest.client.KsqlRestClient.makeRootRequest(KsqlRestClient.java:115)
	at io.confluent.ksql.cli.Cli.validateClient(Cli.java:120)
	at io.confluent.ksql.cli.Cli.<init>(Cli.java:101)
	at io.confluent.ksql.Ksql.main(Ksql.java:56)
```

**Comment by vasiliybondarenko** [comment]
How a user can overcome the issue? I get the error while running a command ` ksql http://localhost:8090`

**Comment by rmoff** [comment]
@vasiliybondarenko it might be you're hitting a different issue, as that command should work. Can you raise a separate issue with steps to reproduce (what version you're running, how you're downloading it, how you're starting the stack up) and then if is related to this one we can link them—and if not we can help address the question separately. thanks!

**Comment by kirktrue** [comment]
Building off of `master` just now (`v5.1.0-SNAPSHOT`), I don't see any issues. When I run the server from tab A:

```
./bin/ksql-server-start config/ksql-server.properties
```

Then the CLI from tab B:

```
./bin/ksql
```

I get a nice banner message, help, and prompt:

```
                  
                  ===========================================
                  =        _  __ _____  ____  _             =
                  =       | |/ // ____|/ __ \| |            =
                  =       | ' /| (___ | |  | | |            =
                  =       |  <  \___ \| |  | | |            =
                  =       | . \ ____) | |__| | |____        =
                  =       |_|\_\_____/ \___\_\______|       =
                  =                                         =
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017-2018 Confluent Inc.

CLI v5.1.0-SNAPSHOT, Server v5.1.0-SNAPSHOT located at http://localhost:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> 
```

Are there other steps I'm missing?

**Comment by uurl** [comment]
@rmoff @rodesai running ksql command without parameters works fine. 
This issue should be closed.

**Comment by rmoff** [comment]
thanks @uurl
