### ISSUE TITLE
Failed to start KSQL : throws ERROR Failed to initialize TopicClient

### ISSUE THREAD

**Issue by rattaj** [confluentinc/ksql#1456]
I am using apache kafka_2.11-1.1.0 and latest KSQL from git repository. I have verified that kafka is working properly by pushing some data to topic & executing console producer /consumers. I executed below steps to use KSQL:

**Step 1** Get the code from git:
`git clone https://github.com/confluentinc/ksql.git`
**Step 2.** Build code using maven:
`mvn clean compile install -DskipTests` 
**Step 3.** Updated ksql configuration 'bootstrap.servers' to look for the appropriate broker.
**Step 4.** Start KSQL:
`./bin/ksql-server-start config/ksql-server.properties`
When I execute this command, I get below stack trace:

> [2018-06-19 01:30:25,561] ERROR Failed to initialize TopicClient: Unexpected resource type GROUP for resource 0 (io.confluent.ksql.util.KafkaTopicClient:270)
[2018-06-19 01:30:25,562] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:48)
io.confluent.ksql.util.KsqlException: Could not fetch broker information. KSQL cannot initialize
        at io.confluent.ksql.util.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:271)
        at io.confluent.ksql.util.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:76)
        at io.confluent.ksql.util.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:66)
        at io.confluent.ksql.KsqlEngine.<init>(KsqlEngine.java:153)
        at io.confluent.ksql.KsqlEngine.<init>(KsqlEngine.java:120)
        at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:299)
        at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:83)
        at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:45)
Caused by: org.apache.kafka.common.errors.InvalidRequestException: Unexpected resource type GROUP for resource 0

I need to use KSQL's standalone package and use it with existing kafka cluster. I have attached ksql log and maven log. 

[ksql.log](https://github.com/confluentinc/ksql/files/2114179/ksql.log)
[maven_kafka.log](https://github.com/confluentinc/ksql/files/2114180/maven_kafka.log)

**Comment by apurvam** [comment]
You are hitting https://issues.apache.org/jira/browse/KAFKA-7064 . It's a regression in Kafka's admin client which prevents newer versions of KSQL to run against any previous verision of kafka. It will be fixed in Kafka soon and then picked up in KSQL.

**Comment by rattaj** [comment]
ok, Thanks Apurv.

**Comment by apurvam** [comment]
Hi @rattaj. Did you try it again? Is it fixed?

**Comment by rattaj** [comment]
Hi @apurvam , It is working fine now.
Thanks much.

**Comment by apurvam** [comment]
Great, closing this out.

**Comment by MSrikar** [comment]
I'm facing same issue with 5.1 version. Could you please help me.

**Comment by Tin-Nguyen** [comment]
I’m using the latest version and be pacing with the same issue when trying to connect the remote kafka cluster (it works well with my local kafka)
