### ISSUE TITLE
UnsupportedOperationException in latest KSQL build

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1545]
Running this [script](https://github.com/confluentinc/quickstart-demos/blob/5.0.x/pageviews/ksql.commands) of KSQL commands results in the error:

```bash
ksql> run script 'ksql.commands';java.lang.UnsupportedOperationException
```

From the logs

```bash
java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at io.confluent.ksql.physical.PhysicalPlanBuilder.updateListProperty(PhysicalPlanBuilder.java:337)
        at io.confluent.ksql.physical.PhysicalPlanBuilder.buildStreams(PhysicalPlanBuilder.java:358)
        at io.confluent.ksql.physical.PhysicalPlanBuilder.buildPlanForStructuredOutputNode(PhysicalPlanBuilder.java:256)
        at io.confluent.ksql.physical.PhysicalPlanBuilder.buildPhysicalPlan(PhysicalPlanBuilder.java:150)
        at io.confluent.ksql.QueryEngine.buildQueryPhysicalPlan(QueryEngine.java:200)
        at io.confluent.ksql.QueryEngine.buildPhysicalPlans(QueryEngine.java:166)
        at io.confluent.ksql.KsqlEngine.planQueries(KsqlEngine.java:228)
        at io.confluent.ksql.KsqlEngine.buildMultipleQueries(KsqlEngine.java:211)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleRunScript(StatementExecutor.java:282)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.executeStatement(StatementExecutor.java:260)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatementWithTerminatedQueries(StatementExecutor.java:206)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatement(StatementExecutor.java:112)
        at io.confluent.ksql.rest.server.computation.CommandRunner.executeStatement(CommandRunner.java:105)
        at io.confluent.ksql.rest.server.computation.CommandRunner.fetchAndRunCommands(CommandRunner.java:88)
        at io.confluent.ksql.rest.server.computation.CommandRunner.run(CommandRunner.java:63)
        at java.lang.Thread.run(Thread.java:748)
```

This is a regression.  It works in earlier 5.0.x but fails in the latest KSQL release (SNAPSHOT-54)

**Comment by ybyzek** [comment]
Specific place in the script where it fails:

```bash

ksql> CREATE STREAM pageviews_original (viewtime bigint, userid varchar, pageid varchar) WITH (kafka_topic='pageviews', value_format='AVRO');

 Message        
----------------
 Stream created 
----------------
ksql> CREATE TABLE users_original (registertime bigint, gender varchar, regionid varchar, userid varchar) WITH (kafka_topic='users', value_format='AVRO', key = 'userid');

 Message       
---------------
 Table created 
---------------
ksql> CREATE STREAM pageviews_female AS SELECT users_original.userid AS userid, pageid, regionid, gender FROM pageviews_original LEFT JOIN users_original ON pageviews_original.userid = users_original.userid WHERE gender = 'FEMALE';
java.lang.UnsupportedOperationException
```
