### ISSUE TITLE
Stream to stream join causes timestamp extraction exception in KSQL5

### ISSUE THREAD

**Issue by IDispose** [confluentinc/ksql#1595]
This is a really interesting bug. 

It appears the in a `stream-to-stream` join the `timestamp` extractor code in `io.confluent.ksql.util.timestamp.LongTimeStampExtractor` uses the index of the `timestamp` column in the second stream to look for a `timestamp` column in the first stream.

Steps to reproduce

1. Create 3 streams with identical number of columns for example

`
CREATE STREAM MY_STREAM1 (P_KEY STRING, VALUE BIGINT, RECORDED_TIMESTAMP BIGINT) WITH (kafka_topic='my-topic-1', value_format='avro')
`

2. Create a joined stream to join `MY_STREAM1` and `MY_STREAM2`

`
CREATE STREAM MY_JOIN01_STREAM WITH (TIMESTAMP='RECORDED_TIMESTAMP') as SELECT a.P_KEY as P_KEY, a.RECORDED_TIMESTAMP as RECORDED_TIMESTAMP, a.VALUE as A_VALUE, b.VALUE as B_VALUE FROM MY_STREAM1 a inner join MY_STREAM2 b within 1 second ON a.P_KEY = b.P_KEY partition by P_KEY
`

This will create a stream with the schema

```
Field              | Type
------------------------------------------------
 ROWTIME                         | BIGINT           (system)
 ROWKEY                           | VARCHAR(STRING)  (system)
 P_KEY                                | VARCHAR(STRING)
 RECORDED_TIMESTAMP | BIGINT 
 A_VALUE                           | BIGINT
 B_VALUE                            | BIGINT
 
------------------------------------------------
```

3. Now try to join MY_JOIN01_STREAM with MY_STREAM2 like so

`
CREATE STREAM MY_JOIN02_STREAM WITH (TIMESTAMP='RECORDED_TIMESTAMP') as SELECT a.P_KEY as P_KEY, a.RECORDED_TIMESTAMP as RECORDED_TIMESTAMP, a.A_VALUE as A_VALUE, a.B_VALUE as B_VALUE, b.VALUE as C_VALUE FROM MY_JOIN01_STREAM a inner join MY_STREAM3 b within 1 second ON a.P_KEY = b.P_KEY partition by P_KEY
` 

Check `ksql` logs you should see an error that says

`
ERROR Exception in extracting timestamp for row: [ 'some key value' | 1530619322 | 123 | 456 ] (io.confluent.ksql.util.timestamp.LongTimestampExtractor:55)
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
        at java.util.LinkedList.get(LinkedList.java:476)
        at io.confluent.ksql.util.timestamp.LongTimestampExtractor.extract(LongTimestampExtractor.java:50)
        at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:105)
        at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
        at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:638)
        at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:936)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:831)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)
`

**Comment by dguy** [comment]
@IDispose, i've been trying to reproduce this, but so far no luck...

**Comment by IDispose** [comment]
@dguy thanks for confirming. I think the example has less number of columns than in the streams I have. My streams have 13 columns each and the location of the designated `TIMESTAMP` column in left and right streams are different. If I manage to ensure that the `TIMESTAMP` columns are in the same index it works.

**Comment by keithharper** [comment]
I feel like this should be re-opened. I just struggled with this situation for the second half of the day yesterday, and about an hour this morning. Once I realized I was getting a large number of exceptions upon stream creation (stream-table in my case), I knew it was likely not something I had done to cause it.

In my case, I had a stream defined as:
```
CREATE STREAM MEDIA_NOTE_REKEY \
WITH(VALUE_FORMAT='JSON', TIMESTAMP='last_updated_ts') AS \
select note_id, \
       media_id, \
       note, \
       custom_field_id, \
       stringtotimestamp(last_updated_ts, 'yyyy-MM-dd''T''HH:mm:ss''Z''') as last_updated_ts \
from MEDIA_NOTE_STREAM \
partition by note;
```

and a table defined as:
```
CREATE TABLE TABLE_IMPORTED_DATA_VALUE_IMPORT_FIELD \
(imported_data_id integer, \
 import_field_id integer, \
 imported_value VARCHAR, \
 last_updated_ts bigint) \
WITH (KAFKA_TOPIC='IMPORTED_DATA_VALUE_IMPORT_FIELD', VALUE_FORMAT='JSON', KEY='imported_value', TIMESTAMP='last_updated_ts');
```

and a stream-table join defined as:
```
CREATE STREAM IMPORTED_DATA_VALUE_ASSOCIATED_TO_NOTE WITH(TIMESTAMP='last_updated_ts') AS \
SELECT media_id, \
       imported_data_id, \
       imported_value, \
       note, \
       MEDIA_NOTE_REKEY.last_updated_ts as last_updated_ts \
FROM MEDIA_NOTE_REKEY \
join TABLE_IMPORTED_DATA_VALUE_IMPORT_FIELD \
on note = imported_value \
partition by imported_data_id;
```

This resulted in this exception for every record that is part of the join:
```
[2018-11-08 09:50:23,626] ERROR Exception in extracting timestamp for row: [ 12160 | 17 | 'Some Text' | 1521656041000 ] (io.confluent.ksql.util.timestamp.LongTimestampExtractor:55)
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at io.confluent.ksql.util.timestamp.LongTimestampExtractor.extract(LongTimestampExtractor.java:50)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:105)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:638)
	at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:936)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:831)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)

```

After stumbling upon this issue, I changed the `MEDIA_NOTE_REKEY` stream to the following:
```
CREATE STREAM MEDIA_NOTE_REKEY \
WITH(VALUE_FORMAT='JSON', TIMESTAMP='last_updated_ts') AS \
select note_id, \
       media_id, \
       note, \
       stringtotimestamp(last_updated_ts, 'yyyy-MM-dd''T''HH:mm:ss''Z''') as last_updated_ts, \
       custom_field_id \
from MEDIA_NOTE_STREAM \
partition by note;
```

This made the `last_updated_ts` column the 4th column (base-1) in both `MEDIA_NOTE_REKEY` and `TABLE_IMPORTED_DATA_VALUE_IMPORT_FIELD`

To me, this seems highly unreasonable to expect someone to be able to ensure that the timestamp column is always the `nth` column for any stream or table that might need to be joined together, while still maintaining timestamps.
