### ISSUE TITLE
KSQL UDF class loader error:Could not initialize class

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/ksql#1722]
i can run the jar package, but ksql report the class missing:
and i update the related code to github:
https://github.com/clojurians-org/my-ksql-udf-all/tree/master/my-ksql-udf-java
```
[larluo@larluo-nixos:~/work/git/my-repo/my-ksql-udf-all/my-ksql-udf-java]$ java -cp target/my-ksql-udf-java-0.0.1-standalone.jar my_ksql_udf.CompUDF 
fnsStr: bs2str.b64-encode.gzip.str2bs
fnObj: clojure.lang.Delay@15a04efb
H4sIAAAAAAAAAMtJLMopzQcAVpsYZQYAAAA=

ksql> SELECT comp() from USERS ;                  
larluo

ksql> SELECT comp('bs2str.b64-encode.gzip.str2bs', 'larluo') from USERS LIMIT 1 ;
null

[2018-08-09 23:42:52,642] ERROR Error calculating column with index 0 : KSQL_COL_0 (io.confluent.ksql.structured.SelectValueMapper:75)
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:756)
        at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:748)
        at io.confluent.ksql.structured.SelectValueMapper.apply(SelectValueMapper.java:72)
        at io.confluent.ksql.structured.SelectValueMapper.apply(SelectValueMapper.java:33)
        at org.apache.kafka.streams.kstream.internals.AbstractStream$2.apply(AbstractStream.java:87)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:40)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:50)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.runAndMeasureLatency(ProcessorNode.java:244)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:143)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:126)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:90)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:56)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:50)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.runAndMeasureLatency(ProcessorNode.java:244)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:143)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:126)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:90)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:50)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.runAndMeasureLatency(ProcessorNode.java:244)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:133)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:143)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:126)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:90)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:288)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:409)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:957)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:832)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class my_ksql_udf.Comp
        at my_ksql_udf.CompUDF.invoke(CompUDF.java:19)
        at my_ksql_udf.CompUDF_invoke.eval(Unknown Source)
        at io.confluent.ksql.function.udf.PluggableUdf.evaluate(PluggableUdf.java:45)
        at SC.eval0(Unknown Source)
        ... 37 more

**Comment by big-andy-coates** [comment]
Hi @clojurians-org 

My guess would be you're missing a dependency on the class path. 

From the error trace you posted I'd guess there is also an earlier error, from the first invocation, which gives details of what failed to initialize / what is missing.

**Comment by big-andy-coates** [comment]
In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
