### ISSUE TITLE
java.lang.NoClassDefFoundError running ksql-server cp-os 5.0

### ISSUE THREAD

**Issue by IDispose** [confluentinc/ksql#1767]
Uninstalled cp-os 4.1 and installed cp-os 5.0 When I run `confluent start` all the services except `ksql-server` start

This is the error in the log file (`confluent log sql-server`)

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/websocket/DeploymentException
        at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:83)
        at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:45)
Caused by: java.lang.ClassNotFoundException: javax.websocket.DeploymentException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

**Comment by IDispose** [comment]
Interestingly following these instructions results in the above error

https://docs.confluent.io/current/installation/installing_cp/rhel-centos.html

Uninstalled and installed using these

https://docs.confluent.io/current/installation/upgrade.html#upgrade

and cp-oss works !

**Comment by apurvam** [comment]
@IDispose  how did you uninstall cp-os-4.1. The latter 'upgrade' documentation has a bunch of steps to fully remove all dependencies, which the first link for a fresh install does not.

In particular, the diff includes 

```
 sudo yum remove confluent-kafka-2.11
# To remove Confluent-Platform and all its dependencies at once, run the following after stopping all services
  sudo yum autoremove confluent-platform-2.11

sudo rm /etc/yum.repos.d/confluent.repo
```

Without those steps, there could be a mix of dependencies, causing your `ClassNotFoundException`. It looks like the upgrade steps worked for your upgrade, so I think all is good.
