### ISSUE TITLE
Unable to deserialize responses with KsqlRestClient

### ISSUE THREAD

**Issue by cadeparker-civitas** [confluentinc/ksql#1768]
We are trying to send CREATE TABLE statements to our ksql server via the KsqlRestClient, but when the response is returned, the client fails with a Jackson deserialization error:

Our client usage:

```
  @Test
  public void testCreate() {
    String statement = "CREATE TABLE PERSON (EMPLID VARCHAR, birthdate BIGINT, BIRTHPLACE VARCHAR, BIRTHCOUNTRY VARCHAR, BIRTHSTATE VARCHAR) WITH (KAFKA_TOPIC = 'person', VALUE_FORMAT = 'JSON', KEY = 'EMPLID') ;";

    KsqlRestClient client = new KsqlRestClient("http://localhost:8088");

    client.makeKsqlRequest(statement);
  }
```

Which produces this error:

```
javax.ws.rs.ProcessingException: Error reading entity from input stream.

	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at io.confluent.ksql.rest.client.KsqlRestClient.makeKsqlRequest(KsqlRestClient.java:144)
	at com.civitaslearning.platform.integrate.provisioning.graphschema.IntegrationPackKsqlGeneratorTest.testCreate(IntegrationPackKsqlGeneratorTest.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id '@type' into a subtype of [simple type, class io.confluent.ksql.rest.entity.KsqlEntity]: known type ids = [KsqlEntity, currentStatus, description, error, executionPlan, kafka_topics, ksql_topics, properties, queries, streams, tables, topic_description]
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@21680803; line: 1, column: 3] (through reference chain: io.confluent.ksql.rest.entity.KsqlEntityList[0])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:104)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at io.confluent.rest.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:71)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	... 33 more
```

The actual request succeeds with status code 200, but the client fails to deserialize the json string into the KsqlEntityList class.

Using my debugger, I found the actual json string to be:
```
[
  {
    "@type": "currentStatus",
    "statementText": "CREATE TABLE PERSON (EMPLID VARCHAR, birthdate BIGINT, BIRTHPLACE VARCHAR, BIRTHCOUNTRY VARCHAR, BIRTHSTATE VARCHAR) WITH (KAFKA_TOPIC = 'person', VALUE_FORMAT = 'JSON', KEY = 'EMPLID') ;",
    "commandId": "table/PERSON/create",
    "commandStatus": {
      "status": "SUCCESS",
      "message": "Table created"
    }
  }
]
```

I wrote a simple test case to see if I could use an ObjectMapper to deserialize the string, but that also threw an exception for a bad "type id":

```
  String respJson =
      "[{"
          + "\"@type\":\"currentStatus\","
          + "\"statementText\":\"CREATE TABLE PERSON (EMPLID VARCHAR, birthdate BIGINT, "
              + "BIRTHPLACE VARCHAR, BIRTHCOUNTRY VARCHAR, BIRTHSTATE VARCHAR) WITH (KAFKA_TOPIC = 'person', "
              + "VALUE_FORMAT = 'JSON', KEY = 'EMPLID') ;\","
          + "\"commandId\":\"table/PERSON/create\","
          + "\"commandStatus\":{\"status\":\"SUCCESS\","
          + "\"message\":\"Table created\"}}]";

  @Test
  public void deserialize() throws IOException {
    ObjectMapper mapper = new ObjectMapper();
    mapper.readValue(respJson, KsqlEntityList.class);
  }
```

Which produces this error:
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id '@type' into a subtype of [simple type, class io.confluent.ksql.rest.entity.KsqlEntity]: known type ids = [KsqlEntity, currentStatus, description, error, executionPlan, kafka_topics, ksql_topics, properties, queries, streams, tables, topic_description]
 at [Source: [{"@type":"currentStatus","statementText":"CREATE TABLE PERSON (EMPLID VARCHAR, birthdate BIGINT, BIRTHPLACE VARCHAR, BIRTHCOUNTRY VARCHAR, BIRTHSTATE VARCHAR) WITH (KAFKA_TOPIC = 'person', VALUE_FORMAT = 'JSON', KEY = 'EMPLID') ;","commandId":"table/PERSON/create","commandStatus":{"status":"SUCCESS","message":"Table created"}}]; line: 1, column: 3] (through reference chain: io.confluent.ksql.rest.entity.KsqlEntityList[0])

	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:104)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
```

We are using jackson 2.8.10 in the test above.

The KSQL server is running v5.0.0 as provided by the Confluent Enterprise 5.0 download

**Comment by rodesai** [comment]
What version of the client are you running?

**Comment by cadeparker-civitas** [comment]
Looks like we were still using the 4.1.0 client. Using the models from the 5.0.0 package worked as expected. Sorry to bother! Thanks for the help!
