### ISSUE TITLE
HTTPS connection between KSQL client and server not fully supported (also impacts Confluent Control Center)

### ISSUE THREAD

**Issue by andybryant** [confluentinc/ksql#1834]
We have secured our Kafka cluster with SSL authentication on brokers and schema registry.
When using ksql-server 5.0.0 docker image against this cluster where it's listening on client connections on http everything works as expected.

When we switch ksql-server to expect https traffic (`KSQL_LISTENERS=https://0.0.0.0:8088`) we can connect successfully from a client, create streams, print topic contents, but when we attempt to run an interactive query it never shows any results.

In the KSQL-server logs we see the following exception

```
[2018-09-06 05:12:55,496] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:119)
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:235)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:217)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:398)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.flush(ResponseWriter.java:330)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:287)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.flush(WriterInterceptorExecutor.java:305)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1141)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3910)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3176)
	at io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter.write(QueryStreamWriter.java:129)
	at io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter.write(QueryStreamWriter.java:94)
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:79)
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:61)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:280)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:409)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:584)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by juyttenh** [comment]
Can you share your ksql-server https configuration, and your client configuration?

**Comment by andybryant** [comment]
Here's the environment variables passed to the docker image, anonymised somewhat with passwords removed...

Integration with Kafka and schema registry are working fine (we're able to read avro data). The toggle between having it work and fail is changing `KSQL_LISTENERS` between http and https

```"KSQL_BOOTSTRAP_SERVERS": "SSL://kafka00.pre.cld.ecorp:9094,SSL://kafka01.pre.cld.ecorp:9094,SSL://kafka02.pre.cld.ecorp:9094",
"KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE": "false",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS": "SSL://kafka00.pre.cld.ecorp:9094,SSL://kafka01.pre.cld.ecorp:9094,SSL://kafka02.pre.cld.ecorp:9094",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL": "SSL",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEYSTORE_LOCATION": "/etc/kafka/secrets/ksql.pre.cld.ecorp.keystore.jks",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEYSTORE_PASSWORD": "********",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEY_PASSWORD": "********",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_TRUSTSTORE_LOCATION": "/etc/ssecorp.truststore.jks",
"KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_TRUSTSTORE_PASSWORD": "********",
"KSQL_CONSUMER_INTERCEPTOR_CLASSES": "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor",
"KSQL_CONSUMER_SECURITY_PROTOCOL": "SSL",
"KSQL_KSQL_SCHEMA_REGISTRY_URL": "https://schema.pre.cld.ecorp:8081",
"KSQL_KSQL_SERVICE_ID": "cld-ksql-server",
"KSQL_LISTENERS": "https://0.0.0.0:8088",
"KSQL_LOG4J_ROOT_LOGLEVEL": "DEBUG",
"KSQL_OPTS": "-Djavax.net.ssl.trustStore=/etc/ssecorp.truststore.jks -Djavax.net.ssl.trustStorePassword=******** -Djavax.net.ssl.keyStore=/etc/kafka/secrets/ksql.pre.cld.ecorp.keystore.jks -Djavax.net.ssl.keyStorePassword=********",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS": "SSL://kafka00.pre.cld.ecorp:9094,SSL://kafka01.pre.cld.ecorp:9094,SSL://kafka02.pre.cld.ecorp:9094",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL": "SSL",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEYSTORE_LOCATION": "/etc/kafka/secrets/ksql.pre.cld.ecorp.keystore.jks",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEYSTORE_PASSWORD": "********",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEY_PASSWORD": "********",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_TRUSTSTORE_LOCATION": "/etc/ssecorp.truststore.jks",
"KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SSL_TRUSTSTORE_PASSWORD": "********",
"KSQL_PRODUCER_INTERCEPTOR_CLASSES": "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor",
"KSQL_PRODUCER_SECURITY_PROTOCOL": "SSL",
"KSQL_SECURITY_PROTOCOL": "SSL",
"KSQL_SINK_REPLICAS": "3",
"KSQL_SSL_KEYSTORE_LOCATION": "/etc/kafka/secrets/ksql.pre.cld.ecorp.keystore.jks",
"KSQL_SSL_KEYSTORE_PASSWORD": "********",
"KSQL_SSL_KEY_PASSWORD": "********",
"KSQL_SSL_TRUSTSTORE_LOCATION": "/etc/ssecorp.truststore.jks",
"KSQL_SSL_TRUSTSTORE_PASSWORD": "********",
"KSQL_STREAMS_NUM_STANDBY_REPLICAS": "0",
"KSQL_STREAMS_PRODUCER_CONFLUENT_BATCH_EXPIRY_MS": "9223372036854775807",
"KSQL_STREAMS_PRODUCER_MAX_BLOCK_MS": "9223372036854775807",
"KSQL_STREAMS_PRODUCER_REQUEST_TIMEOUT_MS": "300000",
"KSQL_STREAMS_PRODUCER_RETRIES": "2147483647",
"KSQL_STREAMS_REPLICATION_FACTOR": "3",
"KSQL_UI_ENABLED": "false",
```

**Comment by apurvam** [comment]
The KSQL rest end point doesn't support HTTPS yet. I'll mark this as an enhancement.

**Comment by andybryant** [comment]
Note this also has the knock-on effect that to be able to execute live queries in Control Center _**both**_ KSQL-Server and Control Center need to listen on http rather than https.

**Comment by big-andy-coates** [comment]
The above patch adds some basic SSL support to the CLI.

However, it looks like this issue maybe caused by Kafka and KSQL using different key and trust stores.  If that is the case, then the problem may still exist as the above patch is just a CLI change, where as supporting separate SSL properties for KSQL and the external services it uses will need a change in the server.

Potentially related to: https://github.com/confluentinc/ksql/issues/1821

**Comment by big-andy-coates** [comment]
Reopening as I'm not convinced my PR fixes this specific issue.
