### ISSUE TITLE
Aggregate function at Joining null results throwing NullPointerException

### ISSUE THREAD

**Issue by asifakb** [confluentinc/ksql#1879]
I'm trying to join a table and a stream as follows where there is a possibility that product_price could not be found for a given product...I was expecting zero if there is no match/null result..but getting a NullPointerException.... 

```
select F.product_id, sum(cast(P.product_price as double)) as total_purchased FROM cust_info_stream F LEFT OUTER JOIN products_table P ON P.product_id = F.product_id group by F.product_id;

nt_type=CONSUMER session= cluster=pMoRwL4KTIuaNbup86ZY2A group=_confluent-ksql-default_transient_7149059076021906962_1536773581018 (io.confluent.monitoring.clients.interceptor.MonitoringInterceptor:320)
[2018-09-12 17:33:05,326] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:119)
java.lang.NullPointerException
        at io.confluent.ksql.function.udaf.sum.DoubleSumKudaf.aggregate(DoubleSumKudaf.java:42)
        at io.confluent.ksql.function.udaf.sum.DoubleSumKudaf.aggregate(DoubleSumKudaf.java:29)
        at io.confluent.ksql.function.udaf.KudafAggregator.lambda$apply$1(KudafAggregator.java:56)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at io.confluent.ksql.function.udaf.KudafAggregator.apply(KudafAggregator.java:53)
        at io.confluent.ksql.function.udaf.KudafAggregator.apply(KudafAggregator.java:30)
        at org.apache.kafka.streams.kstream.internals.KStreamAggregate$KStreamAggregateProcessor.process(KStreamAggregate.java:91)
```

**Comment by asifakb** [comment]
We can avoid it by doing an explicit null check like this but that takes away the very purpose of left outer join. It would be nice if the function returns ZERO in case aggregate function receives a null value ...

`select F.product_id, sum(cast(P.product_price as double)) as total_purchased FROM cust_info_stream F LEFT OUTER JOIN products_table P ON P.product_id = F.product_id WHERE P.product_price is NOT NULL group by F.product_id;`

**Comment by vcrfxia** [comment]
Closing as this issue is no longer present on `master` (i.e., has since been fixed):
```
ksql> create stream orders with (kafka_topic='orders',value_format='json',partitions=1,replicas=1);

 Message
----------------
 Stream created
----------------
ksql> create table products (product_id varchar, product_price varchar) with (kafka_topic='products',value_format='json',key='product_id',partitions=1,replicas=1);

 Message
---------------
 Table created
---------------
ksql> select o.product_id, sum(cast(p.product_price as double)) as total_purchased from orders o left outer join products p on p.product_id = o.product_id group by o.product_id emit changes;
+----------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+
|O_PRODUCT_ID                                                                                        |TOTAL_PURCHASED                                                                                     |
+----------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+
|foo                                                                                                 |0.0                                                                                                 |
```
after sending the record 
```
$ ./bin/kafka-console-producer --broker-list localhost:9092 --topic orders
>{"product_id":"foo"}
```
