### ISSUE TITLE
Badly Formatted JSON not in `DESCRIBE EXTENDED` Runtime Stats

### ISSUE THREAD

**Issue by mattdonders** [confluentinc/ksql#2005]
I saw a previous issue opened by @rmoff about presenting errors of failed messages back into the `DESCRIBE EXTENDED` view which was great, but for some reason badly formatted JSON is not showing up in the **failed-messages** section.

Here is my badly formatted JSON (missing quotes and mis-matched braces):
```
kafka-console-producer --broker-list 172.19.40.128:9092 --topic _json_metricbeat
>{@timestamp:"2018-10-03T14:17:13.646Z","@metadata":{"beat":"metricbeat","type":"doc","version":"6.2.2","topic":"metricbeat"}
```

These errors show up in the `ksql-server.stdout` log - 
```
[2018-10-05 10:48:42,424] WARN task [0_0] Skipping record due to deserialization error. topic=[_json_metricbeat] partition=[0] offset=[59141] (org.apache.kafka.streams.processor.internals.RecordDeserializer:86)
org.apache.kafka.common.errors.SerializationException: KsqlJsonDeserializer failed to deserialize data for topic: _json_metricbeat
Caused by: java.lang.NullPointerException
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer$CaseInsensitiveJsonNode.<init>(KsqlJsonDeserializer.java:193)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.getGenericRow(KsqlJsonDeserializer.java:89)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.deserialize(KsqlJsonDeserializer.java:77)
        at io.confluent.ksql.serde.json.KsqlJsonDeserializer.deserialize(KsqlJsonDeserializer.java:45)
        at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65)
        at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55)
        at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:63)
        at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66)
        at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:97)
        at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:117)
        at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:638)
        at org.apache.kafka.streams.processor.internals.StreamThread.addRecordsToTasks(StreamThread.java:936)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:831)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)
```

But they do not show up in the `DESCRIBE EXTENDED` query within the KSQL CLI (abridged output).
```
ksql> describe extended METRICBEAT_TARGET;

Name                 : METRICBEAT_TARGET
Type                 : STREAM
Key field            :
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : AVRO
Kafka topic          : metricbeat (partitions: 1, replication: 1)

Queries that write into this STREAM
-----------------------------------
CSAS_METRICBEAT_TARGET_0 : CREATE STREAM metricbeat_target WITH (VALUE_FORMAT='AVRO', KAFKA_TOPIC='metricbeat', PARTITIONS=1) AS SELECT * FROM metricbeat_source;

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------
messages-per-sec:         0   total-messages:     59041     last-message: 10/5/18 10:47:05 AM EDT
 failed-messages:         0 failed-messages-per-sec:         0      last-failed:       n/a
(Statistics of the local KSQL server interaction with the Kafka topic metricbeat)
```

I was under the assumption that badly formatted messages should produce an error that shows up in this view. Is this not the case? Also, is there a way (using KSQL) to have these messages go into an error topic as well?

**Comment by rodesai** [comment]
@mattdonders this was fixed in KSQL 5.1 (https://github.com/confluentinc/ksql/pull/1979) Which version did you observe this in?
