### ISSUE TITLE
 Unable to create AVRO table from AVRO stream

### ISSUE THREAD

**Issue by fortinj66** [confluentinc/ksql#2248]
I'm having an issue with creating an AVRO table with an AVRO stream.  The stream is directly imported into KSQL from and avro based kafka topic:

```
ksql> create stream DSB_ERROR_STREAM with (kafka_topic='dev-dsb-errors', value_format='AVRO', key='dsb_server');

 Message
----------------
 Stream created
----------------

ksql> show streams;

 Stream Name      | Kafka Topic    | Format
--------------------------------------------
 DSB_ERROR_STREAM | dev-dsb-errors | AVRO
--------------------------------------------

ksql> describe extended DSB_ERROR_STREAM;

Name                 : DSB_ERROR_STREAM
Type                 : STREAM
Key field            : DSB_SERVER
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : AVRO
Kafka topic          : dev-dsb-errors (partitions: 1, replication: 1)

 Field      | Type
----------------------------------------
 ROWTIME    | BIGINT           (system)
 ROWKEY     | VARCHAR(STRING)  (system)
 TIMESTAMP  | BIGINT
 DSB_SERVER | VARCHAR(STRING)
 ACCOUNT    | VARCHAR(STRING)
 MOD_CLASS  | VARCHAR(STRING)
 METHOD     | VARCHAR(STRING)
 TIMEOUT    | INTEGER
----------------------------------------

Local runtime statistics
------------------------


(Statistics of the local KSQL server interaction with the Kafka topic dev-dsb-errors)
```
I can read and select from the stream with no issue and also have no issue running windowing aggregations...

However, when I try to create a table using the same aggregation, the table create fails:

```
ksql> create table DSB_ERROR_STREAM_windowed as \ 
                  select mod_class, method, timeout, count(*) \
                  from DSB_ERROR_STREAM window session ( 60 seconds) \
                  group by mod_class, method, timeout having count(*) > 0;
io.confluent.ksql.util.KsqlException: Could not connect to Schema Registry service: Subject not found.; error code: 40401
```

and the error from the ksql.log:

```
[2018-12-07 15:14:36,333] ERROR Failed to handle: Command{statement='create table DSB_ERROR_STREAM_windowed as  select mod_class, method, timeout, count(*)  from DSB_ERROR_STREAM window session ( 60 seconds)   group by mod_class, method, timeout  having count(*) > 0;', overwriteProperties={}} (io.confluent.ksql.rest.server.computation.StatementExecutor:167)
io.confluent.ksql.util.KsqlException: Could not connect to Schema Registry service: Subject not found.; error code: 40401
        at io.confluent.ksql.util.AvroUtil.isValidAvroSchemaForTopic(AvroUtil.java:228)
        at io.confluent.ksql.util.AvroUtil.isValidSchemaEvolution(AvroUtil.java:212)
        at io.confluent.ksql.KsqlEngine.lambda$validateQueries$4(KsqlEngine.java:363)
        at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
        at io.confluent.ksql.KsqlEngine.validateQueries(KsqlEngine.java:344)
        at io.confluent.ksql.KsqlEngine.doExecute(KsqlEngine.java:337)
        at io.confluent.ksql.KsqlEngine.execute(KsqlEngine.java:263)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.startQuery(StatementExecutor.java:291)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleCreateAsSelect(StatementExecutor.java:265)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.executeStatement(StatementExecutor.java:193)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatementWithTerminatedQueries(StatementExecutor.java:164)
        at io.confluent.ksql.rest.server.computation.StatementExecutor.handleStatement(StatementExecutor.java:90)
        at io.confluent.ksql.rest.server.computation.CommandRunner.lambda$executeStatement$2(CommandRunner.java:121)
        at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:65)
        at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:38)
        at io.confluent.ksql.rest.server.computation.CommandRunner.executeStatement(CommandRunner.java:117)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.confluent.ksql.rest.server.computation.CommandRunner.fetchAndRunCommands(CommandRunner.java:92)
        at io.confluent.ksql.rest.server.computation.CommandRunner.run(CommandRunner.java:67)
        at java.lang.Thread.run(Thread.java:748)
```

The following are the subjects contained in the schema-registry:
```
(from http://kafka-d01:8081/subjects)
[
    "dev-dsb-errors-key",
    "dev-dsb-errors-value",
]
```

I did build this version off of the KSQL master branch:

```
git log
commit 5abb0f61ee6b518a88feeb9cfce7b77e2cb237ce
Author: Andy Coates <8012398+big-andy-coates@users.noreply.github.com>
Date:   Wed Dec 5 14:18:19 2018 +0000

    Fix some CLI line termination issues (#2214)
```

I'm at a bit of a loss as to how to debug this further...

--John

**Comment by fortinj66** [comment]
Well, I rebuilt the source from branch 5.1.x and it seems to work...

Something is broken in master then?

**Comment by fortinj66** [comment]
Closing as this seems to work.  I'll open a new issue for my current issues...
