### ISSUE TITLE
Cluster Authorization failure with ksql

### ISSUE THREAD

**Issue by chetann** [confluentinc/ksql#2290]
Hi,

I am using confluent 5.1 version, and we have a secure cluster across. So with KSQL I end up getting this error.
```
[root@tg-plkn-kmh3mxtgngfu-xarthuf4ureb-server-atralyhizbst ksql-cli]# cat cli-181219-071058.log
[2018-12-19 07:10:59,206] ERROR Failed to initialize TopicClient: Cluster authorization failed. (io.confluent.ksql.util.KafkaTopicClient:259)
[2018-12-19 07:10:59,209] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:45)
io.confluent.ksql.util.KsqlException: Could not fetch broker information. KSQL cannot initialize
    at io.confluent.ksql.util.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:260)
    at io.confluent.ksql.util.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:57)
    at io.confluent.ksql.KsqlEngine.create(KsqlEngine.java:115)
    at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:287)
    at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:80)
    at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:42)
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.```

I did resolve this by doing a workaround which is by providing open permissions at cluster level and it works fine.
```Current ACLs for resource `Cluster:kafka-cluster`:
     User:* has Allow permission for operations: Create from hosts: *
    User:* has Allow permission for operations: All from hosts: *```

But this is kind off not allowed to be done due to security reasons. So is there a way to get this working through using certs ACLs and getting handshake done between KSQL and Kafka. If so where can I provide the cert details in KSQL while running the service?

**Comment by dguy** [comment]
Have you had a look at: https://docs.confluent.io/current/ksql/docs/installation/server-config/security.html ?
