### ISSUE TITLE
ConcurrentModificationException when shutting down KSQL 

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2339]
```
[2019-01-11 17:44:23,981] ERROR Exception while waiting for CommandRunner thread to complete (io.confluent.ksql.rest.server.KsqlRestApplication:191)
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2103)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2058)
	at io.confluent.ksql.rest.server.CommandTopic.close(CommandTopic.java:137)
	at io.confluent.ksql.rest.server.computation.CommandStore.close(CommandStore.java:79)
	at io.confluent.ksql.rest.server.computation.CommandRunner.close(CommandRunner.java:110)
	at io.confluent.ksql.rest.server.KsqlRestApplication.stop(KsqlRestApplication.java:188)
	at io.confluent.ksql.test.util.TestKsqlRestApp.after(TestKsqlRestApp.java:163)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by big-andy-coates** [comment]
No one has been able to recreate...
