### ISSUE TITLE
Tab in multi-line input causes org.jline.reader.EOFError

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2350]
By default, KSQL CLI will ignore the tab character at the beginning of a new line. However if a multi-line statement is used, a tab will cause an error: 

```
ksql> PRINT \
>Jan 15, 2019 2:34:31 PM org.jline.utils.Log logr
INFO: Error while parsing line
org.jline.reader.EOFError: Escaped new line
        at org.jline.reader.impl.DefaultParser.parse(DefaultParser.java:163)
        at io.confluent.ksql.cli.console.TrimmingParser.parse(TrimmingParser.java:49)
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:3952)
        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:3875)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:585)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
        at io.confluent.ksql.cli.console.JLineReader.readLine(JLineReader.java:125)
        at io.confluent.ksql.cli.Cli.readLine(Cli.java:218)
        at io.confluent.ksql.cli.Cli.runInteractively(Cli.java:102)
        at io.confluent.ksql.Ksql.main(Ksql.java:64)
```

To reproduce the above, enter the keys `P R I N T \ <return> <tab>`

The reason that this is a problem is that pasted code samples may inadvertently have tabs present, causing a confusing experience for the user.

Confluent Platform 5.1.0

**Comment by big-andy-coates** [comment]
Tested in master - this is no longer an issue.

@rmoff, would you mind re-testing to ensure you agree, please?

**Comment by rmoff** [comment]
Tested against master, issue is still present:

![ksql](https://user-images.githubusercontent.com/3671582/52484783-139f7800-2baf-11e9-807e-00e5de6d7c7e.gif)

**Comment by ouertani** [comment]
@rmoff could you please check #2734
