### ISSUE TITLE
KSQL Problem while - print <topic> from beginning

### ISSUE THREAD

**Issue by authorjapps** [confluentinc/ksql#2386]
Hello, I have hit with this issue while querying KSQL server
+ Via REST api call(two issues here)
  + Producing/Consuming as plain raw text message - `String` SerDe
  + Putting as avro message - `KafkaAvro` SerDe
+ Via KSQL-cli

## Via REST api call - `String` SerDe
```java
url:http://localhost:8088/query
method:POST
request:
{
  "headers" : {
    "Content-Type" : "application/vnd.ksql.v1+json; charset=utf-8",
    "Accept" : "application/vnd.ksql.v1+json"
  },
  "body" : {
    "ksql" : "print 'demo-ksql' from beginning;",
    "streamsProperties" : { }
  }
} 

Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Wed, 23 Jan 2019 07:41:41 GMT" ],
    "Server" : [ "Jetty(9.4.12.v20180830)" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Vary" : [ "Accept-Encoding, User-Agent" ],
    "Content-Type" : [ "application/vnd.ksql.v1+json" ]
  },
  "rawBody" : "java.lang.String cannot be cast to org.apache.avro.generic.GenericRecord\n"
}
```

## Via REST api call - `KafkaAvro` SerDe
- First of all it throws an error with `200` http response code. Better to throw as 400 or 500 (+)
- Second, the error message is not in JSON format. The error message could be wrapped to a JSON format to make application processing easy

```java
url:http://localhost:8088/query
method:POST
request:
{
  "headers" : {
    "Content-Type" : "application/vnd.ksql.v1+json; charset=utf-8",
    "Accept" : "application/vnd.ksql.v1+json"
  },
  "body" : {
    "ksql" : "print 'demo-ksql' from beginning;",
    "streamsProperties" : { }
  }
} 

Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Thu, 17 Jan 2019 22:01:15 GMT" ],
    "Server" : [ "Jetty(9.4.12.v20180830)" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Vary" : [ "Accept-Encoding, User-Agent" ],
    "Content-Type" : [ "application/vnd.ksql.v1+json" ]
  },
  "rawBody" : "java.lang.String cannot be cast to org.apache.avro.generic.GenericRecord\n"
}
```
## Via KSQL-cli
```
ksql> print 'demo-ksql' from beginning;
java.lang.String cannot be cast to org.apache.avro.generic.GenericRecord
ksql> 
```

## Console consumer output
```
$ docker exec compose_kafka_1  kafka-console-consumer --bootstrap-server localhost:29092 --topic demo-ksql  --from-beginning
8Hello, Created for KSQL demo
8Hello, Created for KSQL demo
Hello World
```

## KSQL-Server log
```java
[2019-01-23 07:41:42,331] INFO 192.168.32.1 - - [23/Jan/2019:07:41:41 +0000] "POST /query HTTP/1.1" 200 84  568 (io.confluent.rest-utils.requests:60)
[2019-01-23 07:45:43,328] INFO Building AST for print 'demo-ksql' from beginning;. (io.confluent.ksql.KsqlEngine:323)
[2019-01-23 07:45:43,352] INFO Printing topic 'demo-ksql' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:132)
[2019-01-23 07:45:43,372] ERROR Exception encountered while writing to output stream (io.confluent.ksql.rest.server.resources.streaming.TopicStreamWriter:112)
java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.avro.generic.GenericRecord
	at io.confluent.ksql.rest.server.resources.streaming.TopicStream$Format$2$1.print(TopicStream.java:132)
	at io.confluent.ksql.rest.server.resources.streaming.TopicStream$RecordFormatter.lambda$format$1(TopicStream.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)

```

## Docker File and Tests - To reproduce(in case you want to run locally)
+ Docker file is [here](https://github.com/authorjapps/zerocode/blob/master/docker/compose/kafka-schema-registry.yml)
+ JUnit Test is [here - String](https://github.com/authorjapps/zerocode/blob/kafka_p3_multi/kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/more/ksql/KafkaKsqlTest.java)

+ JUnit Test is [here - Avro](https://github.com/authorjapps/zerocode/blob/kafka_p3_multi/kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/more/ksql/KafkaKsqlAvroTest.java)

Just run as JUnit (right click and run the these tests), after you bring up the docker.
```java
    //@Ignore ("Issue still exists")
    @Test
    @JsonTestCase("kafka/consume/ksql/WIP_ISSUE_test_ksql_print_records.json")
    public void testKafkaConsume_printTopicRaw() throws Exception {
    }

    //@Ignore ("Issue still exists")
    @Test
    @JsonTestCase("kafka/consume/ksql/WIP_ISSUE_test_ksql_print_records_json.json")
    public void testKafkaConsume_printTopicJson() throws Exception {
    }
```

Then observe the KSQL server log and IDE console log.

### :::Note:::
I will try producing JSON records and stick the logs here when I get chance.
Also try with `kafkacat` as advised by @rmoff .

**Comment by rmoff** [comment]
Can you explain clearly how these records are being produced onto the topic? I can't see this from your ticket so far. thanks.

**Comment by apurvam** [comment]
Thanks for the detailed message @authorjapps . This is strange indeed, especially the part about removing the comma causing the right serde to be chosen by print. Which version of KSQL are you using? 

Here is the code that selects the format for 'print' on master: https://github.com/confluentinc/ksql/blob/master/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java

The presence of a comma in the string should not matter: the formatter will try to deserialize the value of the message as an avro record, and only choose the avro formatter if the deserialization succeeded. 

Are you sure that the topic didn't have a mix of string and avro records?

**Comment by authorjapps** [comment]
Thanks @apurvam . Thanks for sharing the source code 👍. Looks interesting. That opens of couple of more scenarios for us to handle in our framework.

> Are you sure that the topic didn't have a mix of string and avro records?

Ans - I have tested both cases
+  1)mix of string and avro records   <---- Definitely doesn't work. Cast error already explained
+  2)only string records <----- works fine now 👍 
+  3)only avro records  <---- Will confirm soon (_vaguely remember seen issues_)
+  4)Will try fresh validation with comma in the string  <--- Will comeback here

**Comment by authorjapps** [comment]
When you get a chance, could you please throw some light on the below(reported in the above ticket)
> Over the REST call for the same command, see the screen shot below. The REST client goes on Lading... and doesn't return anything.

- It looks like this is not designed to be called via REST client
- It seems like it opens a connection and waits indefinitely

**Comment by authorjapps** [comment]
@apurvam 
> Which version of KSQL are you using?

cp-ksql-server:5.1.0

Do you advise using any higher version than this?
