### ISSUE TITLE
Error: setting ksql-server.properties Failed to initialize TopicClient

### ISSUE THREAD

**Issue by ericqqqqq** [confluentinc/ksql#2462]
I am using version 5.1.1 ksql. Also, I am running ksql locally. 
Machine: Mac OS 10.14.2

When I run default ksql-server.properties which is stored inside `etc/ksql/ksql-server.propertoes` with command: 

`<path-to-confluent>/bin/ksql-server-start <path-to-confluent>/etc/ksql/ksql-server.properties`

 It returns An Error: 

```[2019-02-20 15:32:49,878] ERROR Failed to initialize TopicClient: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. (io.confluent.ksql.util.KafkaTopicClient:259)
[2019-02-20 15:32:49,879] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:45)
io.confluent.ksql.util.KsqlException: Could not fetch broker information. KSQL cannot initialize
	at io.confluent.ksql.util.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:260)
	at io.confluent.ksql.util.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:57)
	at io.confluent.ksql.KsqlEngine.create(KsqlEngine.java:115)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:287)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:80)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:42)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
	at io.confluent.ksql.util.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:237)
	... 5 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

**Comment by cuonglun12** [comment]
Hello, Could u share me how to fix this issue ?
