### ISSUE TITLE
java.lang.NullPointerException using SUM

### ISSUE THREAD

**Issue by fuyar** [confluentinc/ksql#2490]
Hello,

I have 2 topics materialized as TABLES inside KSQL (table1 and table2).
I'm using latest stable KSQL version (5.1.2).

I'm just trying to do something like this 
select t1.id, sum(t2.total) from table1 t1 left join table2 t2 on (t1.id = t2.id) where t1.id = xxxx group by t1.id;

Table2 got less rows obviously. There are t2.total null values due to no matching rows.
t2.total is set as an INT.

My queries stop after a while with this stacktrace : 

```ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:111)
java.lang.NullPointerException
        at io.confluent.ksql.function.udaf.sum.IntegerSumKudaf.undo(IntegerSumKudaf.java:46)
        at io.confluent.ksql.function.udaf.sum.IntegerSumKudaf.undo(IntegerSumKudaf.java:25)
        at io.confluent.ksql.function.udaf.KudafUndoAggregator.lambda$apply$1(KudafUndoAggregator.java:50)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
        at io.confluent.ksql.function.udaf.KudafUndoAggregator.apply(KudafUndoAggregator.java:46)
        at io.confluent.ksql.function.udaf.KudafUndoAggregator.apply(KudafUndoAggregator.java:25)
        at org.apache.kafka.streams.kstream.internals.KTableAggregate$KTableAggregateProcessor.process(KTableAggregate.java:88)
        at org.apache.kafka.streams.kstream.internals.KTableAggregate$KTableAggregateProcessor.process(KTableAggregate.java:56)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:351)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:104)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:413)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:862)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
```

There is no check in undo function on null values (unlike aggregate).

**Comment by big-andy-coates** [comment]
This looks to be a bug in the current version of KSQL.

**Comment by big-andy-coates** [comment]
Please note, unfortunately this has missed the cut of for 5.2 release. It'll be in the following release.
