### ISSUE TITLE
Processing log : KSQL doesn't warn if processing log written to topic with lower RF

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2565]
KSQL will warn if the command topic is not replicated

    WARN Creating topic _confluent-ksql-default__command_topic with replication factor of 1 which is less than 2. This is not advisable in a production environment.  (io.confluent.ksql.rest.util.KsqlInternalTopicUtils:75)

It should do the same for `ksql.logging.processing.topic`.

**Comment by esquare666** [comment]
May I know if any solution for this ? Still getting an error
[2023-07-22 19:59:50,414] WARN Creating topic _confluent-ksql-default_command_topic with replication factor of 1 which is less than 2. This is not advisable in a production environment.  (io.confluent.ksql.rest.util.KsqlInternalTopicUtils:74)
[2023-07-22 19:59:50,456] INFO Creating topic '_confluent-ksql-default_command_topic'  (io.confluent.ksql.services.KafkaTopicClient:116)
[2023-07-22 19:59:50,784] ERROR Unhandled exception in server startup (io.confluent.ksql.rest.server.KsqlServerMain:156)
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to guarantee existence of topic _confluent-ksql-default_command_topic
	at io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:143)
	at io.confluent.ksql.services.KafkaTopicClient.createTopic(KafkaTopicClient.java:103)
	at io.confluent.ksql.rest.util.KsqlInternalTopicUtils.ensureTopic(KsqlInternalTopicUtils.java:82)
	at io.confluent.ksql.rest.server.KsqlRestApplication.registerCommandTopic(KsqlRestApplication.java:1114)
	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:426)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:397)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:380)
	at io.confluent.ksql.rest.server.KsqlServerMain.runExecutable(KsqlServerMain.java:152)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:115)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:94)
Caused by: org.apache.kafka.common.errors.PolicyViolationException: Topic replication factor must be 3

**Comment by andsty** [comment]
how can i increate the replication factor for command topic?
