### ISSUE TITLE
Fatal user code error in TimestampExtractor

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2609]
KSQL 5.2

Set up test data

```
kafkacat -P -b localhost -t time_test <<EOF
{"order_id":101,"customer_id":513,"order_ts":"2019-03-24T07:38:05Z","order_total_usd":"56615.44","make":"Ford"}
EOF
```

Declare stream, with the timestamp set based on a column in the payload

```
SET 'auto.offset.reset' = 'earliest';

CREATE STREAM TIME_TEST (ORDER_ID INT, ORDER_TS VARCHAR) WITH (TIMESTAMP='ORDER_TS', TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX', KAFKA_TOPIC='time_test', VALUE_FORMAT='JSON');
```

Query stream

```
ksql> SELECT * FROM TIME_TEST;
1553413085000 | null | 101 | 2019-03-24T07:38:05Z
```

Insert bad record into topic, in which the timestamp column doesn't exist: 

```
kafkacat -P -b localhost -t time_test <<EOF
{"shipment_id":"ship-uu20951","order_id":102,"shipment_provider":"ups","shipment_ts":"2019-03-26T06:45:10Z"}
EOF
```

🛑 `SELECT` breaks: 

```
ksql> SELECT * FROM TIME_TEST;
1553413085000 | null | 101 | 2019-03-24T07:38:05Z
Fatal user code error in TimestampExtractor callback for record ConsumerRecord(topic = time_test, partition = 0, leaderEpoch = null, offset = 1, CreateTime = 1553601617291, serialized key size = -1, serialized value size = 108, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ 102 | null ]).
Caused by: text
Query terminated
```

🛑  CSAS fails too

```
ksql-server_1             | [2019-03-26 12:04:27,300] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] State transition from RUNNING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:214)
ksql-server_1             | [2019-03-26 12:04:27,300] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1205)
ksql-server_1             | [2019-03-26 12:04:27,340] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:214)
ksql-server_1             | [2019-03-26 12:04:27,341] INFO stream-client [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c] State transition from RUNNING to ERROR (org.apache.kafka.streams.KafkaStreams:263)
ksql-server_1             | [2019-03-26 12:04:27,341] ERROR stream-client [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c] All stream threads have died. The instance will be in error state and should be closed. (org.apache.kafka.streams.KafkaStreams:423)
ksql-server_1             | Exception in thread "_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537" org.apache.kafka.streams.errors.StreamsException: Fatal user code error in TimestampExtractor callback for record ConsumerRecord(topic = time_test, partition = 0, leaderEpoch = null, offset = 1, CreateTime = 1553601617291, serialized key size = -1, serialized value size = 108, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ 102 | null ]).
ksql-server_1             | [2019-03-26 12:04:27,343] INFO stream-thread [_confluent-ksql-asgardquery_CSAS_FOO_TIME_35-728a0abe-7d39-4602-8af0-18dd4c4aa00c-StreamThread-537] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1225)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.maybeUpdateTimestamp(RecordQueue.java:174)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.poll(RecordQueue.java:115)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.PartitionGroup.nextRecord(PartitionGroup.java:100)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:349)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:420)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:889)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:804)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:773)
ksql-server_1             | Caused by: java.lang.NullPointerException: text
ksql-server_1             |     at java.util.Objects.requireNonNull(Objects.java:228)
ksql-server_1             |     at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1891)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:46)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:42)
ksql-server_1             |     at io.confluent.ksql.util.timestamp.StringTimestampExtractor.extract(StringTimestampExtractor.java:45)
ksql-server_1             |     at org.apache.kafka.streams.processor.internals.RecordQueue.maybeUpdateTimestamp(RecordQueue.java:169)
ksql-server_1             |     ... 8 more
```

PRINT works: 

```
ksql> PRINT 'time_test' FROM BEGINNING;
Format:JSONC to interrupt
{"ROWTIME":1553601533808,"ROWKEY":"null","order_id":101,"customer_id":513,"order_ts":"2019-03-24T07:38:05Z","order_total_usd":"56615.44","make":"Ford"}
{"ROWTIME":1553601617291,"ROWKEY":"null","shipment_id":"ship-uu20951","order_id":102,"shipment_provider":"ups","shipment_ts":"2019-03-26T06:45:10Z"}
```

Works fine if `TIMESTAMP` not set: 

```
ksql> CREATE STREAM TIME_TEST2 (ORDER_ID INT, ORDER_TS VARCHAR) WITH (KAFKA_TOPIC='time_test', VALUE_FORMAT='JSON')

 Message
----------------
 Stream created
----------------
ksql> SELECT * FROM TIME_TEST2;
1553601533808 | null | 101 | 2019-03-24T07:38:05Z
1553601617291 | null | 102 | null
```

Workaround presumably is to define the first stream without `TIMESTAMP`, create a derived one in which records without the timestamp field are filtered out and set the timestamp in the created one. 

But, this should be fixed properly, and just as undeserialisable messages are dropped but processing continues, the same here. At the moment it's a very sharp edge.

**Comment by agavra** [comment]
We should probably log-and-continue as we do with most errors. We should make sure that this shows up in the processing log so that users can debug what's going on.

**Comment by agavra** [comment]
There is also a streams config to Log and skip on invalid timestamp: https://kafka.apache.org/10/javadoc/org/apache/kafka/streams/processor/LogAndSkipOnInvalidTimestamp.html
