### ISSUE TITLE
ksql-test-runner Error: Could not find

### ISSUE THREAD

**Issue by Sikta** [confluentinc/ksql#3312]
Is there a guide on how to install this?

I downloaded the confluent-5.3.0-2.12.zip file and extracted it. When I try to run the ksql-test-runner from the bin folder I get the following error.

```Error: Could not find or load main class io.confluent.ksql.test.tools.KsqlTestingTool```

In the ksql-test-runner docs, it assumes you already have everything installed.

**Comment by Sikta** [comment]
Apparently there was a packaging error and this file wasn’t included in the zip. It supposed to be fixed in the 5.3.1 RC. I’ll verify and close tomorrow.

**Comment by Sikta** [comment]
In 5.3.1 I'm now getting a new error:

```
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)```

**Comment by big-andy-coates** [comment]
Thanks for reporting!  Closing as a duplicate of https://github.com/confluentinc/ksql/issues/3387
