### ISSUE TITLE
pull queries open a kafka admin client per request

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/ksql#3663]
**Describe the bug**
spent a bunch of time profiling the ksql server further to understand (I still don’t know how to control min/max threads in jetty), but nonetheless I saw that admin client threads are being generated per request. (can repro this even with show tables, so its more to do with the /ksql endpoint than anything related to pull queries)

**To Reproduce**
Steps to reproduce the behavior, include:
1. master branch
2. N/A
3. Just do a curl of `SHOW TABLES` in a loop

**Expected behavior**
Kafka admin client should not be opened per request? 

**Actual behaviour**

![ksql-with-pull-queries](https://user-images.githubusercontent.com/1179324/67505800-c716a280-f640-11e9-880c-e67e3f7a38a6.gif)

```
2019-10-23 17:20:36,607] INFO Received: KsqlRequest{ksql='SHOW TABLES;', streamsProperties={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:198)
java.lang.RuntimeException: Whos creating this?qtp843710487-42
    at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:508)
    at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:456)
    at org.apache.kafka.clients.admin.Admin.create(Admin.java:71)
    at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getAdmin(DefaultKafkaClientSupplier.java:41)
    at io.confluent.ksql.services.ServiceContextFactory.create(ServiceContextFactory.java:53)
    at io.confluent.ksql.rest.server.services.RestServiceContextFactory.create(RestServiceContextFactory.java:71)
    at io.confluent.ksql.rest.server.services.RestServiceContextFactory.create(RestServiceContextFactory.java:57)
    at io.confluent.ksql.rest.server.context.KsqlRestServiceContextFactory.provide(KsqlRestServiceContextFactory.java:91)
    at io.confluent.ksql.rest.server.context.KsqlRestServiceContextFactory.provide(KsqlRestServiceContextFactory.java:39)
    at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129)
```

**Additional context**

**Comment by big-andy-coates** [comment]
The creation of admin clients per-request is not a bug. It's a feature required by KSQL when the auth mechanism requires KSQL to pass through auth headers to Kafka.  This requires a new Admin Client per request at the moment.

We should not look to 'fix' this by only creating a new admin client per request if auth is not enabled.  Such a fix would not help anyone running in a secure environment.

There is potential to make upstream changes so that the auth details can be passed with each request.

There is potential to make changes to KSQL to make admin client instantiation lazy and minimising which statements require the client.  Specifically, it may be possible to avoid the overhead totally for Pull queries.

There is also potential to cache admin clients per-user. But this is nasty, adds complexity to the code and only works for small numbers of users and where auth details are static.  This should be a last option only.

**Comment by vinothchandar** [comment]
>Specifically, it may be possible to avoid the overhead totally for Pull queries.
This is what I was thinking as well. +1
