### ISSUE TITLE
KSQL connection issues with kafka

### ISSUE THREAD

**Issue by gangadhar01a** [confluentinc/ksql#3828]
**Provide details of the setup you're running**
Let us know what version of KSQL you're running, what OS, etc, 
KSQL version: confluent-ksql-5.3.1-1.
**Outline your question**
Ask you question!
KSQL not able to connect to the kafka, resulting in timeout expception.

**Following is the ksql configuration file:**

bootstrap.servers=hostname1:9093
listeners=http://0.0.0.0:8088
ksql.logging.processing.topic.auto.create=true
ksql.logging.processing.stream.auto.create=true
#ksql.schema.registry.url=?
ksql.security.protocol=ssl
ksql.ssl.keystore.location=/root/.kafka/kafka.server.keystore.jks
ksql.ssl.keystore.password=password
ksql.ssl.key.password=password
ksql.ssl.client.auth=true
ksql.streams.state.dir=/etc/ksql/
ksql.ssl.truststore.location=/root/.kafka/kafka.server.truststore.jks
ksql.ssl.truststore.password=password

**ERROR:**
[2019-11-12 14:17:27,790] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:62)
io.confluent.ksql.util.KsqlServerException: Could not get Kafka cluster configuration!
	at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:77)
	at io.confluent.ksql.engine.TopicAccessValidatorFactory.isKafkaAuthorizerEnabled(TopicAccessValidatorFactory.java:66)
	at io.confluent.ksql.engine.TopicAccessValidatorFactory.create(TopicAccessValidatorFactory.java:50)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:505)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:444)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:94)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:59)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:55)
	... 6 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

**Comment by abdul-maroof-confiz** [comment]
Did you find the solution @gangadhar01a ? I am facing the same issue.

**Comment by luumarodrigues** [comment]
@abdul-maroof-confiz I am facing the same issue too :(

**Comment by abdul-maroof-confiz** [comment]
> @abdul-maroof-confiz I am facing the same issue too :(

@luumarodrigues My issue got fixed. Please connect on [linkedin](https://www.linkedin.com/in/abdulmaroof/) pm. Maybe I can help you resolve this issue.
