### ISSUE TITLE
ksqldb 0.6 - SELECT not working

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#3998]
Running through https://ksqldb.io/quickstart.html worked fine the first time. 
Now I'm going through it again *and my docker is possibly in a weird state*, but what I'm seeing is this: 

Stream `RIDERLOCATIONS` is JSON: 

```
ksql> SHOW STREAMS;

 Stream Name         | Kafka Topic                 | Format
------------------------------------------------------------
 KSQL_PROCESSING_LOG | default_ksql_processing_log | JSON
 RIDERLOCATIONS      | locations                   | JSON
------------------------------------------------------------
```

Topic has data: 

```
ksql> PRINT locations FROM BEGINNING;
Format:JSON
{"ROWTIME":1575021503630,"ROWKEY":"c2309eec","PROFILEID":"c2309eec","LATITUDE":37.7877,"LONGITUDE":-122.4205}
{"ROWTIME":1575021503755,"ROWKEY":"18f4ea86","PROFILEID":"18f4ea86","LATITUDE":37.3903,"LONGITUDE":-122.0643}
{"ROWTIME":1575021503864,"ROWKEY":"4ab5cbad","PROFILEID":"4ab5cbad","LATITUDE":37.3952,"LONGITUDE":-122.0813}
{"ROWTIME":1575021503970,"ROWKEY":"8b6eae59","PROFILEID":"8b6eae59","LATITUDE":37.3944,"LONGITUDE":-122.0813}
{"ROWTIME":1575021504078,"ROWKEY":"4a7c7b41","PROFILEID":"4a7c7b41","LATITUDE":37.4049,"LONGITUDE":-122.0822}
{"ROWTIME":1575021504716,"ROWKEY":"4ddad000","PROFILEID":"4ddad000","LATITUDE":37.7857,"LONGITUDE":-122.4011}
{"ROWTIME":1575021604263,"ROWKEY":"c2309eec","PROFILEID":"c2309eec","LATITUDE":37.7877,"LONGITUDE":-122.4205}
{"ROWTIME":1575021604460,"ROWKEY":"18f4ea86","PROFILEID":"18f4ea86","LATITUDE":37.3903,"LONGITUDE":-122.0643}
{"ROWTIME":1575021604614,"ROWKEY":"4ab5cbad","PROFILEID":"4ab5cbad","LATITUDE":37.3952,"LONGITUDE":-122.0813}
{"ROWTIME":1575021604728,"ROWKEY":"8b6eae59","PROFILEID":"8b6eae59","LATITUDE":37.3944,"LONGITUDE":-122.0813}
{"ROWTIME":1575021604865,"ROWKEY":"4a7c7b41","PROFILEID":"4a7c7b41","LATITUDE":37.4049,"LONGITUDE":-122.0822}
{"ROWTIME":1575021606997,"ROWKEY":"4ddad000","PROFILEID":"4ddad000","LATITUDE":37.7857,"LONGITUDE":-122.4011}
```

`SELECT` returns no data: 

```
ksql> SET 'auto.offset.reset' = 'earliest';
Successfully changed local property 'auto.offset.reset' from 'earliest' to 'earliest'.
ksql> SELECT * FROM riderLocations EMIT CHANGES;

Press CTRL-C to interrupt
```

ksqldb server log: 

```
ksqldb-server       | [2019-11-29 10:12:18,347] INFO Streaming query 'SELECT * FROM riderLocations EMIT CHANGES;' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:288)
ksqldb-server       | [2019-11-29 10:12:18,348] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] Starting (org.apache.kafka.streams.processor.internals.StreamThread:664)
ksqldb-server       | [2019-11-29 10:12:18,346] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] Starting (org.apache.kafka.streams.processor.internals.StreamThread:664)
ksqldb-server       | [2019-11-29 10:12:18,361] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] State transition from CREATED to STARTING (org.apache.kafka.streams.processor.internals.StreamThread:219)
ksqldb-server       | [2019-11-29 10:12:18,361] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] State transition from CREATED to STARTING (org.apache.kafka.streams.processor.internals.StreamThread:219)
```

If I then Ctrl-C to cancel the query the CLI shows

```
ksql> SELECT * FROM riderLocations EMIT CHANGES;
^C+-----------------------------------+-----------------------------------+-----------------------------------+-----------------------------------+-----------------------------------+
|ROWTIME                            |ROWKEY                             |PROFILEID                          |LATITUDE                           |LONGITUDE                          |
+-----------------------------------+-----------------------------------+-----------------------------------+-----------------------------------+-----------------------------------+
Query terminated
ksql>
```

And the server log shows

```
 [2019-11-29 10:14:36,363] WARN Query terminated due to exception:org.eclipse.jetty.io.EofException (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:95)
 [2019-11-29 10:14:36,363] INFO stream-client [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59] State transition from REBALANCING to PENDING_SHUTDOWN (org.apache.kafka.streams.KafkaStreams:276)
 [2019-11-29 10:14:36,373] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-1] Informed to shut down (org.apache.kafka.streams.processor.internals.StreamThread:1098)
 [2019-11-29 10:14:36,373] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-1] State transition from STARTING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,373] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] Informed to shut down (org.apache.kafka.streams.processor.internals.StreamThread:1098)
 [2019-11-29 10:14:36,373] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] State transition from STARTING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,374] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-3] Informed to shut down (org.apache.kafka.streams.processor.internals.StreamThread:1098)
 [2019-11-29 10:14:36,375] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-3] State transition from STARTING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,375] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] Informed to shut down (org.apache.kafka.streams.processor.internals.StreamThread:1098)
 [2019-11-29 10:14:36,375] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] State transition from STARTING to PENDING_SHUTDOWN (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,422] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1112)
 [2019-11-29 10:14:36,422] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1112)
 [2019-11-29 10:14:36,437] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-1] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1112)
 [2019-11-29 10:14:36,438] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-3] Shutting down (org.apache.kafka.streams.processor.internals.StreamThread:1112)
 [2019-11-29 10:14:36,465] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-3] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,465] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-3] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1132)
 [2019-11-29 10:14:36,468] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,468] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-4] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1132)
 [2019-11-29 10:14:36,484] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,484] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-2] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1132)
 [2019-11-29 10:14:36,487] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD (org.apache.kafka.streams.processor.internals.StreamThread:219)
 [2019-11-29 10:14:36,487] INFO stream-thread [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59-StreamThread-1] Shutdown complete (org.apache.kafka.streams.processor.internals.StreamThread:1132)
 [2019-11-29 10:14:36,493] INFO stream-client [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59] State transition from PENDING_SHUTDOWN to NOT_RUNNING (org.apache.kafka.streams.KafkaStreams:276)
 [2019-11-29 10:14:36,493] INFO stream-client [_confluent-ksql-default_transient_2323136009432137425_1575022338232-ffe24aa2-714d-4541-b548-6c05a831ff59] Streams client stopped completely (org.apache.kafka.streams.KafkaStreams:961)
 [2019-11-29 10:14:36,496] WARN Could not clean up the schema registry for query: _confluent-ksql-default_transient_2323136009432137425_1575022338232 (io.confluent.ksql.schema.registry.SchemaRegistryUtil:59)
 java.net.ConnectException: Connection refused (Connection refused)
   at java.net.PlainSocketImpl.socketConnect(Native Method)
   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
   at java.net.Socket.connect(Socket.java:589)
   at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
   at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
   at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
   at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
   at sun.net.www.http.HttpClient.New(HttpClient.java:339)
   at sun.net.www.http.HttpClient.New(HttpClient.java:357)
   at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
   at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1046)
   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1044)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1043)
   at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
   at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
   at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:250)
   at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:322)
   at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:635)
   at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:630)
   at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getAllSubjects(CachedSchemaRegistryClient.java:388)
   at io.confluent.ksql.schema.registry.SchemaRegistryUtil.getSubjectNames(SchemaRegistryUtil.java:57)
   at io.confluent.ksql.schema.registry.SchemaRegistryUtil.getInternalSubjectNames(SchemaRegistryUtil.java:74)
   at io.confluent.ksql.schema.registry.SchemaRegistryUtil.cleanUpInternalTopicAvroSchemas(SchemaRegistryUtil.java:44)
   at io.confluent.ksql.engine.KsqlEngine.unregisterQuery(KsqlEngine.java:214)
   at io.confluent.ksql.engine.EngineContext.unregisterQuery(EngineContext.java:223)
   at io.confluent.ksql.util.QueryMetadata.close(QueryMetadata.java:150)
   at io.confluent.ksql.util.TransientQueryMetadata.close(TransientQueryMetadata.java:102)
   at io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter.write(QueryStreamWriter.java:104)
   at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55)
   at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
   at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
   at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
   at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
   at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1111)
   at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
   at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
   at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
   at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
   at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385)
   at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560)
   at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501)
   at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
   at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
   at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
   at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
   at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
   at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
   at org.eclipse.jetty.server.Server.handle(Server.java:494)
   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
   at java.lang.Thread.run(Thread.java:748)
 [2019-11-29 10:14:36,505] INFO 192.168.128.8 - - [29/Nov/2019:10:12:18 +0000] "POST /query HTTP/1.1" 200 273  138313 (io.confluent.rest-utils.requests:62)
```

If I run the `SELECT` again and in another session `INSERT` some more data I still don't see it in the `SELECT` output (but I do in `PRINT`)

Two issues: 

1. Why don't I get data, even though there is data in the topic and offset is earliest? 
2. Why is ksqldb trying to connect to the SR even though it's working with JSON data? This big long stacktrace in the log is a distraction when troubleshooting.

**Comment by big-andy-coates** [comment]
anything in the processing log?

**Comment by rmoff** [comment]
I didn't check the processing log, only what's quoted above from the server log

**Comment by big-andy-coates** [comment]
Can you recreate an check the proccessing log?

**Comment by ravika-mdosl** [comment]
i got the same issue;

**Comment by apurvam** [comment]
Is this still an issue? Should it be closed?

**Comment by rmoff** [comment]
¯\_(ツ)_/¯ closing.

**Comment by lloiacono** [comment]
Why has this issue being closed? I'm having the same problem, do not know how to troubleshoot.

**Comment by rmoff** [comment]
@lloiacono The issue is over a year old, and related to a much older version. I suggest you raise a new ticket with full details of your issue, version number, deployment details etc. You can always link to this one as reference if you think they're related.
