### ISSUE TITLE
ksqlDB should set key.converter to string for sink connectors if not specified by user

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#4036]
ksqlDB currently writes keys as strings, and as such any connector will fail if the worker is not set to use String for key converter. 

e.g.

```
ksql> DESCRIBE CONNECTOR SINK_POSTGRES_01;

Name                 : SINK_POSTGRES_01
Class                : io.confluent.connect.jdbc.JdbcSinkConnector
Type                 : sink
State                : RUNNING
WorkerId             : kafka-connect-01:8083

 Task ID | State  | Error Trace
---------------------------------------------------------------------------------------------------------------------------------------------------
 0       | FAILED | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic USERMENTIONS_COUNT to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:110)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
        ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

---------------------------------------------------------------------------------------------------------------------------------------------------
```

This is a bad experience for the user because (a) it doesn't work and (b) it's hard to troubleshoot because the Kafka Connect error doesn't say it's the Key that's causing the deserialisation problem.

My suggestion: when the user issues `CREATE SINK CONNECTOR` ksqlDB should automagically set `'key.converter'       = 'org.apache.kafka.connect.storage.StringConverter' ` if it's not present in the user's DML.  As and when ksqlDB supports richer strings we can change this, but for now it will smooth the path _a lot_ for users if we can do this. There is precedent for similar config overrides in `CREATE SOURCE CONNECTOR` setting up Single Message Transforms.

**Comment by rmoff** [comment]
@agavra WDYT> ?

**Comment by agavra** [comment]
@rmoff I think this makes sense. For the `JdbcSourceConnector` we already do this (see https://github.com/confluentinc/ksql/blob/master/ksql-engine/src/main/java/io/confluent/ksql/connect/supported/JdbcSource.java#L72)

The only reason I didn't have this be a default everywhere is that I was worried it might be better to fail than to coerce incompatible data - for example, the JDBC connector will also fail with the StringConverter if you database key is not a String 😢 (at least I'm pretty sure it fails). I think the behavior around this is a little sticky... I'm hoping that the primitive key work will come in soon and help make this problem go away, but maybe in the short term it makes more sense to just set the default to StringConverter anyway.

**Comment by rmoff** [comment]
great, thanks @agavra !
