### ISSUE TITLE
MSSQL Connector No Driver Found. Error_Code: 400

### ISSUE THREAD

**Issue by Sarlken** [confluentinc/ksql#4167]
Hello all;

I'm trying to transfer my data from mssql to apache kafka. To do that I created one docker-compose file to deploy the ksqldb to my virtual machine.

I also configured connect.properties file and I have downloaded the plugins required as below:

- kafka-connect-jdbc-5.3.1.jar
- mssql-jdbc-7.4.1.jre8.jar

and mounted this drives to my container in docker compose file and I can see the files in the containers.

I have also added the required path as below to connect.properties file as below:
plugin.path=/usr/share/java/kafka-connect-jdbc/kafka-connect-jdbc-5.3.1.jar

But still getting the error below 

{
  "error_code" : 400,
  "message" : "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:sqlserver://example.com:56482;databaseName=ex;user=ex;password=ex for configuration Couldn't open connection to jdbc:sqlserver://example.com:56482;databaseName=ex;user=ex;password=ex\nInvalid value java.sql.SQLException: No suitable driver found for jdbc:sqlserver://example.com:56482;databaseName=ex;user=ex;password=ex for configuration Couldn't open connection to jdbc:sqlserver://example.com:56482;databaseName=ex;user=ex;password=ex\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
}

I would be glad for any help!

**Comment by prashanthjbabu** [comment]
I'm facing a similar issue with postgresl
```
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: No suitable driver found for jdbc:postgresql://postgres:54
32/
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:59)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:64)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:562)
	... 10 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:postgresql://postgres:5432/
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:239)
	at io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect.getConnection(PostgreSqlDatabaseDialect.java:103)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	... 13 more

```
I have both postgresql and jdbc connector jars in the plugin path . I followed this blog https://www.confluent.io/blog/kafka-connect-deep-dive-jdbc-source-connector/ and noticed tht the registration of the sql driver does not happen immediately after the jdbc plugin is loaded but happens separately
