### ISSUE TITLE
Trying to select from K-SQL stream created o kafka topic produces end-of-input error

### ISSUE THREAD

**Issue by visakhmurukes** [confluentinc/ksql#4316]
**Describe the bug**
Trying to select from a stream created over kafka topic fails with an error midway after displaying some initial rows
**To Reproduce**

- Create a kafka topic based on MySQL table.
- Create a K-SQL stream on top of Kafka topic
-  Trying to select from a stream using K-SQL query

**Expected behavior**

stream gets created

**Actual behaviour**

**_com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"row":{"columns":[1579000050672,"\u0000\u0000\u0000\u00004"; line: 1, column: 34] (through reference chain: io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["columns"]->java.util.ArrayList[1])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
        value
 at [Source:
        (String)"{"row":{"columns":[1579000050672,"\u0000\u0000\u0000\u00004"; line: 1,
        column: 34] (through reference chain:
        io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["
        columns"]->java.util.ArrayList[1])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
        value
 at [Source:
        (String)"{"row":{"columns":[1579000050672,"\u0000\u0000\u0000\u00004"; line: 1,
        column: 119]_**

The offending row looks like this

'90465', 'TEST 1', '8', '990_60040_1577196000', '1577196000', '2019-12-24', '0', '2019-12-22 08:20:28.232483', '2019-12-24 19:21:02.207983', '124', '1', '1', '2019-12-24', '06:00 PM'

table definition is below

CREATE TABLE `test  `
(
 `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `number` varchar(100) NOT NULL,
  `s_id` varchar(200) NOT NULL,
  `st` int(10) unsigned NOT NULL,
  `b_date_start` date NOT NULL,
  `status` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `modified_at` datetime(6) NOT NULL,
  `exp_id` int(11) NOT NULL,
  `modified_by_id` int(11) NOT NULL,
  `b_enabled` tinyint(1) NOT NULL,
  `s_date` date NOT NULL,
  `s_time` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

![ksqlerr](https://user-images.githubusercontent.com/14180077/72414884-b2076680-378c-11ea-87de-3f0ccce8bbcc.png)

**Comment by visakhmurukes** [comment]
Any help on this please?
The error still persists and cant understand the root cause

**Comment by yugensaccnt** [comment]
@visakhmurukes - I went on ahead by creating additional streams on the top of the stream that was originally causing this problem and did not encounter the error on the subsequents streams/tables. Let me know your experience

**Comment by Crispy1975** [comment]
I have had the exact same thing happen today, the main difference is that we are using MongoDB to stream into Kafka via Kafka Connect. Our stream is built on top of two other streams doing various transforms, and for the most part has not had an issue until today.

```
Query terminated
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"row":{"columns":[1582302557410,"0d364ad1-b771-49ea-b7d2-37ee088bc2c9","0d364ad1-b771-49ea-b7d2-37ee088bc2c9","60388b1049567835e143","added","item","e860b374-dab0-42ef-891d-f39a8f8932ea"; line: 1, column: 153] (through reference chain: io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["columns"]->java.util.ArrayList[6])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
	value
 at [Source:
	(String)"{"row":{"columns":[1582302557410,"0d364ad1-b771-49ea-b7d2-37ee088bc2c9"
	,"0d364ad1-b771-49ea-b7d2-37ee088bc2c9","60388b1049567835e143","added","item"
	,"e860b374-dab0-42ef-891d-f39a8f8932ea"; line: 1, column: 153] (through
	reference chain:
	io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["
	columns"]->java.util.ArrayList[6])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
	value
 at [Source:
	(String)"{"row":{"columns":[1582302557410,"0d364ad1-b771-49ea-b7d2-37ee088bc2c9"
	,"0d364ad1-b771-49ea-b7d2-37ee088bc2c9","60388b1049567835e143","added","item"
	,"e860b374-dab0-42ef-891d-f39a8f8932ea"; line: 1, column: 379]
```

**Comment by AndreaTosti** [comment]
I have the same problem, it always happens to me when I try to return a large number of rows (about 200000)

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"row":{"columns":[1582909218117,"2250041",1582909218117,"User_"; line: 1, column: 58] (through reference chain: io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["columns"]->java.util.ArrayList[3])
```

**Comment by AndreaTosti** [comment]
Investigating I noticed that in the ksqldb-server logs, since I use it locally, if it is not very performing, a timeout expires, and if this timeout expires, the JSON is truncated. If the timeout does not expire, I can also return 1 million lines without problems. Now I'm looking for a way to increase this timeout via configuration.

`[2020-03-03 14:55:03,638] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:101)
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:227)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:408)
        at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.flush(ResponseWriter.java:306)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:263)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.flush(WriterInterceptorExecutor.java:281)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1141)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3911)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3177)
        at io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter.write(QueryStreamWriter.java:109)
        at io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter.write(QueryStreamWriter.java:76)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1111)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
        at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501)
        at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
`
