### ISSUE TITLE
Type inference is not supported for: class org.apache.kafka.connect.data.Struct

### ISSUE THREAD

**Issue by fedexist** [confluentinc/ksql#4688]
**Provide details of the setup you're running**
I'm testing this UDF on a local environment with docker-compose:

```yaml
version: '2'
services:
  ksql:
    image: confluentinc/cp-ksql-server:5.4.0
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SERVICE_ID: "ksql_service_2_"
      KSQL_LISTENERS: "http://0.0.0.0:8088/"
    volumes:
      - /udf-jars:/usr/ext
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: MY_LOCAL_IP
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Outline your question**

I've implemented the following UDF, which has two structs as input and should return a Struct with a dynamic return type:

```java
@UdfDescription(name = "MERGECDC")
public class MergeStructUdfConnect {

    @Udf(description = "Merge two structs", schemaProvider = "structSchema")
    public Struct mergeStruct(
            @UdfParameter(value = "before") Struct before,
            @UdfParameter(value = "after") Struct after) {

        final String IS_MISSING_SUFFIX = "_isMissing";
        Struct output;
        // do stuff using before and after structs, 
        // like filters and assign fields to output struct
        return output;
    }

    @UdfSchemaProvider
    public SqlType structSchema(final List<SqlType> params) {
        // Use SqlType from after field
        SqlType inputType = params.get(1);
        SqlStruct structType = (SqlStruct) inputType;

        SqlStruct.Builder outputTypeBuilder = SqlStruct.builder();

        structType.fields().stream()
                .filter( f -> !(f.name().endsWith("_isMissing")))
                .forEach( f -> outputTypeBuilder.field(f.name(), f.type()));

        return outputTypeBuilder.build();
    }

}
```

While running the KSQL server, I'm having this error:

```
ksql_1       | [2020-03-03 10:45:56,393] INFO Adding function MERGECDC for method public org.apache.kafka.connect.data.Struct com.generali.aateam.MergeStructUdfConnect.mergeStruct(org.apache.kafka.connect.data.Struct,org.apache.kafka.connect.data.Struct) (io.confluent.ksql.function.UdfLoader:143)
ksql_1       | [2020-03-03 10:45:56,394] WARN Failed to add UDF to the MetaStore. name=MERGECDC method=public org.apache.kafka.connect.data.Struct com.generali.aateam.MergeStructUdfConnect.mergeStruct(org.apache.kafka.connect.data.Struct,org.apache.kafka.connect.data.Struct) (io.confluent.ksql.function.UdfLoader:114)
ksql_1       | io.confluent.ksql.util.KsqlException: Type inference is not supported for: class org.apache.kafka.connect.data.Struct
ksql_1       | 	at io.confluent.ksql.execution.function.UdfUtil.handleParameterizedType(UdfUtil.java:143)
ksql_1       | 	at io.confluent.ksql.execution.function.UdfUtil.lambda$getSchemaFromType$6(UdfUtil.java:104)
ksql_1       | 	at io.confluent.ksql.execution.function.UdfUtil.getSchemaFromType(UdfUtil.java:104)
ksql_1       | 	at io.confluent.ksql.function.FunctionLoaderUtils.lambda$createParameters$1(FunctionLoaderUtils.java:92)
ksql_1       | 	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
ksql_1       | 	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
ksql_1       | 	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
ksql_1       | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
ksql_1       | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
ksql_1       | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
ksql_1       | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ksql_1       | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
ksql_1       | 	at io.confluent.ksql.function.FunctionLoaderUtils.createParameters(FunctionLoaderUtils.java:93)
ksql_1       | 	at io.confluent.ksql.function.UdfLoader.createFunction(UdfLoader.java:146)
ksql_1       | 	at io.confluent.ksql.function.UdfLoader.loadUdfFromClass(UdfLoader.java:107)
ksql_1       | 	at io.confluent.ksql.function.UserFunctionLoader.lambda$loadFunctions$4(UserFunctionLoader.java:125)
ksql_1       | 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$8.lookForMatches(ScanSpec.java:1316)
ksql_1       | 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:696)
ksql_1       | 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1606)
ksql_1       | 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1678)
ksql_1       | 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1704)
ksql_1       | 	at io.confluent.ksql.function.UserFunctionLoader.loadFunctions(UserFunctionLoader.java:135)
ksql_1       | 	at io.confluent.ksql.function.UserFunctionLoader.lambda$load$2(UserFunctionLoader.java:97)
ksql_1       | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
ksql_1       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
ksql_1       | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
ksql_1       | 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
ksql_1       | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
ksql_1       | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
ksql_1       | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
ksql_1       | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
ksql_1       | 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
ksql_1       | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
ksql_1       | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ksql_1       | 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
ksql_1       | 	at io.confluent.ksql.function.UserFunctionLoader.load(UserFunctionLoader.java:96)
ksql_1       | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:471)
ksql_1       | 	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:425)
ksql_1       | 	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:94)
ksql_1       | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:57)
```

Am I doing something wrong? Are dynamic structs really not supported?

**Comment by agavra** [comment]
Hello @fedexist - I believe you need to specify the `schema` for the input parameters as well inside the `@UdfParameter` annotation:

```java
  /**
   * The schema for this parameter.
   *
   * <p>For simple parameters, this is optional and can be determined from
   * the Java value itself. For complex return types (e.g. {@code Struct} types),
   * this is required and will fail if not supplied.
   */
  String schema() default "";
```

This is a current limitation in the framework that the input struct types must be static. I think you can work around it by defining an empty struct type (e.g. `STRUCT<>`) which will accept any struct if I remember correctly (though I'd need to double check that)

**Comment by fedexist** [comment]
> Hello @fedexist - I believe you need to specify the `schema` for the input parameters as well inside the `@UdfParameter` annotation:
> 
> ```java
>   /**
>    * The schema for this parameter.
>    *
>    * <p>For simple parameters, this is optional and can be determined from
>    * the Java value itself. For complex return types (e.g. {@code Struct} types),
>    * this is required and will fail if not supplied.
>    */
>   String schema() default "";
> ```
> 
> This is a current limitation in the framework that the input struct types must be static. I think you can work around it by defining an empty struct type (e.g. `STRUCT<>`) which will accept any struct if I remember correctly (though I'd need to double check that)

Thank you @agavra, I missed that annotation requirement. I will try and see if it works without explicity specifying the struct fields.
