### ISSUE TITLE
ProxyHandler throwing IllegalStateException

### ISSUE THREAD

**Issue by jrea** [confluentinc/ksql#4760]
**Describe the bug**
Can't query streams/tables
**To Reproduce**
run in node:
```
    import { request } from 'http';
    const ksql = 'show streams extended; show tables extended;';
    const data = JSON.stringify({ ksql });
    const options = {
      method: 'POST',
      hostname: 'localhost',
      port: '8088',
      path: '/ksql',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': data.length
      }
    }
    const req = request(options, res => {
      console.log(res.statusCode);
      res.on('data', d => {
        console.log(d);
      })
    });
    req.on('error', error => {
      console.error(error)
    })
    req.write(data);
    req.end();
```

**Expected behavior**
returns streams and tables

**Actual behaviour**
ksqldb server response with
```[2020-03-12 21:29:30,713] INFO Received: KsqlRequest{ksql='show streams extended; show tables extended;', configOverrides={}, requestProperties={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:236)
[2020-03-12 21:29:30,730] ERROR Exception in proxying (io.confluent.ksql.api.server.ProxyHandler:193)
java.lang.IllegalStateException: You must set the Content-Length header to be the total size of the message body BEFORE sending any data if you are not using HTTP chunked encoding.
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:682)
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:305)
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:64)
	at io.confluent.ksql.api.server.ProxyHandler$Pipe.handler(ProxyHandler.java:172)
```

**Additional context**
It also seems strange that this returns a 200, when there is an internal proxy error

**Comment by purplefox** [comment]
hi @jrea - will take a look soon, I am on PTO this week :)

**Comment by vcrfxia** [comment]
@jrea Can you try using the old content-type for the `/ksql` endpoint? This works for me in curl:
```
$ curl -X "POST" "http://localhost:8088/ksql" -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" -d '{"ksql":"SHOW STREAMS EXTENDED; SHOW TABLES EXTENDED;","streamsProperties":{}}'
```
(Note that it's the exact same command used before the introduction of the vert.x server and proxy handler.)

This is in contrast to how the new vert.x-only endpoints are accessed:
```
$ curl --http2 -X POST "http://localhost:8088/query-stream" -H "Content-Type: application/json; charset=utf-8" -d '{"sql":" select * from ksql_processing_log emit changes;"}'
```
In particular, the content type and HTTP version are different.

**Comment by purplefox** [comment]
https://github.com/confluentinc/ksql/pull/4777
