### ISSUE TITLE
Correct handling of timestamps belonging to leap days

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/ksql#4864]
**Describe the bug**
When ksql encounters a timestamp belonging to a leap day, it currently fails with the following

```
Caused by: java.time.DateTimeException: Invalid date 'DayOfYear 366' as '1970' is not a leap year
at java.time.LocalDate.ofYearDay(LocalDate.java:290)
at java.time.LocalDate.withDayOfYear(LocalDate.java:1118)
at java.time.LocalDate.with(LocalDate.java:1029)
at java.time.LocalDateTime.with(LocalDateTime.java:970)
at java.time.ZonedDateTime.with(ZonedDateTime.java:1311)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parseZoned(StringToTimestampParser.java:75)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:58)
at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:48)
at io.confluent.ksql.util.timestamp.StringTimestampExtractor.extract(StringTimestampExtractor.java:45)
at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:177)
```

**To Reproduce**

Able to reproduce this with a small test case

```
@Test
  public void testEscalation2522() {
    // Given
    final String format = "yyyy-MM-dd'T'HH:mm:ss.SSSX";
    final String timestamp = "2012-12-31T23:59:58.660Z";

    // When
    final long ts = new StringToTimestampParser(format).parse(timestamp);

    // Then

  }
```

**Expected behavior**

Valid epoch timestamp is returned. 

**Actual behaviour**

```
java.time.DateTimeException: Invalid date 'DayOfYear 366' as '1970' is not a leap year

	at java.time.LocalDate.ofYearDay(LocalDate.java:290)
	at java.time.LocalDate.withDayOfYear(LocalDate.java:1118)
	at java.time.LocalDate.with(LocalDate.java:1029)
	at java.time.LocalDateTime.with(LocalDateTime.java:970)
	at java.time.ZonedDateTime.with(ZonedDateTime.java:1311)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parseZoned(StringToTimestampParser.java:75)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:58)
	at io.confluent.ksql.util.timestamp.StringToTimestampParser.parse(StringToTimestampParser.java:48)
	at io.confluent.ksql.util.timestamp.StringToTimestampParserTest.testEscalation2522(StringToTimestampParserTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Additional context**

**Comment by maxant** [comment]
this fix isn't yet released e.g. in 5.4.1 is it?
