### ISSUE TITLE
Confusing error message when starting two KSQL servers with same address

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#4873]
**Describe the bug**
Bad logging when starting two servers at same address. It was tricky to figure out why one of the servers wasn't coming up properly. I had to add additional logging statements to the code to figure out why the server failed to start.

**To Reproduce**
Start up two KSQL's with the same server config file so they'll have same address.

**Expected behavior**
Logging that looks like 
```
io.confluent.ksql.util.KsqlException: Failed to start API server
	at io.confluent.ksql.api.server.Server.start(Server.java:137)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startApiServer(KsqlRestApplication.java:378)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:342)
	at io.confluent.ksql.rest.server.ExecutableServer.startAsync(ExecutableServer.java:47)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:75)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:61)
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.confluent.ksql.api.server.Server.start(Server.java:132)
	... 5 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:415)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:509)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Actual behaviour**
```
[2020-03-23 13:17:00,294] ERROR Exception while waiting for pull query metrics to close (io.confluent.ksql.rest.server.KsqlRestApplication:462)
java.lang.NullPointerException
	at io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource.closeMetrics(StreamedQueryResource.java:180)
	at io.confluent.ksql.rest.server.KsqlRestApplication.triggerShutdown(KsqlRestApplication.java:460)
	at io.confluent.ksql.rest.server.ExecutableServer.triggerShutdown(ExecutableServer.java:54)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:83)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:61)
[2020-03-23 13:17:15,306] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:63)
java.lang.IllegalStateException: Not started
	at io.confluent.ksql.api.server.Server.stop(Server.java:147)
	at io.confluent.ksql.rest.server.KsqlRestApplication.triggerShutdown(KsqlRestApplication.java:489)
	at io.confluent.ksql.rest.server.ExecutableServer.triggerShutdown(ExecutableServer.java:54)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:83)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:61)
[2020-03-23 13:17:15,343] ERROR Exception while waiting for pull query metrics to close (io.confluent.ksql.rest.server.KsqlRestApplication:462)
java.lang.NullPointerException
	at io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource.closeMetrics(StreamedQueryResource.java:180)
	at io.confluent.ksql.rest.server.KsqlRestApplication.triggerShutdown(KsqlRestApplication.java:460)
	at io.confluent.ksql.rest.server.KsqlRestApplication.onShutdown(KsqlRestApplication.java:519)
	at io.confluent.rest.Application.doShutdown(Application.java:561)
	at io.confluent.rest.ApplicationGroup.doStop(ApplicationGroup.java:45)
	at io.confluent.rest.ApplicationServer.doStop(ApplicationServer.java:179)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:127)
```

**Additional context**
Tested on master with commit e10bbcede42f209765e96b2b2bb392f4d83b2560

**Comment by stevenpyzhang** [comment]
There's a PR open for this https://github.com/confluentinc/ksql/pull/4974
