### ISSUE TITLE
Latest 5.4.x RPM packages cannot start /usr/bin/ksql

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#4916]
**Describe the bug**

When running `/usr/bin/ksql`, we get the exception below. Note that this error does _not_ occur when running the packages installed via 5.5.x (which can hook up the CLI to the old running server)

**To Reproduce**

Install the ksql packages as described in https://docs.confluent.io/current/installation/installing_cp/rhel-centos.html#get-the-software then spin up zk, kafka and ksql. All of them should work, but then connecting via `/usr/bin/ksql` does not 😢 

**Expected behavior**

We should be able to connect!

**Actual behaviour**

```
Exception in thread "main" java.lang.NoSuchMethodError: org.glassfish.jersey.internal.LocalizationMessages.WARNING_PROPERTIES()Ljava/lang/String;
	at org.glassfish.jersey.internal.config.SystemPropertiesConfigurationModel.getProperties(SystemPropertiesConfigurationModel.java:120)
	at org.glassfish.jersey.internal.config.SystemPropertiesConfigurationProvider.getProperties(SystemPropertiesConfigurationProvider.java:29)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFactory.readExternalPropertiesMap(ExternalPropertiesConfigurationFactory.java:55)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFactory.configure(ExternalPropertiesConfigurationFactory.java:72)
	at org.glassfish.jersey.internal.config.ExternalPropertiesConfigurationFeature.configure(ExternalPropertiesConfigurationFeature.java:26)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:677)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:611)
	at org.glassfish.jersey.client.ClientConfig$State.configureMetaProviders(ClientConfig.java:387)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:802)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:261)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:119)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:88)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:84)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:75)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at io.confluent.ksql.rest.client.KsqlTarget.get(KsqlTarget.java:140)
	at io.confluent.ksql.rest.client.KsqlTarget.getServerInfo(KsqlTarget.java:70)
	at io.confluent.ksql.rest.client.KsqlRestClient.getServerInfo(KsqlRestClient.java:82)
	at io.confluent.ksql.cli.Cli.displayWelcomeMessage(Cli.java:187)
	at io.confluent.ksql.cli.Cli.runInteractively(Cli.java:166)
	at io.confluent.ksql.Ksql.run(Ksql.java:95)
	at io.confluent.ksql.Ksql.main(Ksql.java:71)
```

**Additional context**

**Comment by agavra** [comment]
Turns out this was because some of my jars were downloaded with 5.5.x RPMs and others with 5.4 RPMs. Closing this ticket.
