### ISSUE TITLE
KSQL Docker image doesn't get successfully started

### ISSUE THREAD

**Issue by a-hosseini** [confluentinc/ksql#5011]
**Describe the bug**
I have a cluster of Kafka running in AWS. I am going to get KSQL running so I can query my topics. I am using the Docker hub image as follows:
`docker run -it --rm --name ksqldb -e KSQL_BOOTSTRAP_SERVERS=<my brokers comma separated> -e KSQL_LISTENERS=http://127.0.0.1:8088/ -p 127.0.0.1:8088:8088 -e KSQL_KSQL_SERVICE_ID=ksql_service confluentinc/cp-ksql-server:5.4.1`

**To Reproduce**
The KSQL get started on port 8088 and I get a brief info when I run `curl -sX GET "http://127.0.0.1:8088/info"` but KSQL-cli fails to connect to the server. 

I see this in the KSQL server logs:

```
io.confluent.ksql.util.KsqlException: Cannot load UDF bigDecimalNoSchemaProvider. BigDecimal return type is not supported without a schema provider method.
	at io.confluent.ksql.function.FunctionLoaderUtils.handleUdfReturnSchema(FunctionLoaderUtils.java:186)
	at io.confluent.ksql.function.UdtfLoader.createTableFunction(UdtfLoader.java:144)
	at io.confluent.ksql.function.UdtfLoader.loadUdtfFromClass(UdtfLoader.java:108)
	at io.confluent.ksql.function.UserFunctionLoader.lambda$loadFunctions$6(UserFunctionLoader.java:133)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$8.lookForMatches(ScanSpec.java:1316)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:696)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1606)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1678)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1704)
	at io.confluent.ksql.function.UserFunctionLoader.loadFunctions(UserFunctionLoader.java:135)
	at io.confluent.ksql.function.UserFunctionLoader.load(UserFunctionLoader.java:82)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:498)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:452)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:94)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:57)
[2020-04-06 19:59:03,048] WARN Failed to add UDTF to the MetaStore. name=rawListReturn method=public java.util.List io.confluent.ksql.function.UdtfLoaderTest$RawListReturn.badReturn(int) (io.confluent.ksql.function.UdtfLoader:118)
io.confluent.ksql.util.KsqlException: UDTF functions must return a parameterized List. Class io.confluent.ksql.function.UdtfLoaderTest$RawListReturn Method badReturn
	at io.confluent.ksql.function.UdtfLoader.loadUdtfFromClass(UdtfLoader.java:97)
	at io.confluent.ksql.function.UserFunctionLoader.lambda$loadFunctions$6(UserFunctionLoader.java:133)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$8.lookForMatches(ScanSpec.java:1316)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:696)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1606)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1678)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1704)
	at io.confluent.ksql.function.UserFunctionLoader.loadFunctions(UserFunctionLoader.java:135)
	at io.confluent.ksql.function.UserFunctionLoader.load(UserFunctionLoader.java:82)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:498)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:452)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:94)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:57)
[2020-04-06 19:59:03,050] WARN Failed to add UDTF to the MetaStore. name=badReturnUdtf method=public java.util.Map io.confluent.ksql.function.UdtfLoaderTest$UdtfBadReturnValue.badReturn(int) (io.confluent.ksql.function.UdtfLoader:118)
io.confluent.ksql.util.KsqlException: UDTF functions must return a List. Class io.confluent.ksql.function.UdtfLoaderTest$UdtfBadReturnValue Method badReturn
	at io.confluent.ksql.function.UdtfLoader.loadUdtfFromClass(UdtfLoader.java:90)
	at io.confluent.ksql.function.UserFunctionLoader.lambda$loadFunctions$6(UserFunctionLoader.java:133)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$8.lookForMatches(ScanSpec.java:1316)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:696)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1606)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1678)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1704)
	at io.confluent.ksql.function.UserFunctionLoader.loadFunctions(UserFunctionLoader.java:135)
	at io.confluent.ksql.function.UserFunctionLoader.load(UserFunctionLoader.java:82)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:498)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:452)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:94)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:57)
```

Once server gets  started I get this message:
```
[2020-04-06 19:59:11,554] INFO Server up and running (io.confluent.ksql.rest.server.KsqlServerMain:74)
[2020-04-06 19:59:12,693] INFO Successfully submitted metrics to Confluent via secure endpoint (io.confluent.support.metrics.submitters.ConfluentSubmitter:143)
[2020-04-06 19:59:14,694] INFO 127.0.0.1 - - [06/Apr/2020:19:59:14 +0000] "POST //ksql HTTP/1.1" 404 3680  4 (io.confluent.rest-utils.requests:62)
[2020-04-06 19:59:19,795] INFO 127.0.0.1 - - [06/Apr/2020:19:59:19 +0000] "POST //ksql HTTP/1.1" 404 3783  6 (io.confluent.rest-utils.requests:62)
```

**Comment by apurvam** [comment]
Which CLI distribution are you using? Do you have the CLI logs to share?

**Comment by a-hosseini** [comment]
I have figured that out, was using a wrong port.
