### ISSUE TITLE
The DefaultKsqlClient is not configured for TLS

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#5055]
**Describe the bug**
If KSQL servers are configured for HTTPS, they can't make requests to each other successfully because the client used by the servers isn't configured for TLS.

**To Reproduce**

1. Set up KSQL server for https
2. Start up two servers at `https://localhost:8089` and `https://localhost:8088`
3. Execute a query `Create stream test as select * from KSQL_PROCESSING_LOG;`
4. Issue a `Show queries;` request to one of the servers

**Expected behavior**
The server handling the request is able to issue a successful `Show queries` request to the other server.

**Actual behaviour**
The server handling the request fails and this is in the logs.
```
Failed to retrieve query info from host. host: HostInfo{host='localhost', port=8089}, cause: io.confluent.ksql.rest.client.KsqlRestClientException: Cannot make request with scheme https as client is configured without tls (ListQueriesExecutor.java:280)
```

**Additional context**
I verified this is also a problem with heartbeats enabled

```
[2020-04-13 10:40:47,359] ERROR Request to server: KsqlHostInfo{host='localhost', port=8088} failed with exception: Cannot make request with scheme https as client is configured without tls (io.confluent.ksql.rest.server.HeartbeatAgent:326)
io.confluent.ksql.rest.client.KsqlRestClientException: Cannot make request with scheme https as client is configured without tls
	at io.confluent.ksql.rest.client.KsqlClient.target(KsqlClient.java:104)
	at io.confluent.ksql.rest.server.services.DefaultKsqlClient.makeAsyncHeartbeatRequest(DefaultKsqlClient.java:107)
	at io.confluent.ksql.rest.server.HeartbeatAgent$SendHeartbeatService.runOneIteration(HeartbeatAgent.java:322)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Tested on master with commit: 988c3d1068b4cf970ea6c31fecf58496b7c7ee72

**Comment by stevenpyzhang** [comment]
This isn't an issue with heartbeats in 5.5 so this is likely related to the recent Vertx refactor to the clients.

**Comment by stevenpyzhang** [comment]
Tested Heartbeats at commit 2ac521b225f22cde6db68d4ab8b444d80ec0ba23 which is right before https://github.com/confluentinc/ksql/pull/4609 and it worked. It fails with the error after pulling these changes.

**Comment by apurvam** [comment]
cc @vcrfxia @purplefox  seems to be a regression with the vert.x changes.

**Comment by purplefox** [comment]
I'm curious what the expected behaviour is in the case each server has two listeners - one listening on https and another listening on http. Should the default client use http or https?

**Comment by purplefox** [comment]
> I'm curious what the expected behaviour is in the case each server has two listeners - one listening on https and another listening on http. Should the default client use http or https?

Answering my own question - currently if advertised listener is not specified then it uses the first one i the listeners string.
