### ISSUE TITLE
NullPointerException from struct dereference in PARTITION BY on 0.8.0/0.8.1

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5481]
The following bug is present on 0.8.0 and 0.8.1, but not 0.9.0 or master. It's possible the bug is present on earlier versions as well. Filing so we have a record of the bug, even though it's already been fixed.

**Describe the bug**

If struct dereference fails because the struct field is null, queries that partition by the inner field will fail with a NullPointerException, which kills the Streams threads and prevents further processing. This is in contrast to the behavior of ksqlDB if the PARTITION BY expression is null, in which case the record is ignored and processing continues as usual.

**To Reproduce**

1. Create source stream:
  ```
  create stream test (raw varchar, nested struct<f1 varchar, f2 varchar>) with (kafka_topic='test', value_format='json');
  ```
1. Create repartition stream:
  ```
  create stream test_partition_nested as select * from test partition by nested->f1;
  ```
1. Produce source record with null struct field: `{"raw":"foo"}`

**Expected behavior**

The Streams threads should not die. Either no record should appear in the repartitioned stream (which is consistent with the behavior when the source record `{"raw":"foo", "nested":{"f2":"bar}}` is produced) or a record with null key should be produced. Either way the query should continue to process subsequent data, rather than error-ing out.

We should also log an error to the processing log.

**Actual behaviour**

The Streams threads die with an NPE:
```
[2020-05-26 12:44:20,359] ERROR stream-thread [_confluent-ksql-default_query_CSAS_TEST_PARTITION_NESTED_0-c97501dc-75b8-4b8e-a335-05896ac7f741-StreamThread-2] Failed to process stream task 0_0 due to the following error: (org.apache.kafka.streams.processor.internals.AssignedStreamsTasks:483)
org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=test, partition=0, offset=3, stacktrace=io.confluent.ksql.util.KsqlException
	at io.confluent.ksql.execution.codegen.ExpressionMetadata.evaluate(ExpressionMetadata.java:69)
	at io.confluent.ksql.execution.streams.StreamSelectKeyBuilder.lambda$build$0(StreamSelectKeyBuilder.java:58)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:56)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
Caused by: java.lang.NullPointerException
	at SC.eval0(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:756)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:748)
	at io.confluent.ksql.execution.codegen.ExpressionMetadata.evaluate(ExpressionMetadata.java:67)
	... 24 more

	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:400)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
Caused by: io.confluent.ksql.util.KsqlException
	at io.confluent.ksql.execution.codegen.ExpressionMetadata.evaluate(ExpressionMetadata.java:69)
	at io.confluent.ksql.execution.streams.StreamSelectKeyBuilder.lambda$build$0(StreamSelectKeyBuilder.java:58)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:42)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:56)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	... 5 more
Caused by: java.lang.NullPointerException
	at SC.eval0(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:756)
	at org.codehaus.janino.ScriptEvaluator.evaluate(ScriptEvaluator.java:748)
	at io.confluent.ksql.execution.codegen.ExpressionMetadata.evaluate(ExpressionMetadata.java:67)
	... 24 more
```

**Additional context**

On 0.9.0 and master, the behavior is fixed and a message is logged to the processing log as expected:
```
ERROR {"type":1,"deserializationError":null,"recordProcessingError":{"errorMessage":"Error computing new key from expression NESTED->F1","record":null,"cause":[]},"productionError":null} (processing.CSAS_TEST_PARTITION_NESTED_0.PartitionBy:44)
```

**Comment by vcrfxia** [comment]
A workaround for older versions is to add WHERE clauses to filter out rows that could result in NPEs in the PARTITION BY.

**Comment by vcrfxia** [comment]
Closing as this issue has since been fixed.
