### ISSUE TITLE
ksql-cli local exit hangs if ksql-server is unable to contact the broker

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#553]
If I run `ksql-cli local`, stop the broker, and then try and exit ksql, the client hangs and does not respond to interrupts. jstack shows that its stuck here:

```
"main" #1 prio=5 os_prio=31 tid=0x00007f931e820000 nid=0x1c03 in Object.wait() [0x0000700003e41000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.kafka.streams.KafkaStreams.waitOnState(KafkaStreams.java:221)
	- locked <0x000000072a406648> (a java.lang.Object)
	at org.apache.kafka.streams.KafkaStreams.close(KafkaStreams.java:836)
	- locked <0x0000000729d5b180> (a org.apache.kafka.streams.KafkaStreams)
	at org.apache.kafka.streams.KafkaStreams.close(KafkaStreams.java:766)
	at io.confluent.ksql.util.QueryMetadata.close(QueryMetadata.java:92)
	at io.confluent.ksql.KsqlEngine.terminateAllQueries(KsqlEngine.java:480)
	at io.confluent.ksql.cli.LocalCli.close(LocalCli.java:49)
	at io.confluent.ksql.cli.commands.AbstractCliCommands.run(AbstractCliCommands.java:87)
	at io.confluent.ksql.Ksql.main(Ksql.java:43)
```

**Comment by miguno** [comment]
Is this still an issue?

**Comment by rmoff** [comment]
I cannot reproduce this with 5.0.0-SNAPSHOT

Connect to KSQL server: 

    ksql http://ksql-server:8088

Shut down broker

Ctrl-D in KSQL CLI to exit - returns to shell prompt straight away
```

ksql>
Exiting KSQL.
Robin@asgard02 ~/g/d/ksql-workshop>
```
