### ISSUE TITLE
Opaque error messages from /inserts-stream endpoint

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5585]
**Describe the bug**

Certain user errors, such as attempting to use Avro without having configured Schema Registry, are not exposed in responses from the /inserts-stream endpoint. The errors are logged to the server logs, but all clients see is `Received error from /inserts-stream. Error code: 50000. Message: Error in processing inserts` which is not actionable. 

**To Reproduce**

On 6.0.x or master (probably present for 5.5.x as well):
- Start ksqlDB server without Schema Registry
- Create an Avro stream
- Insert a row to the stream via the `/inserts-stream` endpoint

**Expected behavior**

A clear error message indicating that Avro cannot be used without configuring Schema Registry.

**Actual behaviour**

The error message `Error in processing inserts` with error code 50000:
```
Received error from /inserts-stream. Error code: 50000. Message: Error in processing inserts
```

The server logs contain:
```
[2020-06-09 14:50:12,623] ERROR Error in processing inserts (io.confluent.ksql.api.server.AcksSubscriber:100)
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: transactions. Failed to serialize Avro data from topic transactions :
Caused by: org.apache.kafka.connect.errors.DataException: Failed to serialize Avro data from topic transactions :
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:91)
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:49)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:285)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:251)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:143)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:51)
	at io.confluent.ksql.reactive.BaseSubscriber.doOnNext(BaseSubscriber.java:191)
	at io.confluent.ksql.reactive.BaseSubscriber.lambda$onNext$1(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BaseSubscriber.runOnRightContext(BaseSubscriber.java:153)
	at io.confluent.ksql.reactive.BaseSubscriber.onNext(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BasePublisher.doOnNext(BasePublisher.java:106)
	at io.confluent.ksql.reactive.BufferedPublisher.maybeSend(BufferedPublisher.java:149)
	at io.confluent.ksql.reactive.BasePublisher.doRequest(BasePublisher.java:182)
	at io.confluent.ksql.reactive.BasePublisher.access$200(BasePublisher.java:32)
	at io.confluent.ksql.reactive.BasePublisher$Sub.lambda$request$0(BasePublisher.java:200)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: io.confluent.ksql.util.KsqlSchemaRegistryNotConfiguredException: KSQL is not configured to use a schema registry. To enable it, please set ksql.schema.registry.url
	at io.confluent.ksql.schema.registry.DefaultSchemaRegistryClient.<init>(DefaultSchemaRegistryClient.java:44)
	at io.confluent.ksql.schema.registry.KsqlSchemaRegistryClientFactory.get(KsqlSchemaRegistryClientFactory.java:114)
	at io.confluent.ksql.serde.avro.KsqlAvroSerdeFactory.createConnectSerializer(KsqlAvroSerdeFactory.java:107)
	at io.confluent.ksql.serde.avro.KsqlAvroSerdeFactory.lambda$createSerde$0(KsqlAvroSerdeFactory.java:61)
	at io.confluent.ksql.serde.tls.ThreadLocalCloseable.lambda$new$0(ThreadLocalCloseable.java:38)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at io.confluent.ksql.serde.tls.ThreadLocalCloseable.get(ThreadLocalCloseable.java:45)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:285)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:251)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:143)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:51)
	at io.confluent.ksql.reactive.BaseSubscriber.doOnNext(BaseSubscriber.java:191)
	at io.confluent.ksql.reactive.BaseSubscriber.lambda$onNext$1(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BaseSubscriber.runOnRightContext(BaseSubscriber.java:153)
	at io.confluent.ksql.reactive.BaseSubscriber.onNext(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BasePublisher.doOnNext(BasePublisher.java:106)
	at io.confluent.ksql.reactive.BufferedPublisher.maybeSend(BufferedPublisher.java:149)
	at io.confluent.ksql.reactive.BasePublisher.doRequest(BasePublisher.java:182)
	at io.confluent.ksql.reactive.BasePublisher.access$200(BasePublisher.java:32)
	at io.confluent.ksql.reactive.BasePublisher$Sub.lambda$request$0(BasePublisher.java:200)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional context**

Other errors (besides not having configured Schema Registry) are similarly opaque. For example, Schema Registry may be configured but if the ksqlDB server is unable to access Schema Registry, the same opaque error is returned to the client. The server error message is:
```
[2020-06-09 14:56:10,104] ERROR Error in processing inserts (io.confluent.ksql.api.server.AcksSubscriber:100)
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: transactions. Failed to serialize Avro data from topic transactions :
Caused by: org.apache.kafka.connect.errors.DataException: Failed to serialize Avro data from topic transactions :
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:91)
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:49)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:285)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:251)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:143)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:51)
	at io.confluent.ksql.reactive.BaseSubscriber.doOnNext(BaseSubscriber.java:191)
	at io.confluent.ksql.reactive.BaseSubscriber.lambda$onNext$1(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BaseSubscriber.runOnRightContext(BaseSubscriber.java:153)
	at io.confluent.ksql.reactive.BaseSubscriber.onNext(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BasePublisher.doOnNext(BasePublisher.java:106)
	at io.confluent.ksql.reactive.BufferedPublisher.maybeSend(BufferedPublisher.java:149)
	at io.confluent.ksql.reactive.BasePublisher.doRequest(BasePublisher.java:182)
	at io.confluent.ksql.reactive.BasePublisher.access$200(BasePublisher.java:32)
	at io.confluent.ksql.reactive.BasePublisher$Sub.lambda$request$0(BasePublisher.java:200)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1301)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1299)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1298)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:263)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:351)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:494)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:485)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:458)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:74)
	at io.confluent.connect.avro.AvroConverter$Serializer.serialize(AvroConverter.java:143)
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:84)
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:49)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:285)
	at io.confluent.ksql.serde.GenericRowSerDe$GenericRowSerializer.serialize(GenericRowSerDe.java:251)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:143)
	at io.confluent.ksql.api.impl.InsertsSubscriber.handleValue(InsertsSubscriber.java:51)
	at io.confluent.ksql.reactive.BaseSubscriber.doOnNext(BaseSubscriber.java:191)
	at io.confluent.ksql.reactive.BaseSubscriber.lambda$onNext$1(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BaseSubscriber.runOnRightContext(BaseSubscriber.java:153)
	at io.confluent.ksql.reactive.BaseSubscriber.onNext(BaseSubscriber.java:67)
	at io.confluent.ksql.reactive.BasePublisher.doOnNext(BasePublisher.java:106)
	at io.confluent.ksql.reactive.BufferedPublisher.maybeSend(BufferedPublisher.java:149)
	at io.confluent.ksql.reactive.BasePublisher.doRequest(BasePublisher.java:182)
	at io.confluent.ksql.reactive.BasePublisher.access$200(BasePublisher.java:32)
	at io.confluent.ksql.reactive.BasePublisher$Sub.lambda$request$0(BasePublisher.java:200)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vcrfxia** [comment]
Hey @purplefox @MichaelDrogalis it's not clear to me what the desired error messages in these scenarios are.

The error message on the server is `Error serializing message to topic: transactions. Failed to serialize Avro data from topic transactions :` which doesn't seem useful to expose to the client.

In the first example where the problem is that Schema Registry has not been configured, we could check for the `KsqlSchemaRegistryNotConfiguredException` in the stack trace and return a more useful message to the client, but this sort of custom error-handling doesn't work in the second example where Schema Registry is configured but ksqlDB is unable to reach Schema Registry. 

Does it make sense to try to craft custom error messages to return to the client? It feels like the AvroConverter is a better place to try to improve error messages, rather than in ksqlDB.

What about keeping the generic message `Error in processing inserts.` and appending `Check the server logs for more.`? We could also check if the stream is Avro or Protobuf and add `Is ksqlDB configured with Schema Registry?` if so.

**Comment by MichaelDrogalis** [comment]
Yeah I also don't think getting into custom-propagated error handling is a great idea. If we're confident all these errors will turn up in the server logs, I think it's sufficient to just note that in the error message.
