### ISSUE TITLE
Subscript Expressions in GROUP BY not valid as non-aggregate SELECT function arguments

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#5906]
**Describe the bug**

When aggregating a stream with a `GROUP BY` expression that involves a subscript expression (i.e. map lookup, `col1['foo']` the AggregateAnalyzer will not properly accept them as function arguments to non-aggregate functions.

**To Reproduce**

```json
    {
      "name": "Subscript Expressions in GROUP BY not valid non-aggregate SELECT function arguments",
      "statements": [
        "CREATE STREAM input (id INT KEY, col1 MAP<VARCHAR, VARCHAR>) WITH (kafka_topic='input', value_format='json');",
        "CREATE TABLE output AS SELECT col1['foo'], AS_VALUE(col1['foo']) AS foo, COUNT(*) FROM input WINDOW TUMBLING (SIZE 10 MILLISECONDS) GROUP BY col1['foo'];"
      ],
      "inputs": [],
      "outputs": []
    },
```

**Expected behavior**

The query succeeds.

**Actual behaviour**

```
Caused by: io.confluent.ksql.util.KsqlException: Non-aggregate SELECT expression(s) not part of GROUP BY: AS_VALUE(COL1['foo'])
Either add the column to the GROUP BY or remove it from the SELECT.
	at io.confluent.ksql.analyzer.AggregateAnalyzer$AggAnalyzer.enforceAggregateRules(AggregateAnalyzer.java:258)
	at io.confluent.ksql.analyzer.AggregateAnalyzer$AggAnalyzer.result(AggregateAnalyzer.java:240)
	at io.confluent.ksql.analyzer.AggregateAnalyzer.analyze(AggregateAnalyzer.java:62)
	at io.confluent.ksql.planner.LogicalPlanner.buildAggregateNode(LogicalPlanner.java:234)
	at io.confluent.ksql.planner.LogicalPlanner.buildPlan(LogicalPlanner.java:132)
	at io.confluent.ksql.engine.QueryEngine.buildQueryLogicalPlan(QueryEngine.java:74)
	at io.confluent.ksql.engine.EngineExecutor.planQuery(EngineExecutor.java:202)
	at io.confluent.ksql.engine.EngineExecutor.plan(EngineExecutor.java:161)
	at io.confluent.ksql.engine.KsqlEngine.plan(KsqlEngine.java:186)
	at io.confluent.ksql.test.tools.TestExecutorUtil$PlannedStatementIterator.planStatement(TestExecutorUtil.java:422)
	... 40 more
```

**Additional context**

Note that the same expression will work if the group by column is not a subscript expression, such as:
```json
      "statements": [
        "CREATE STREAM input (id INT KEY, col1 VARCHAR) WITH (kafka_topic='input', value_format='json');",
        "CREATE TABLE output AS SELECT col1, AS_VALUE(col1) AS foo, COUNT(*) FROM input WINDOW TUMBLING (SIZE 10 MILLISECONDS) GROUP BY col1;"
      ],
```

**Comment by MichaelDrogalis** [comment]
Adding triage for discussion tomorrow.

**Comment by vpapavas** [comment]
Hey @agavra , 

I think this query should not work in the first place
```
CREATE TABLE output AS SELECT col1, AS_VALUE(col1) AS foo, COUNT(*) FROM input WINDOW TUMBLING (SIZE 10 MILLISECONDS) GROUP BY col1;
```
Because one is only allowed to use in the `SELECT` clause fields that are either aggregate functions or grouping keys. So, for the above query to work, it should be
```
CREATE TABLE output AS SELECT col1, AS_VALUE(col1) AS foo, COUNT(*) FROM input WINDOW TUMBLING (SIZE 10 MILLISECONDS) GROUP BY col1, AS_VALUE(col1);
```

Unless we are treating the function `AS_VALUE` as a special case and make an exception allowing only this to appear in the `SELECT` clause of a grouping query? I know it copies the column in the value so technically it wouldn't mess up the groups. Just trying to understand the scope of this bug. Is it specific to the function `AS_VALUE` or other udfs as well?

**Comment by agavra** [comment]
@vpapavas I don't think this is the case. The following works:
```sql
ksql> CREATE STREAM input2 (id INT KEY, col1 VARCHAR) WITH (kafka_topic='input', value_format='json');

 Message
----------------
 Stream created
----------------
ksql> CREATE TABLE output AS SELECT col1, AS_VALUE(col1) AS foo, COUNT(*) FROM input2 WINDOW TUMBLING (SIZE 10 MILLISECONDS) GROUP BY col1;

 Message
-------------------------------------
 Created query with ID CTAS_OUTPUT_0
-------------------------------------
```

If you think about it, you should be able to use the group by column in _any_ non-aggregate function just the same way you'd be able to select it. You just apply the function once and use that value for every aggregate output.

**Comment by vpapavas** [comment]
OK, I found what the problem is and this bug I just filed is related #5967

**Comment by vpapavas** [comment]
I have fixed this bug there is another one. 
This simplified query 
```
CREATE TABLE test4 AS SELECT col1['foo'],  COUNT(*) FROM input GROUP BY col1['foo'];
```
fails in the `CodeGenRunner:visitDereferenceExpression:addRequiredColumn` with 
```
Invalid Group By: Cannot find the select field in the available fields. field: `COL1`, schema: [`ROWTIME` BIGINT]. expression:COL1['foo'], schema:`ID` INTEGER KEY, `ROWTIME` BIGINT
```

@big-andy-coates Any idea what this message means? I think this problem is related to the new key work. The query should work, no?

**Comment by big-andy-coates** [comment]
Don't think is related to the key work.

Looks like the code that is extracting the set of required columns in the analyser isn't picking up `col1`.  You can see this because the schema ` schema: [`ROWTIME` BIGINT]` doesn't include `COL1`.  My guess would be that `AggregateAnalyzer` is not adding the required column to the aggregate analysis result when handling subscripts .
