### ISSUE TITLE
KSQL fails silently if re-creating an Avro-encoded stream with different schema

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#595]
Running KSQL 0.3 from @hjafarpour's PR (https://github.com/hjafarpour/ksql/tree/KSQL-515-handle-nullable-avro-fields). Using Server + CLI mode. 

In CLI, define a stream: 
```sql
CREATE STREAM FOO AS SELECT CAST(LOGON_ID AS BIGINT), CAST(CUSTOMER_ID AS BIGINT), LOGON_DATE FROM LOGON;
```

Note that the `CAST`ed columns are not aliased. Schema in Schema Registry is: 

```json
{"type":"record","name":"avro_schema","namespace":"ksql","fields":[{"name":"KSQL_COL_0","type":"long"},{"name":"KSQL_COL_1","type":"long"},{"name":"LOGON_DATE","type":"string"}]}
```

Now drop and recreate the stream using aliases for the column names: 

```sql
ksql> DROP STREAM FOO;

 Message
------------------------
 Source FOO was dropped
------------------------
ksql> CREATE STREAM FOO AS SELECT CAST(LOGON_ID AS BIGINT) AS LOGON_ID, CAST(CUSTOMER_ID AS BIGINT) AS CUSTOMER_ID, LOGON_DATE FROM LOGON;

 Message
----------------------------
 Stream created and running
----------------------------
```

All appears well and happy with the world, except `FOO` returns no records. No error has been thrown to the user on the CLI so far. 

Checking `DESCRIBE` doesn't show any problems, nor does `SHOW QUERIES`

```sql
ksql> describe extended foo;

Type                 : STREAM
Key field            :
Timestamp field      : Not set - using <ROWTIME>
Key format           : STRING
Value format         : AVRO
Kafka output topic   : FOO (partitions: 4, replication: 1)

 Field       | Type
-----------------------------------------
 ROWTIME     | BIGINT           (system)
 ROWKEY      | VARCHAR(STRING)  (system)
 LOGON_ID    | BIGINT
 CUSTOMER_ID | BIGINT
 LOGON_DATE  | VARCHAR(STRING)
-----------------------------------------

Queries that write into this STREAM
-----------------------------------
id:CSAS_FOO - CREATE STREAM FOO AS SELECT CAST(LOGON_ID AS BIGINT) AS LOGON_ID, CAST(CUSTOMER_ID AS BIGINT) AS CUSTOMER_ID, LOGON_DATE FROM LOGON;

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------


(Statistics of the local KSQL server interaction with the Kafka topic FOO)
ksql> show queries;

 Query ID          | Kafka Topic  | Query String
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CSAS_FOO          | FOO          | CREATE STREAM FOO AS SELECT CAST(LOGON_ID AS BIGINT) AS LOGON_ID, CAST(CUSTOMER_ID AS BIGINT) AS CUSTOMER_ID, LOGON_DATE FROM LOGON;
 CSAS_CUST_REKEYED | CUST_REKEYED | CREATE STREAM CUST_REKEYED AS SELECT * FROM CUST_SRC PARTITION BY CUSTOMER_ID;
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
For detailed information on a Query run: EXPLAIN <Query ID>;
```

But checking the `stdout` for the server shows that the query barfed: 

```
Exception in thread "ksql_query_CSAS_FOO-df8ebd42-0e54-41ce-b32f-8d42489892c5-StreamThread-124" org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=ora-ogg2-SOE2-LOGON-avro, partition=0, offset=597686
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:235)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:417)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:918)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:798)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
Caused by: org.apache.kafka.common.errors.SerializationException: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: {"type":"record","name":"avro_schema","namespace":"ksql","fields":[{"name":"LOGON_ID","type":"long"},{"name":"CUSTOMER_ID","type":"long"},{"name":"LOGON_DATE","type":"string"}]}
Caused by: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: {"type":"record","name":"avro_schema","namespace":"ksql","fields":[{"name":"LOGON_ID","type":"long"},{"name":"CUSTOMER_ID","type":"long"},{"name":"LOGON_DATE","type":"string"}]}
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema being registered is incompatible with an earlier schema; error code: 409
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:199)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:226)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:315)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:307)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:302)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:107)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:146)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:79)
        at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
        at io.confluent.ksql.serde.avro.KsqlGenericRowAvroSerializer.serialize(KsqlGenericRowAvroSerializer.java:92)
        at io.confluent.ksql.serde.avro.KsqlGenericRowAvroSerializer.serialize(KsqlGenericRowAvroSerializer.java:38)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:147)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:94)
        at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:87)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:171)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:219)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:417)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:918)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:798)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
```

1. User should be told if there's a problem with the schema changing
2. `DESCRIBE EXTENDED` and `SHOW QUERIES` should indicate that the underlying query is dead.

**Comment by rmoff** [comment]
Related:  CSAS query aborts silently (to the CLI), had to go to Server `stdout` to find out why it wasn't running

```
Exception in thread "ksql_query_CSAS_LOGON_ENRICHED2-87cc2ddd-708c-422b-881c-c0bc32260bd8-StreamThread-199" org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000012, topic=ksql_query_CSAS_LOGON_ENRICHED2-KSTREAM-MAP-0000000009-repartition, partition=0, offset=0
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:235)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:417)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:918)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:798)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
Caused by: org.apache.kafka.common.errors.SerializationException: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException: null of long in field C_CUSTOMER_ID of ksql.avro_schema
        at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:145)
        at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:139)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:62)
        at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:101)
        at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
        at io.confluent.ksql.serde.avro.KsqlGenericRowAvroSerializer.serialize(KsqlGenericRowAvroSerializer.java:92)
        at io.confluent.ksql.serde.avro.KsqlGenericRowAvroSerializer.serialize(KsqlGenericRowAvroSerializer.java:38)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:147)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:94)
        at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:87)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.kstream.internals.KStreamKTableJoinProcessor.process(KStreamKTableJoinProcessor.java:58)
        at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
        at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
        at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:219)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:94)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:417)
        at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:918)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:798)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:750)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:720)
Caused by: java.lang.NullPointerException
```

**Comment by ybyzek** [comment]
+1

I was going to file a new issue but came across this one.  It is confusing for users to see everything look normal from CLI, including `DESCRIBE` and `EXPLAIN`, but no data is coming through.  Today I encountered an issue where KSQL was trying to read an Avro message with an invalid schema, and there were appropriate logs in the KSQL server output, but there was no indication from CLI.  These need to bubble up to the user.  In my case, the logs showed which CTAS/CSAS was impacted, so it should be easy to have some kind of error count in `EXPLAIN`

**Comment by rmoff** [comment]
As of 5.0.0-SNAPSHOT this no longer appears to be a problem. A new version of the schema is successfully created and registered.
