### ISSUE TITLE
KsqlTester should allow inserts into sources without DML

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#6058]
The following test:
```sql
----------------------------------------------------------------------------------------------------
--@test: basic test 2
----------------------------------------------------------------------------------------------------
CREATE STREAM foo (id INT KEY, col1 INT) WITH (kafka_topic='foo', value_format='JSON');
INSERT INTO foo (rowtime, id, col1) VALUES (1, 1, 1);
```

Will fail because there is no driver registered into the driver pipeline. The error message is:
```

io.confluent.ksql.test.KsqlTestException: Test failure for statement `INSERT INTO foo (rowtime, id, col1) VALUES (1, 1, 1);` (Line: 18, Col: 1):
	Cannot pipe input to unknown source: foo
	file:///Users/almog.gavra/dev/confluent/ksql/ksqldb-functional-tests/target/test-classes/sql-tests/test.sql:18

	at io.confluent.ksql.test.driver.KsqlTesterTest.handleExpectedException(KsqlTesterTest.java:324)
	at io.confluent.ksql.test.driver.KsqlTesterTest.test(KsqlTesterTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: io.confluent.ksql.util.KsqlException: Cannot pipe input to unknown source: foo
	at io.confluent.ksql.test.driver.TestDriverPipeline.pipeInput(TestDriverPipeline.java:184)
	at io.confluent.ksql.test.driver.TestDriverPipeline.pipeInput(TestDriverPipeline.java:166)
	at io.confluent.ksql.test.driver.KsqlTesterTest.pipeInput(KsqlTesterTest.java:260)
	at io.confluent.ksql.test.driver.KsqlTesterTest.execute(KsqlTesterTest.java:180)
	at io.confluent.ksql.test.parser.TestStatement.consume(TestStatement.java:81)
	at io.confluent.ksql.test.driver.KsqlTesterTest.test(KsqlTesterTest.java:163)
	... 35 more
```

**Comment by jzaralim** [comment]
#9321 fixes this
