### ISSUE TITLE
KsqlTester does not allow for DDL evolution

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#6059]
The following test does not work because after we register the schema for A the first time around, for some reason the testing tool does not let us evolve it:
```sql
----------------------------------------------------------------------------------------------------
--@test: ddl evolution
----------------------------------------------------------------------------------------------------

CREATE STREAM a (id INT KEY, col1 INT) WITH (kafka_topic='a', value_format='JSON');
CREATE STREAM b AS SELECT * FROM a;

INSERT INTO a (id, col1) VALUES (1, 1);
CREATE OR REPLACE STREAM a (id INT KEY, col1 INT, col2 INT) WITH (kafka_topic='a', value_format='JSON');

INSERT INTO a (id, col1, col2) VALUES (1, 1, 1);
```

It fails with this rather cryptic error message:
```
io.confluent.ksql.test.KsqlTestException: Test failure for statement `INSERT INTO a (id, col1, col2) VALUES (1, 1, 1);` (Line: 64, Col: 1):
	Field count mismatch. topic: a, expected: 1, got: 2
	file:///Users/almog.gavra/dev/confluent/ksql/ksqldb-functional-tests/target/test-classes/sql-tests/query-upgrades/projections.sql:64

	at io.confluent.ksql.test.driver.KsqlTesterTest.handleExpectedException(KsqlTesterTest.java:324)
	at io.confluent.ksql.test.driver.KsqlTesterTest.test(KsqlTesterTest.java:165)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.apache.kafka.common.errors.SerializationException: Field count mismatch. topic: a, expected: 1, got: 2
```

**Comment by agavra** [comment]
I think the reason for this is because we get the `keySerde` and `valueSerde` for the input topics the first time we register it with the pipeline:
```java
        .map(ds -> new TopicInfo(ds.getKafkaTopicName(), keySerde(ds), valueSerde(ds)))
```

From then on, even if the data source changes, we will use the same serdes. Output topics are re-registered each time so there is not a problem.

For input topics, we need to probably remove old drivers and add new ones if a `CREATE OR REPLACE` comes in for an input topic that is already registered
