### ISSUE TITLE
ksql-server-start will hang when it "Unable to check broker compatibility"

### ISSUE THREAD

**Issue by bryanyang0528** [confluentinc/ksql#611]
I use docker-compose to startup ksql-server with kafka and zookeeper.
I started a ksql server by calling ksql-server-start /etc/ksql/ksqlserver.properties by supervisor(python).
The process will hang after docker-compose up.
The error message in the log shows:

```
# cat /var/log/ksql/ksql-server.err.log
Exception in thread "main" io.confluent.ksql.util.KsqlException: Unable to check broker compatibility against a broker without any topics
	at io.confluent.ksql.rest.server.BrokerCompatibilityCheck.create(BrokerCompatibilityCheck.java:49)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:237)
	at io.confluent.ksql.rest.server.KsqlRestApplication.main(KsqlRestApplication.java:207)
```

* netstat

```
# netstat -nlopt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name Timer
tcp        0      0 0.0.0.0:33105           0.0.0.0:*               LISTEN      9/java           off (0.00/0/0)
tcp        0      0 127.0.0.11:36129        0.0.0.0:*               LISTEN      -                off (0.00/0/0)
```

* ps

```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.4  57660 19988 ?        Ss   10:56   0:00 /usr/bin/python /usr/bin/supervisord -n
root         9  0.4  1.7 5934148 68964 ?       Sl   10:56   0:03 java -cp /usr/share/java/ksql-cli/*: -Xmx3g -server -XX:+UseParNe
root        35  0.0  0.0   4336  1644 pts/0    Ss   10:56   0:00 /bin/sh
root       819  0.0  0.0  19188  2404 pts/0    R+   11:09   0:00 ps aux
```

This is the content of the config file of supervisor.
```
[program:ksql-server]
command=/usr/bin/ksql-server-start /etc/ksql/ksqlserver.properties
directory=/usr/bin
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/ksql/ksql-server.err.log
stdout_logfile=/var/log/ksql/ksql-server.out.log
user=root
```

Full of the Dockerfile is here [https://github.com/bryanyang0528/ksql-python/tree/master/ksql-server](https://github.com/bryanyang0528/ksql-python/tree/master/ksql-server)

It will be fine after I kill the current process and supervisor will start the server again.
I guess the problem will happen when the Kafka server is not ready. 

Thanks

**Comment by hjafarpour** [comment]
@bryanyang0528 at the moment compatibility check needs at least one topic in your kafka cluster. Please create a topic first and then start KSQL server.

**Comment by bryanyang0528** [comment]
@hjafarpour Thank you for your quick response!
