### ISSUE TITLE
Internal Server Error for /healthcheck endpoint in RBAC-enabled ksqlDB cluster

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#6479]
**Describe the bug**
Internal server error (500) occurs when accessing /healthcheck endpoint in RBAC-enabled ksqlDB 6.0.0 cluster. Error occurs with or without valid credentials (this is supposed to be an open, non-authorized endpoint). Other endpoints like /info work fine with the same credentials.

Exception in ksqlDB server looks like:
```
[2020-10-20 14:56:03,341] ERROR Failed to handle request -1 /healthcheck (io.confluent.ksql.api.server.FailureHandler:38)
io.confluent.ksql.util.KsqlException: Invalid user principal found. Got: null Expected: JwtPrincipal.
	at io.confluent.ksql.security.utils.KsqlSecurityUtils.toJwtPrincipal(KsqlSecurityUtils.java:27)
	at io.confluent.ksql.security.KsqlUserContextProviderImpl.getKafkaClientSupplier(KsqlUserContextProviderImpl.java:41)
	at io.confluent.ksql.api.impl.DefaultKsqlSecurityContextProvider.lambda$provide$0(DefaultKsqlSecurityContextProvider.java:74)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.confluent.ksql.api.impl.DefaultKsqlSecurityContextProvider.provide(DefaultKsqlSecurityContextProvider.java:69)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.executeOldApiEndpoint(KsqlServerEndpoints.java:295)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.executeCheckHealth(KsqlServerEndpoints.java:230)
	at io.confluent.ksql.api.server.ServerVerticle.lambda$handleHealthcheckRequest$12(ServerVerticle.java:289)
	at io.confluent.ksql.api.server.OldApiUtils.handleOldApiRequest(OldApiUtils.java:69)
	at io.confluent.ksql.api.server.ServerVerticle.handleHealthcheckRequest(ServerVerticle.java:287)
```

**To Reproduce**
Issue can be reproduced in cp-demo (6.0.0-post branch), executing the following curl command:
```
curl -u ksqlDBAdmin:ksqlDBAdmin http://localhost:8088/healthcheck
```

**Expected behavior**
Curl should return a response from the healthcheck endpoint without errors.

**Actual behaviour**
Curl is failing with the output:
```
[2020-10-20 14:56:03,341] ERROR Failed to handle request -1 /healthcheck (io.confluent.ksql.api.server.FailureHandler:38)
io.confluent.ksql.util.KsqlException: Invalid user principal found. Got: null Expected: JwtPrincipal.
	at io.confluent.ksql.security.utils.KsqlSecurityUtils.toJwtPrincipal(KsqlSecurityUtils.java:27)
	at io.confluent.ksql.security.KsqlUserContextProviderImpl.getKafkaClientSupplier(KsqlUserContextProviderImpl.java:41)
	at io.confluent.ksql.api.impl.DefaultKsqlSecurityContextProvider.lambda$provide$0(DefaultKsqlSecurityContextProvider.java:74)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.confluent.ksql.api.impl.DefaultKsqlSecurityContextProvider.provide(DefaultKsqlSecurityContextProvider.java:69)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.executeOldApiEndpoint(KsqlServerEndpoints.java:295)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.executeCheckHealth(KsqlServerEndpoints.java:230)
	at io.confluent.ksql.api.server.ServerVerticle.lambda$handleHealthcheckRequest$12(ServerVerticle.java:289)
	at io.confluent.ksql.api.server.OldApiUtils.handleOldApiRequest(OldApiUtils.java:69)
	at io.confluent.ksql.api.server.ServerVerticle.handleHealthcheckRequest(ServerVerticle.java:287)
```

**Additional context**
The error is caused by Vert.x changes. During authentication, Vert.x is setting the `Principal` as NULL when paths that not require authentication are detected. Seems the issue is in `KsqlServerEndpoints::executeOldApiEndpoint`:
```
private CompletableFuture<EndpointResponse> executeOldApiEndpoint(
      final ApiSecurityContext apiSecurityContext,
      final Function<KsqlSecurityContext, EndpointResponse> functionCall) {

    final KsqlSecurityContext ksqlSecurityContext = ksqlSecurityContextProvider
        .provide(apiSecurityContext);

    try {
      return CompletableFuture.completedFuture(functionCall.apply(ksqlSecurityContext));
    } finally {
      ksqlSecurityContext.getServiceContext().close();
    }
  }
```
^ The `ksqlSecurityContextProvider.provide(...)` is throwing the exception that the principal is NULL. We shouldn't call this code if there's no principal (user is not authenticated).

**Comment by spena** [comment]
Fixed in 6.0.x and master
