### ISSUE TITLE
PRINT bug : "Index 0 out of bounds for length 0"

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#6565]
ksqlDB 0.12

Topic contents: 

```
kafkacat -b localhost:9092 -t orders_processed -J -C -u | jq '.'                                                                                                               255 ↵
{
  "topic": "orders_processed",
  "partition": 0,
  "offset": 0,
  "tstype": "create",
  "ts": 1604426116850,
  "key": "\u0000\u0000\u0000\u0001",
  "payload": "\u0000\u0000\u0000\u0000\u0004\u0002�G�z\u0014�(@\u0002\bCake\u0002\u0000\u0002����"
}
{
  "topic": "orders_processed",
  "partition": 0,
  "offset": 1,
  "tstype": "create",
  "ts": 1604426116852,
  "key": "\u0000\u0000\u0000\u0003",
  "payload": "\u0000\u0000\u0000\u0000\u0004\u0002{\u0014�G�p�@\u0002\u001cFranzbrötchen\u0002\u0000\u0002����"
}
{
  "topic": "orders_processed",
  "partition": 0,
  "offset": 2,
  "tstype": "create",
  "ts": 1604426116851,
  "key": "\u0000\u0000\u0000\u0002",
  "payload": "\u0000\u0000\u0000\u0001"
}
% Reached end of topic orders_processed [0] at offset 3
```

ksqlDB throws an error: 

```
ksql> PRINT orders_processed FROM BEGINNING;
Index 0 out of bounds for length 0
Topic printing ceased
ksql>
```

I think the final message (offset 2) is the problem, as previously printing the earlier messages worked (before the last message was added to the topic)

```
ksql> PRINT orders_processed;
Key format: KAFKA_INT or KAFKA_STRING
Value format: AVRO
rowtime: 2020/11/03 17:55:16.850 Z, key: 1, value: {"ORDER_TOTAL_USD": 12.34, "ITEM": "Cake", "CANCELLED_IND": false, "UPDATE_TS": 1604425257062}
rowtime: 2020/11/03 17:55:16.852 Z, key: 3, value: {"ORDER_TOTAL_USD": 910.11, "ITEM": "Franzbrötchen", "CANCELLED_IND": false, "UPDATE_TS": 1604425277524}
^CTopic printing ceased
ksql>
```

**Comment by agavra** [comment]
@rmoff the record payload seems malformed - the serializer expects a magic byte (0x00) then the schemaId (four bytes). The data in the second offset only has four bytes meaning that it can't deserialize it. If you check the logs, are there anything about serde errors?

**Comment by rmoff** [comment]
I've since torn down that environment so I don't have access to the logs, sorry. 

It was whilst researching [this blog](https://rmoff.net/2020/11/03/kafka-connect-ksqldb-and-kafka-tombstone-messages/) so I think the malformed (from an Avro point of view) payload was when I was writing values as `KAFKA` (ISTR writing the value `1`, might that fit?).

Either way, I agree that this just needs to be caught with error handling and not barf on printing the valid records. Although what is *valid* if we're just printing the topic contents without the user have instructed us to deserialise as Avro? Arguably ksqlDB should print all messages (even if it, for example, has to fall back on just writing the raw bytes for ones it can't deserialise using its assumed serde).

**Comment by theturtle32** [comment]
This just happened to me while trying to print a topic with avro-encoded messages. Here's the error output from the ksqldb-server log:

```[2020-12-05 06:27:20,909] ERROR Exception encountered while writing to output stream (io.confluent.ksql.rest.server.resources.streaming.TopicStreamWriter)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at io.confluent.ksql.rest.server.resources.streaming.RecordFormatter.format(RecordFormatter.java:116)
	at io.confluent.ksql.rest.server.resources.streaming.TopicStreamWriter.write(TopicStreamWriter.java:116)
	at io.confluent.ksql.api.server.OldApiUtils.lambda$streamEndpointResponse$3(OldApiUtils.java:133)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)```

Note:
* There is no subject defined in my schema registry of the format `{topic}-value` (this topic was written by a Ruby application using the avro_turf gem to interface with the schema registry, and there is no subject registered for the topic itself, just for the schema name/namespace)
* The ksqlDB server is actually configured to point to an empty schema registry.

My expectation is that it would not be able to find a schema for the avro messages in the empty schema registry and would just print the raw bytes, or at least print that there were messages with values of N bytes that it couldn't deserialize automatically.

**Comment by sheenacodes** [comment]
I am receiving this as well  `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 `

when attempting to print topic where key=null, value=avro formatted
Tried with a basic avro to check if it is the problem of avroschema but still same error. 
NO such error for topics with json formatted values
