### ISSUE TITLE
ksqlDB server + SSL is using the `keyStorePassword` as the `keyPassword`

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#6719]
**Describe the bug**
There are two kind of passwords when a user configures SSL environments using keystores. One is the keystore password that is used to decrypt the keystore file; another is the key password which is used to decrypt the private key obtained from the keystore. These configs are specified as `ssl.keystore.password` and `ssl.key.password` respectively. See an example here: https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#configuring-listener-for-ssl-encryption

Since 6.0, the ksqlDB does not configure the `ssl.key.password` correctly. It uses the same keystore password instead. This does not allow users to correctly configure SSL in ksqlDB servers because they might have different passwords for both the keystore and the private key.

**To Reproduce**
Use cp 6.0 and configure SSL from the example in https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#configuring-listener-for-ssl-encryption. Make sure to set `ssl.key.password` with a different password fro m`ssl.keystore.password`.

**Expected behavior**
ksqlDB should support the use of `ssl.key.password`.

**Actual behaviour**
ksqlDB requires the private key to have the same password as the keystore file.

**Additional context**
In `Server.java`, the `configureTlsKeyStore` is calling this method to configure SSL:
```
options.setKeyStoreOptions(new JksOptions().setValue(KeystoreUtil.getKeyStore(
            keyStoreType,
            keyStorePath,
            Optional.ofNullable(Strings.emptyToNull(keyStorePassword.value())),
            Optional.ofNullable(Strings.emptyToNull(keyStorePassword.value())),
            keyStoreAlias))
            .setPassword(keyStorePassword.value()));
```
Notice that it is passing the same `keyStorePassword` to the `getKeyStore` method, which should accept a keystore and a key password (different passwords).
```
public static Buffer getKeyStore(
      final String keyStoreType,
      final String keyStorePath,
      final Optional<String> keyStorePassword,
      final Optional<String> keyPassword,
      final String alias
  )
```

**Comment by spena** [comment]
@purplefox I was debugging this issue, and I found out that Vert.x does not support a keystore and private key having different passwords. Is that correct? There's no way to pass a different private key password? ksql only supports a single password for the keystore and private key?

I read on Stackoverflow and here (http://karim-ouda.blogspot.com/2010/07/errors-solutions-5.html) that the `Cannot recover key` is because the keystore and key have different passwords.

The error I get is:
```
2020-12-08 15:30:55,871] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:68)
io.confluent.ksql.rest.client.KsqlRestClientException: java.security.UnrecoverableKeyException: Cannot recover key
	at io.confluent.ksql.rest.client.KsqlClient.createHttpClient(KsqlClient.java:179)
	at io.confluent.ksql.rest.client.KsqlClient.<init>(KsqlClient.java:101)
	at io.confluent.ksql.rest.server.services.InternalKsqlClientFactory.createInternalClient(InternalKsqlClientFactory.java:50)
	at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(KsqlRestApplication.java:599)
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:161)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:61)
Caused by: io.vertx.core.VertxException: java.security.UnrecoverableKeyException: Cannot recover key
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:303)
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:478)
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:503)
	at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:133)
	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:319)
	at io.confluent.ksql.rest.client.KsqlClient.createHttpClient(KsqlClient.java:177)
	... 5 more
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:143)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:57)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:71)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at io.vertx.core.net.impl.KeyStoreHelper.<init>(KeyStoreHelper.java:164)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:84)
	at io.vertx.core.net.KeyCertOptions.getKeyManagerFactory(KeyCertOptions.java:53)
	at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:308)
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:253)
	... 10 more
```

I configured the ksql-server.properties this way:
```
# Keystore
ssl.keystore.location=ksql.client.keystore.jks
ssl.keystore.password=client1234
ssl.key.password=key1234
ssl.client.auth=true
ksql.ssl.keystore.alias.internal=localhost
```

I maded a change in the `InternalKsqlClientFactory` class to pass the key password, but it did not work.
```
final String suppliedKeyPassword = clientProps
                .get(SslConfigs.SSL_KEY_PASSWORD_CONFIG);
            keyStoreOptions.setValue(KeystoreUtil.getKeyStore(
                KsqlRestConfig.SSL_STORE_TYPE_JKS,
                keyStoreLocation,
                Optional.ofNullable(Strings.emptyToNull(suppliedKeyStorePassword)),
                Optional.ofNullable(Strings.emptyToNull(suppliedKeyPassword)),
                internalAlias));
```
