### ISSUE TITLE
Error registering AppInfo mbean

### ISSUE THREAD

**Issue by ssedrick** [confluentinc/ksql#6834]
**Describe the bug**
I get the following error whenever I try to run a CREATE statement:
```sh
[2021-01-05 19:33:03,106] WARN Error registering AppInfo mbean (org.apache.kafka.common.utils.AppInfoParser:68)
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=producer-default_
```
This does not happen when I do other commands like: `SHOW CONNECTORS;`, `SHOW TOPICS;`, `PRINT topic FROM BEGINNING`, etc.

**To Reproduce**
This occured with the 0.14.0 image on docker.

Running on Kubernetes with an MSK cluster:
<details><summary><strong>Kubernetes Yaml Manifest</strong></summary>
<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - env:
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_BOOTSTRAP_SERVERS
          value: broker-1.kafka.us-east-1.amazonaws.com:9092,broker-2.kafka.us-east-1.amazonaws.com:9092
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: http://schemas.kafka.svc
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        - name: KSQL_CONNECT_GROUP_ID
          value: ksql-connect-cluster
        - name: KSQL_CONNECT_BOOTSTRAP_SERVERS
          value: broker-2.kafka.us-east-1.amazonaws.com:9092,broker-1.kafka.us-east-1.amazonaws.com:9092
        - name: KSQL_CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.storage.StringConverter
        - name: KSQL_CONNECT_VALUE_CONVERTER
          value: io.confluent.connect.protobuf.ProtobufConverter
        - name: KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schemas.kafka.svc
        - name: KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schemas.kafka.svc
        - name: KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "true"
        - name: KSQL_CONNECT_CONFIG_STORAGE_TOPIC
          value: msk-connect-configs
        - name: KSQL_CONNECT_OFFSET_STORAGE_TOPIC
          value: msk-connect-offset
        - name: KSQL_CONNECT_STATUS_STORAGE_TOPIC
          value: msk-connect-status
        - name: KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "2"
        - name: KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "2"
        - name: KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "2"
        - name: KSQL_CONNECT_PLUGIN_PATH
          value: /opt/kafka/plugins
        - name: KSQL_CONNECT_REST_ADVERTISED_HOST_NAME
          value: ksqldb
        image: confluentinc/ksqldb-server:0.14.0
        imagePullPolicy: Always
        name: ksqldb
        ports:
        - containerPort: 8088
          protocol: TCP
</pre>
</details>

Once that is up and runninig, I port-forward `kubectl port-forward service/ksqldb 8089:80` and run the ksqldb-cli image locally with `docker exec -it ksqldb-cli ksql http://host.docker.internal:8089`

From there, executing the Show and PRINT work fine.
This, however, ends in an error:
 ![Screen Shot 2021-01-05 at 1 56 03 PM](https://user-images.githubusercontent.com/8585377/103692900-1606da00-4f5e-11eb-8e38-e63930412f9c.png)

**Expected behavior**
Tables and Streams to be created without error.

**Actual behaviour**
Once I hit enter, the cli hangs for ~1 minute, after which it gives the output below.
1. CLI output
![Screen Shot 2021-01-05 at 1 56 03 PM](https://user-images.githubusercontent.com/8585377/103692900-1606da00-4f5e-11eb-8e38-e63930412f9c.png)
2. KSQL logs

<details><summary>KSQL Logs Collapsed</summary>
<pre>
[2021-01-05 19:33:03,106] WARN Error registering AppInfo mbean (org.apache.kafka.common.utils.AppInfoParser:68)
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=producer-default_
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:433)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
	at io.confluent.ksql.rest.server.computation.CommandStore.createTransactionalProducer(CommandStore.java:299)
	at io.confluent.ksql.rest.server.computation.DistributingExecutor.execute(DistributingExecutor.java:127)
	at io.confluent.ksql.rest.server.execution.RequestHandler.lambda$executeStatement$0(RequestHandler.java:123)
	at io.confluent.ksql.rest.server.execution.RequestHandler.executeStatement(RequestHandler.java:126)
	at io.confluent.ksql.rest.server.execution.RequestHandler.execute(RequestHandler.java:100)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:275)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:164)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$22(KsqlServerEndpoints.java:302)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$21(KsqlServerEndpoints.java:288)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-01-05 19:33:03,106] WARN Error registering AppInfo mbean (org.apache.kafka.common.utils.AppInfoParser:68)
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=producer-default_
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:433)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
	at io.confluent.ksql.rest.server.computation.CommandStore.createTransactionalProducer(CommandStore.java:299)
	at io.confluent.ksql.rest.server.computation.DistributingExecutor.execute(DistributingExecutor.java:127)
	at io.confluent.ksql.rest.server.execution.RequestHandler.lambda$executeStatement$0(RequestHandler.java:123)
	at io.confluent.ksql.rest.server.execution.RequestHandler.executeStatement(RequestHandler.java:126)
	at io.confluent.ksql.rest.server.execution.RequestHandler.execute(RequestHandler.java:100)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:275)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:164)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$22(KsqlServerEndpoints.java:302)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$21(KsqlServerEndpoints.java:288)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-01-05 19:34:03,114] INFO Processed unsuccessfully: KsqlRequest{ksql='CREATE TABLE vz_subs (subId string PRIMARY KEY, firstName string, lastName string, email string) WITH (KAFKA_TOPIC='vz_subs', KEY_FORMAT='KAFKA', VALUE_FORMAT='JSON');', configOverrides={}, requestProperties={}, commandSequenceNumber=Optional[-1]}, reason: Timeout while initializing transaction to the KSQL command topic.
If you're running a single Kafka broker, ensure that the following configs are set to 1 on the broker:
- transaction.state.log.replication.factor
- transaction.state.log.min.isr
- offsets.topic.replication.factor (io.confluent.ksql.rest.server.resources.KsqlResource:301)
</pre>
</details>

**Additional context**
Zookeeper/brokers managed by AWS MSK. There are 2 brokers and 2 zookeepers.
Zookeeper and brokers allow for plaintext and TLS connection. In the example above, I am using plaintext.

**Comment by ssedrick** [comment]
I've added the config values from the logs:


<details><summary>KSQL Config Values</summary>
<pre>
[2021-01-05 19:31:09,218] INFO KsqlConfig values: 
	ksql.access.validator.enable = auto
	ksql.authorization.cache.expiry.time.secs = 30
	ksql.authorization.cache.max.entries = 10000
	ksql.cast.strings.preserve.nulls = true
	ksql.connect.url = http://localhost:8083
	ksql.connect.worker.config = /etc/ksqldb/connect.properties
	ksql.create.or.replace.enabled = true
	ksql.error.classifier.regex = 
	ksql.extension.dir = ext
	ksql.hidden.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
	ksql.insert.into.values.enabled = true
	ksql.internal.topic.min.insync.replicas = 1
	ksql.internal.topic.replicas = 1
	ksql.key.format.enabled = false
	ksql.metastore.backup.location = 
	ksql.metrics.extension = null
	ksql.metrics.tags.custom = 
	ksql.output.topic.name.prefix = 
	ksql.persistence.default.format.key = KAFKA
	ksql.persistence.default.format.value = null
	ksql.persistence.wrap.single.values = null
	ksql.persistent.prefix = query_
	ksql.properties.overrides.denylist = []
	ksql.pull.queries.enable = true
	ksql.query.error.max.queue.size = 10
	ksql.query.persistent.active.limit = 2147483647
	ksql.query.pull.enable.standby.reads = false
	ksql.query.pull.max.allowed.offset.lag = 9223372036854775807
	ksql.query.pull.max.qps = 2147483647
	ksql.query.pull.metrics.enabled = false
	ksql.query.pull.thread.pool.size = 100
	ksql.query.retry.backoff.initial.ms = 15000
	ksql.query.retry.backoff.max.ms = 900000
	ksql.query.status.running.threshold.seconds = 300
	ksql.readonly.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
	ksql.schema.registry.url = http://schemas.kafka.svc
	ksql.security.extension.class = null
	ksql.service.id = default_
	ksql.sink.window.change.log.additional.retention = 1000000
	ksql.streams.shutdown.timeout.ms = 300000
	ksql.suppress.buffer.size.bytes = -1
	ksql.suppress.enabled = false
	ksql.timestamp.throw.on.invalid = false
	ksql.transient.prefix = transient_
	ksql.udf.collect.metrics = false
	ksql.udf.enable.security.manager = true
	ksql.udfs.enabled = true
	ksql.variable.substitution.enable = true
	metric.reporters = []
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
 (io.confluent.ksql.util.KsqlConfig:354)
 </pre>
 </details>
 <details><summary>KSQL Rest Configs</summary>
 <pre>
[2021-01-05 19:31:09,275] INFO KsqlRestConfig values: 
	access.control.allow.headers = []
	access.control.allow.methods = []
	access.control.allow.origin = 
	authentication.method = NONE
	authentication.realm = 
	authentication.roles = [*]
	authentication.skip.paths = []
	ksql.advertised.listener = null
	ksql.authentication.plugin.class = null
	ksql.healthcheck.interval.ms = 5000
	ksql.heartbeat.check.interval.ms = 200
	ksql.heartbeat.discover.interval.ms = 2000
	ksql.heartbeat.enable = false
	ksql.heartbeat.missed.threshold.ms = 3
	ksql.heartbeat.send.interval.ms = 100
	ksql.heartbeat.thread.pool.size = 3
	ksql.heartbeat.window.ms = 2000
	ksql.internal.listener = null
	ksql.internal.ssl.client.authentication = NONE
	ksql.lag.reporting.enable = false
	ksql.lag.reporting.send.interval.ms = 5000
	ksql.max.push.queries = 100
	ksql.server.command.blocked.threshold.error.ms = 15000
	ksql.server.command.response.timeout.ms = 5000
	ksql.server.error.messages = class io.confluent.ksql.rest.DefaultErrorMessages
	ksql.server.exception.uncaught.handler.enable = false
	ksql.server.install.dir = /usr
	ksql.server.preconditions = []
	ksql.server.websockets.num.threads = 5
	ksql.ssl.keystore.alias.external = 
	ksql.ssl.keystore.alias.internal = 
	ksql.verticle.instances = 2
	ksql.worker.pool.size = 100
	listeners = [http://0.0.0.0:8088]
	query.stream.disconnect.check = 1000
	ssl.cipher.suites = []
	ssl.client.auth = false
	ssl.client.authentication = NONE
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.keystore.location = 
	ssl.keystore.password = [hidden]
	ssl.keystore.reload = false
	ssl.keystore.type = JKS
	ssl.keystore.watch.location = 
	ssl.truststore.location = 
	ssl.truststore.password = [hidden]
	ssl.truststore.type = JKS
 (io.confluent.ksql.rest.server.KsqlRestConfig:354)
 </pre>
 </details>

**Comment by stevenpyzhang** [comment]
@ssedrick I'm not sure those logs are the real issue with why the `CREATE TABLE` statement is failing. The command fails to be produced to the command topic during initializing the transaction for some reason. Would you mind posting the server properties you're running with on your Kafka brokers?

**Comment by ssedrick** [comment]
@stevenpyzhang In this case the brokers are managed by AWS MSK and the [default configuration](https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html).

Should be something like this:
<details><summary>Default Configs</summary>
<pre>
allow.everyone.if.no.acl.found=true
auto.create.topics.enable=false
auto.leader.rebalance.enable=true
default.replication.factor=3
min.insync.replicas=2
num.io.threads=8
num.network.threads=5
num.partitions=1
num.replica.fetchers=2
replica.lag.time.max.ms=30000
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
unclean.leader.election.enable=true
zookeeper.session.timeout.ms=18000
zookeeper.set.acl=false
</pre>
</details>

**Comment by stevenpyzhang** [comment]
Is there any way to update the broker configs so that `transaction.state.log.replication.factor=2` and `offsets.topic.replication.factor=2`

The default value is 3 for the configs 
https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#transaction.state.log.replication.factor
https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#offsets.topic.replication.factor

I believe this causing the KSQL server to fail the transactional produce to the KSQL internal topic since there are only 2 brokers currently. Alternatively, I think adding another broker to the cluster would address the problem since the default configs would match up then.

**Comment by ssedrick** [comment]
@stevenpyzhang That did it, thank you so much for your help!

**Comment by ramyavenu86** [comment]
@ssedrick  Am also running into the same issue. Running AWS  MSK with 2 brokers. Did you end up adding 3 brokers or changed the setting in MSK?
