### ISSUE TITLE
Include ksqldb-rocksdb-config-setter jar in distributed artifacts

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/ksql#6838]
The [How to Limit Memory Usage in ksqlDB](https://www.confluent.io/blog/bounding-ksqldb-memory-usage/) blog post details the use of `KsqlBoundedMemoryRocksDBConfigSetter`, but the containing jar is not on the classpath – nor included at all in releases, including the standalone Docker image.

This yields the following when the custom config setter is otherwise correctly configured:
```
org.apache.kafka.common.config.ConfigException: Invalid value io.confluent.ksql.rocksdb.KsqlBoundedMemoryRocksDBConfigSetter for configuration rocksdb.config.setter: Class io.confluent.ksql.rocksdb.KsqlBoundedMemoryRocksDBConfigSetter could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:729)
	at io.confluent.ksql.config.ConfigItem$Resolved.parseValue(ConfigItem.java:125)
	at io.confluent.ksql.util.KsqlConfig.lambda$resolveStreamsConfig$2(KsqlConfig.java:902)
	at java.base/java.util.Optional.map(Optional.java:265)
```

At minimum, we should ensure that the `ksqldb-rocksdb-config-setter` jar is included in distributed artifacts. We should consider altering `ksql-run-class` to automatically add it to the classpath.

As a workaround, users of the standalone Docker image would need to build the `ksqldb-rocksdb-config-setter` jar at the release version, mount it in the container, and ensure it is added to the classpath.

**Comment by vcrfxia** [comment]
There's another workaround documented in https://github.com/confluentinc/ksql/issues/6644: besides building the config setter module themselves, users can copy the jar from our maven repo.

**Comment by vcrfxia** [comment]
@wcarlson5 should this be labeled for 0.18?

**Comment by ChenZhaobin** [comment]
specifically ,how to alter ksql-run-class in order to use ksqldb-rocksdb-config-setter?

**Comment by ChenZhaobin** [comment]
I download jar here :
https://ksqldb-maven.s3-us-west-2.amazonaws.com/maven/io/confluent/ksql/ksql-rocksdb-config-setter/0.7.1/ksql-rocksdb-config-setter-0.7.1.jar 

it  works when I put it in dir /ksqldb/customclass
and then `vi /ksql-run-class` ,add one line ` KSQL_CLASSPATH="/ksqldb/customclass/*:$KSQL_CLASSPATH"`

**Comment by dberardo-com** [comment]
by the way do you know the difference between these two configs ? 

```
ksql.plugins.rocksdb.cache.size=<desired memory bound>
ksql.plugins.rocksdb.cache.limit.strict=<desired memory bound>
```

ref: https://github.com/confluentinc/ksql/blob/0.28.2-ksqldb/ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfig.java
