### ISSUE TITLE
An NPE while backing the metadata causes KSQL fail to start

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#7184]
**Describe the bug**
If a null key or value is being written to the command topic, then the backup process will fail with an NPE causing the KSQL to stop working. 

This is the stack trace of the NPE:
```
java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:341)
	at io.confluent.ksql.rest.server.BackupReplayFile.write(BackupReplayFile.java:87)
	at io.confluent.ksql.rest.server.CommandTopicBackupImpl.writeRecord(CommandTopicBackupImpl.java:150)
	at io.confluent.ksql.rest.server.CommandTopic.backupRecord(CommandTopic.java:159)
	at io.confluent.ksql.rest.server.CommandTopic.getRestoreCommands(CommandTopic.java:117)
	at io.confluent.ksql.rest.server.computation.CommandStore.getRestoreCommands(CommandStore.java:268)
	at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:254)
	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:459)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:385)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:367)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:89)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:64)
```

**To Reproduce**
KSQL version is `0.15`
Steps to reproduce TBD

**Expected behavior**
The KSQL server should not stop working. The backups should be marked as degradation so a warning is displayed to the user.

**Comment by vcrfxia** [comment]
root cause + add logging.

**Comment by spena** [comment]
I couldn't find the root cause of this null key in the command topic. The logs do not contain any new commands sent by the user. The Kafka logs does not include records written either. This could be probably caused by a producer used by the user to write directly to the command topic, thus causing the server to crash.
