### ISSUE TITLE
NPE is displayed in the `ksql-migrations create` action

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#7196]
**Describe the bug**
A NPE exception is displayed in the `ksql-migrations create` if no configuration file is specified.

**To Reproduce**
```
./ksql-migrations create 1 Setup
Exception in thread "main" java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at io.confluent.ksql.tools.migrations.util.MigrationsDirectoryUtil.getMigrationsDirFromConfigFile(MigrationsDirectoryUtil.java:50)
	at io.confluent.ksql.tools.migrations.commands.CreateMigrationCommand.command(CreateMigrationCommand.java:73)
	at io.confluent.ksql.tools.migrations.commands.BaseCommand.runCommand(BaseCommand.java:79)
	at io.confluent.ksql.tools.migrations.Migrations.main(Migrations.java:101)
```

**Expected behavior**
A message specifying the required parameters for the `create` action. For instance:
```
./ksql-migrations create 1 Setup
Required arguments are missing: 'config-file'
```

**Comment by vcrfxia** [comment]
This is fixed by https://github.com/confluentinc/ksql/pull/7195
