### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [confluentinc/ksql#7413]
[jw@cn05 ksqldb]$ ./mvnw clean package -DskipTests -DversionFilter
...
[INFO] ksqldb-version-metrics-client ...................... SUCCESS [ 39.920 s]
[INFO] ksqldb-rest-app .................................... FAILURE [  3.612 s]
[INFO] ksqldb-api-client .................................. SKIPPED
[INFO] ksqldb-tools ....................................... SKIPPED
[INFO] ksqldb-cli ......................................... SKIPPED
[INFO] ksqldb-examples .................................... SKIPPED
[INFO] ksqldb-console-scripts ............................. SKIPPED
[INFO] ksqldb-etc ......................................... SKIPPED
[INFO] ksqldb-functional-tests ............................ SKIPPED
[INFO] ksqldb-package ..................................... SKIPPED
[INFO] ksqldb-benchmark ................................... SKIPPED
[INFO] ksqlDB RocksDB Config Setter ....................... SKIPPED
[INFO] ksqldb-docker ...................................... SKIPPED
[INFO] ksqldb-api-reactive-streams-tck .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:10 min
[INFO] Finished at: 2021-04-21T09:31:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ksqldb-rest-app: Could not resolve dependencies for project io.confluent.ksql:ksqldb-rest-app:jar:7.0.0-0: Could not find artifact io.confluent:confluent-log4j-extensions:jar:7.0.0-282 in confluent (https://packages.confluent.io/maven/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ksqldb-rest-app
[jw@cn05 ksqldb]$

**Comment by ableegoldman** [comment]
Hey @LutzWeischerFujitsu , based on the error message I'm guessing you're trying to build from master? You should generally be using one of the `-post` branches as these correspond to released versions, for example the latest one right now is `6.1.1-post`. The `master` branch is not guaranteed to be stable since it is by definition the development branch.

Are you trying to build from master specifically? I recall someone else had a similar issue, but it seems to have resolved itself for them: https://forum.confluent.io/t/ksqldb-compilation-is-failing/1267

**Comment by LutzWeischerFujitsu** [comment]
I'm intentionally trying the master to be able to report "unintentional Intel-isms". 
I tried the recommended 'mvn install -DskipTests -Dspotbugs.skip=true' and it works. Trying '[jw@cn05 ksqldb]$ mvn install -Dspotbugs.skip=true' starts failing with 

...
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ ksqldb-common ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.confluent.ksql.util.RetryUtilTest
[2021-04-28 08:23:58,430] ERROR Exception encountered running command: error. Retrying in 1 ms (io.confluent.ksql.util.RetryUtil:106)
[2021-04-28 08:23:58,438] ERROR Stack trace: java.lang.RuntimeException: error
        at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:89)
        at io.confluent.ksql.util.RetryUtilTest.lambda$shouldRespectStopRetrying$4(RetryUtilTest.java:100)
        at org.junit.Assert.assertThrows(Assert.java:1001)
        at org.junit.Assert.assertThrows(Assert.java:981)
        at io.confluent.ksql.util.RetryUtilTest.shouldRespectStopRetrying(RetryUtilTest.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
 (io.confluent.ksql.util.RetryUtil:110)
[2021-04-28 08:23:58,448] ERROR Exception encountered running command: error. Retrying in 2 ms (io.confluent.ksql.util.RetryUtil:106)
[2021-04-28 08:23:58,449] ERROR Stack trace: java.lang.RuntimeException: error
        at io.confluent.ksql.util.RetryUtil.retryWithBackoff(RetryUtil.java:89)
        at io.confluent.ksql.util.RetryUtilTest.lambda$shouldRespectStopRetrying$4(RetryUtilTest.java:100)
        at org.junit.Assert.assertThrows(Assert.java:1001)
        at org.junit.Assert.assertThrows(Assert.java:981)
        at io.confluent.ksql.util.RetryUtilTest.shouldRespectStopRetrying(RetryUtilTest.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
 (io.confluent.ksql.util.RetryUtil:110)
[2021-04-28 08:23:58,453] INFO Stopping retries (io.confluent.ksql.util.RetryUtil:117)
...

Java 11, no JAVA_HOME. Java 1.8 fails, too. Setting JAVA_HOME does not change the situation.

**Comment by msillence** [comment]
I see the same problem with missing io.confluent:confluent-log4j-extensions:jar:7.0.0-510

I don't see any published 7.x versions of the artifact either https://mvnrepository.com/artifact/io.confluent/confluent-log4j-extensions or directly https://packages.confluent.io/maven/io/confluent/confluent-log4j-extensions/
