### ISSUE TITLE
Client.executeQuery DecodeException

### ISSUE THREAD

**Issue by uqix** [confluentinc/ksql#7691]
**Describe the bug**
`Client.executeQuery` results in exception:
```
io.vertx.core.json.DecodeException: Failed to decode:Cannot deserialize instance of java.util.ArrayList<java.lang.Object> out of START_OBJECT token
```

**To Reproduce**
Steps to reproduce the behavior, include:
1. ksqldb-api-client v0.18.0
2. Any SQL statements you ran: `SELECT * FROM demo_truck_location_invalid_alert WHERE truck_id = 2;`

**Expected behavior**
`Client.executeQuery` returns a list of rows without error.

**Actual behaviour**

```
io.vertx.core.json.DecodeException: Failed to decode:Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]] with root cause	 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:336)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:269)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4497)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2730)
	at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
	at io.vertx.core.json.jackson.JacksonCodec.fromBuffer(JacksonCodec.java:67)
	at io.vertx.core.json.JsonArray.fromBuffer(JsonArray.java:849)
	at io.vertx.core.json.JsonArray.<init>(JsonArray.java:88)
	at io.confluent.ksql.api.client.impl.ExecuteQueryResponseHandler.handleRow(ExecuteQueryResponseHandler.java:64)
	at io.confluent.ksql.api.client.impl.QueryResponseHandler.doHandleBodyBuffer(QueryResponseHandler.java:41)
	at io.confluent.ksql.api.client.impl.ResponseHandler.handleBodyBuffer(ResponseHandler.java:39)
	at io.confluent.ksql.api.client.impl.ExecuteQueryResponseHandler.handleBodyBuffer(ExecuteQueryResponseHandler.java:34)
	at io.vertx.core.parsetools.impl.RecordParserImpl.handleParsing(RecordParserImpl.java:214)
	at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:285)
	at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:27)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:232)
	at io.vertx.core.http.impl.Http2ClientConnection$Http2ClientStream.handleData(Http2ClientConnection.java:265)
	at io.vertx.core.http.impl.VertxHttp2Stream.lambda$new$1(VertxHttp2Stream.java:72)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.http.impl.VertxHttp2Stream.onDataRead(VertxHttp2Stream.java:85)
	at io.vertx.core.http.impl.Http2ConnectionBase.lambda$onDataRead$9(Http2ConnectionBase.java:328)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
```

**Additional context**
It did work once, while the query works perfectly in CLI as in screenshot:
![image](https://user-images.githubusercontent.com/10142314/122400940-c0276b00-cfae-11eb-90e7-3cbd52161ac5.png)

**Comment by uqix** [comment]
This error occurs when pull query and push query running at the same time with the same `Client`,
it seems that `Client` is not thread-safe so that reusing it is not possible, related with issue #7684.
