### ISSUE TITLE
ksqldb fails on macbook with M1 processor

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7908]
**Describe the bug**
ksqldb 0.19.0 fails on macbook with M1 processor with a following error:

```
[2021-07-28 11:50:57,688] INFO Started @22177ms (org.eclipse.jetty.server.Server:415)

[2021-07-28 11:50:58,952] ERROR Unhandled exception in server startup (io.confluent.ksql.rest.server.KsqlServerMain:96)

java.lang.ExceptionInInitializerError

at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:175)

at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)

at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)

at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

at org.apache.kafka.connect.runtime.rest.RestServer.initializeResources(RestServer.java:306)

at org.apache.kafka.connect.runtime.Connect.start(Connect.java:55)

at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:140)

at io.confluent.ksql.rest.server.ConnectExecutable.startAsync(ConnectExecutable.java:58)

at io.confluent.ksql.rest.server.MultiExecutable.doAction(MultiExecutable.java:68)

at io.confluent.ksql.rest.server.MultiExecutable.startAsync(MultiExecutable.java:42)

at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:92)

at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:67)

Caused by: java.nio.charset.IllegalCharsetNameException: l;charset=iso-8859-1

at java.base/java.nio.charset.Charset.checkName(Charset.java:308)

at java.base/java.nio.charset.Charset.lookup2(Charset.java:482)

at java.base/java.nio.charset.Charset.lookup(Charset.java:462)

at java.base/java.nio.charset.Charset.forName(Charset.java:526)

at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:107)

at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:67)

... 12 more

```

It seems that the real issue has something to do with jetty, maybe update would fix it ? Or maybe it's some java version incompatibility. In addition, I'm experiencing the same errors with schema registry. 

**To Reproduce**
Run ksqldb on M1 mac with kafka connect cluster. If run without kafka connect, everything seems to be fine.

**Expected behavior**
ksqldb starts up without errors

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
2. Error messages
3. KSQL logs

**Additional context**

**Comment by maksymilian-gasztych** [comment]
Ill gather some more data and reopen

**Comment by maksymilian-gasztych** [comment]
I have found this ticket just now, it seems that until this is closed, ksqldb, and in particular, embedded  kafka connect won't run on apple silicon, am I right ? https://github.com/confluentinc/common-docker/issues/117

**Comment by madukan** [comment]
I have to start and stop a few times to get it working. But then again it doesn't save the data properly, and I have to re-install complete docker compose stack again.
