### ISSUE TITLE
Replication factor does not seem to be preserved for the internal changelog topic for transient queries

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#815]
It appears that the internal changelog topic which is create to execute queries like `SELECT * from some_table` doesn't respect the `ksql.sink.replicas` property value.

In the following, the `ksql.sink.replicas` is set to `3`.

We have a topic `SYSLOG_BY_NODENAME_ALL` keyed by the field `nodename` and with the following properties:
```
Topic:SYSLOG_BY_NODENAME_ALL    PartitionCount:4        ReplicationFactor:3     Configs:
        Topic: SYSLOG_BY_NODENAME_ALL   Partition: 0    Leader: 0       Replicas: 0,1,2 Isr: 0,1,2
        Topic: SYSLOG_BY_NODENAME_ALL   Partition: 1    Leader: 1       Replicas: 1,2,0 Isr: 1,2,0
        Topic: SYSLOG_BY_NODENAME_ALL   Partition: 2    Leader: 2       Replicas: 2,0,1 Isr: 2,0,1
        Topic: SYSLOG_BY_NODENAME_ALL   Partition: 3    Leader: 0       Replicas: 0,2,1 Isr: 0,2,1
```

We now create a table `nodes` from this topic and then execute a `SELECT * from nodes;`. The output is below:
```sql
> CREATE TABLE nodes (nodename varchar, meta varchar, k8sid varchar) WITH (kafka_topic='SYSLOG_BY_NODENAME_ALL', value_format='JSON');
Stream created and running. 
> SHOW TABLES;
 Name       | Topic                  | Format | IsWindowed 
-----------------------------------------------------------
 NODES      | SYSLOG_BY_NODENAME_ALL | JSON   | false      
> select * from nodes;
<nothing>
```

From the server log we see:
```
[2018-02-27 22:59:50,791] INFO Streaming query 'select * from nodes;' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:73)
[2018-02-27 22:59:59,794] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:105)
org.apache.kafka.streams.errors.StreamsException: Could not create topic ksql_transient_4505922072288888046_1519772390764-KSTREAM-REDUCE-STATE-STORE-0000000003-changelog.
        at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:137)
        at org.apache.kafka.streams.processor.internals.StreamPartitionAssignor.prepareTopic(StreamPartitionAssignor.java:655)
        at org.apache.kafka.streams.processor.internals.StreamPartitionAssignor.assign(StreamPartitionAssignor.java:463)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.performAssignment(ConsumerCoordinator.java:358)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.onJoinLeader(AbstractCoordinator.java:520)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.access$1100(AbstractCoordinator.java:93)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:472)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:455)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:814)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:794)
        at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:510)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:356)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:217)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:177)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:364)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:316)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:290)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1149)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
        at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:833)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:790)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:756)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:726)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Topic replication factor must be 3
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:258)
        at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:121)
        ... 26 more
Caused by: org.apache.kafka.common.errors.PolicyViolationException: Topic replication factor must be 3
```

Our environment requires every topic to have a `replication.factor = 3`. It seems that the changelog topic for the transient query tries to create a topic with `replication.factor = 1` and thus fails.  

If we do a CTAS query to create a copy of `nodes`, it creates a topic with the right replication factor.

```sql
> CREATE TABLE nodes_copy as SELECT * from nodes;
Table created
```

The replication factor for the `NODES_COPY` topic is correct:
```
Topic:NODES_COPY        PartitionCount:4        ReplicationFactor:3     Configs:
        Topic: NODES_COPY       Partition: 0    Leader: 1       Replicas: 1,2,0 Isr: 1,2,0
        Topic: NODES_COPY       Partition: 1    Leader: 2       Replicas: 2,0,1 Isr: 2,0,1
        Topic: NODES_COPY       Partition: 2    Leader: 0       Replicas: 0,1,2 Isr: 0,1,2
        Topic: NODES_COPY       Partition: 3    Leader: 1       Replicas: 1,0,2 Isr: 1,0,2
```

We should ensure that the `ksql.sink.replicas` property is respected even for the changelog topics created for transient queries. I have not tested, but this may also be a problem for repartition topics created for transient queries.

**Comment by apurvam** [comment]
The problem is that `replication.factor` property when specified in the `ksql.properties` file does not get passed on to the streams config. Hence the streams application uses `replication.factor = 1` for internal topics, causing the above error. If we do a `set 'replication.factor'='3'` in the CLI, then the `select * from node;` query works just fine. 

I will file a separate issue to track why the streams properties specified in the `ksql.properties` file does not get propagated to the streams application. For things like this where the underlying kafka cluster requires certain configuration values, we would want to be able to specify it in the KSQL server config and not explicitly for each query.
