### ISSUE TITLE
Variable substitution for ksql-migrations doesn't work

### ISSUE THREAD

**Issue by DmytroMelnyk** [confluentinc/ksql#8317]
**Describe the bug**
ksql-migrations tool doesn't recognize variables.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL: 
ksqldb-cli: 0.19-0.21
cp-ksqldb-server:6.2.1
2. Sample source data: 
Follow [this manual](https://www.confluent.io/blog/easily-manage-database-migrations-with-evolving-schemas-in-ksqldb/) till: _Open this file and add the following command_

and change recommended script to:
`CREATE STREAM ${STREAMNAME} (
  orderid STRING, 
  name STRING, 
  items ARRAY<STRING>,
  cost DECIMAL(6, 2),
  ordertime TIMESTAMP
) WITH (
  kafka_topic='order_event', 
  partitions=1,
  value_format='json'
);`

3. run:
`ksql-migrations apply -a -c orders/ksql-migrations.properties -d STREAMNAME=ORDER_EVENTS`

**Expected behavior**
Stream ORDER_EVENTS should be created

**Actual behaviour**
I get the following output in the console:

`Validating current migration state before applying new migrations
Loading migration files
1 migration file(s) loaded.
Applying migration version 1: initialize order events stream
/orders/migrations/V000001__initialize_order_events_stream.sql contents:
CREATE STREAM ${streamName} (
  orderid STRING,
  name STRING,
  items ARRAY<STRING>,
  cost DECIMAL(6, 2),
  ordertime TIMESTAMP
) WITH (
  kafka_topic='order_event',
  partitions=1,
  value_format='json'
);
Failed to execute sql: CREATE STREAM ${streamName} (
  orderid STRING,
  name STRING,
  items ARRAY<STRING>,
  cost DECIMAL(6, 2),
  ordertime TIMESTAMP
) WITH (
  kafka_topic='order_event',
  partitions=1,
  value_format='json'
);. Error: io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: Illegal argument at Line: 1, Col: 15. Source names may only contain alphanumeric values, '_' or '-'. Got: '${STREAMNAME}'. Error code: 40001
Execution time: 1.1490 seconds`

**Comment by jzaralim** [comment]
@DmytroMelnyk  in order for variable substitution to work, both the migration tool and the server need to be versions 0.18/7.0 or newer.

**Comment by DmytroMelnyk** [comment]
For ksqldb/ksqldb-cli 0.19 I've got this error:
![image](https://user-images.githubusercontent.com/10696604/140379498-31fe1c04-2daf-4d1c-96fd-c5597e91c2fb.png)

For ksqldb/ksqldb-cli 0.20-0.21 I've got this error:
![image](https://user-images.githubusercontent.com/10696604/140380256-4f94e01d-ce33-4f6c-be6c-66e37ede5e77.png)

**Comment by DmytroMelnyk** [comment]
@jzaralim should I create the new ticket?

**Comment by jzaralim** [comment]
@DmytroMelnyk do you have any logs? And how are you running ksqlDB?

**Comment by DmytroMelnyk** [comment]
Logs from ksqldb:
`[2021-11-04 16:56:52,922] INFO Processed successfully: KsqlRequest{ksql='CREATE TABLE MIGRATION_SCHEMA_VERSIONS


  WITH (


    KAFKA_TOPIC='ksql-service-idksql_MIGRATION_SCHEMA_VERSIONS'


  )


  AS SELECT 


    version_key, 


    latest_by_offset(version) as version, 


    latest_by_offset(name) AS name, 


    latest_by_offset(state) AS state,     


    latest_by_offset(checksum) AS checksum, 


    latest_by_offset(started_on) AS started_on, 


    latest_by_offset(completed_on) AS completed_on, 


    latest_by_offset(previous) AS previous, 


    latest_by_offset(error_reason) AS error_reason 


  FROM MIGRATION_EVENTS 


  GROUP BY version_key;


', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:316)


[2021-11-04 16:56:52,922] INFO Executed statement: CREATE TABLE MIGRATION_SCHEMA_VERSIONS WITH (KAFKA_TOPIC='ksql-service-idksql_MIGRATION_SCHEMA_VERSIONS', PARTITIONS=1, REPLICAS=1) AS SELECT


  MIGRATION_EVENTS.VERSION_KEY VERSION_KEY,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.VERSION) VERSION,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.NAME) NAME,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.STATE) STATE,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.CHECKSUM) CHECKSUM,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.STARTED_ON) STARTED_ON,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.COMPLETED_ON) COMPLETED_ON,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.PREVIOUS) PREVIOUS,


  LATEST_BY_OFFSET(MIGRATION_EVENTS.ERROR_REASON) ERROR_REASON


FROM MIGRATION_EVENTS MIGRATION_EVENTS


GROUP BY MIGRATION_EVENTS.VERSION_KEY


EMIT CHANGES; (io.confluent.ksql.rest.server.computation.CommandRunner:346)


[2021-11-04 16:56:52,929] INFO 192.168.208.1 - - [Thu, 4 Nov 2021 16:56:52 GMT] "POST /ksql HTTP/2.0" 200 1033 "-" "-" 635 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:56:53,200] INFO 192.168.208.5 - - [Thu, 4 Nov 2021 16:56:53 GMT] "GET /info HTTP/2.0" 200 133 "-" "armeria/1.7.2" 0 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:09,423] INFO 192.168.208.5 - - [Thu, 4 Nov 2021 16:57:09 GMT] "GET /info HTTP/2.0" 200 133 "-" "armeria/1.7.2" 0 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:22,122] INFO 192.168.208.1 - - [Thu, 4 Nov 2021 16:57:22 GMT] "GET /info HTTP/2.0" 200 133 "-" "-" 0 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:22,198] INFO Received: KsqlRequest{ksql='describe MIGRATION_EVENTS;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:262)


[2021-11-04 16:57:22,230] INFO Processed successfully: KsqlRequest{ksql='describe MIGRATION_EVENTS;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:316)


[2021-11-04 16:57:22,246] INFO 192.168.208.1 - - [Thu, 4 Nov 2021 16:57:22 GMT] "POST /ksql HTTP/2.0" 200 1604 "-" "-" 59 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:22,260] INFO Received: KsqlRequest{ksql='describe MIGRATION_SCHEMA_VERSIONS;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:262)


[2021-11-04 16:57:22,286] INFO Processed successfully: KsqlRequest{ksql='describe MIGRATION_SCHEMA_VERSIONS;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:316)


[2021-11-04 16:57:22,293] INFO 192.168.208.1 - - [Thu, 4 Nov 2021 16:57:22 GMT] "POST /ksql HTTP/2.0" 200 2023 "-" "-" 68 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:22,352] ERROR Failure to execute pull query. RoutingOptions{maxOffsetLagAllowed: 9223372036854775807, isSkipForwardRequest: false, isDebugRequest: false, partitions: []} QueryPlannerOptions{tableScansEnabled: false, interpreterEnabled: true} (io.confluent.ksql.engine.EngineExecutor:248)


io.confluent.ksql.util.KsqlException: The `MIGRATION_SCHEMA_VERSIONS` table isn't queryable. To derive a queryable table, you can do 'CREATE TABLE QUERYABLE_MIGRATION_SCHEMA_VERSIONS AS SELECT * FROM MIGRATION_SCHEMA_VERSIONS'. See https://cnfl.io/queries for more info.


Add EMIT CHANGES if you intended to issue a push query.


	at io.confluent.ksql.engine.PullQueryExecutionUtil.notMaterializedException(PullQueryExecutionUtil.java:79)


	at io.confluent.ksql.engine.PullQueryExecutionUtil.findMaterializingQuery(PullQueryExecutionUtil.java:59)


	at io.confluent.ksql.engine.EngineExecutor.buildPullPhysicalPlan(EngineExecutor.java:483)


	at io.confluent.ksql.engine.EngineExecutor.executePullQuery(EngineExecutor.java:198)


	at io.confluent.ksql.engine.KsqlEngine.executePullQuery(KsqlEngine.java:317)


	at io.confluent.ksql.api.impl.QueryEndpoint.createPullQueryPublisher(QueryEndpoint.java:249)


	at io.confluent.ksql.api.impl.QueryEndpoint.createQueryPublisher(QueryEndpoint.java:136)


	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$createQueryPublisher$0(KsqlServerEndpoints.java:169)


	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:344)


	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)


	at java.base/java.lang.Thread.run(Thread.java:829)


[2021-11-04 16:57:22,355] ERROR Failed to execute query (io.confluent.ksql.api.server.ServerUtils:115)


io.confluent.ksql.util.KsqlStatementException: The `MIGRATION_SCHEMA_VERSIONS` table isn't queryable. To derive a queryable table, you can do 'CREATE TABLE QUERYABLE_MIGRATION_SCHEMA_VERSIONS AS SELECT * FROM MIGRATION_SCHEMA_VERSIONS'. See https://cnfl.io/queries for more info.


Add EMIT CHANGES if you intended to issue a push query.


Statement: SELECT VERSION FROM MIGRATION_SCHEMA_VERSIONS WHERE version_key = 'CURRENT';


	at io.confluent.ksql.engine.EngineExecutor.executePullQuery(EngineExecutor.java:259)


	at io.confluent.ksql.engine.KsqlEngine.executePullQuery(KsqlEngine.java:317)


	at io.confluent.ksql.api.impl.QueryEndpoint.createPullQueryPublisher(QueryEndpoint.java:249)


	at io.confluent.ksql.api.impl.QueryEndpoint.createQueryPublisher(QueryEndpoint.java:136)


	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$createQueryPublisher$0(KsqlServerEndpoints.java:169)


	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:344)


	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)


	at java.base/java.lang.Thread.run(Thread.java:829)


Caused by: io.confluent.ksql.util.KsqlException: The `MIGRATION_SCHEMA_VERSIONS` table isn't queryable. To derive a queryable table, you can do 'CREATE TABLE QUERYABLE_MIGRATION_SCHEMA_VERSIONS AS SELECT * FROM MIGRATION_SCHEMA_VERSIONS'. See https://cnfl.io/queries for more info.


Add EMIT CHANGES if you intended to issue a push query.


	at io.confluent.ksql.engine.PullQueryExecutionUtil.notMaterializedException(PullQueryExecutionUtil.java:79)


	at io.confluent.ksql.engine.PullQueryExecutionUtil.findMaterializingQuery(PullQueryExecutionUtil.java:59)


	at io.confluent.ksql.engine.EngineExecutor.buildPullPhysicalPlan(EngineExecutor.java:483)


	at io.confluent.ksql.engine.EngineExecutor.executePullQuery(EngineExecutor.java:198)


	... 10 more


[2021-11-04 16:57:22,356] ERROR Failed to handle request 400 /query-stream (io.confluent.ksql.api.server.FailureHandler:38)


io.confluent.ksql.api.server.KsqlApiException: The `MIGRATION_SCHEMA_VERSIONS` table isn't queryable. To derive a queryable table, you can do 'CREATE TABLE QUERYABLE_MIGRATION_SCHEMA_VERSIONS AS SELECT * FROM MIGRATION_SCHEMA_VERSIONS'. See https://cnfl.io/queries for more info.


Add EMIT CHANGES if you intended to issue a push query.


Statement: SELECT VERSION FROM MIGRATION_SCHEMA_VERSIONS WHERE version_key = 'CURRENT';


	at io.confluent.ksql.api.server.ServerUtils.handleEndpointException(ServerUtils.java:118)


	at io.confluent.ksql.api.server.QueryStreamHandler.lambda$handle$4(QueryStreamHandler.java:137)


	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)


	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)


	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)


	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)


	at io.confluent.ksql.util.VertxCompletableFuture.handle(VertxCompletableFuture.java:37)


	at io.confluent.ksql.util.VertxCompletableFuture.handle(VertxCompletableFuture.java:26)


	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)


	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)


	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)


	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)


	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)


	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)


	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)


	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)


	at java.base/java.lang.Thread.run(Thread.java:829)


[2021-11-04 16:57:22,361] WARN 192.168.208.1 - - [Thu, 4 Nov 2021 16:57:22 GMT] "POST /query-stream HTTP/2.0" 400 435 "-" "-" 124 (io.confluent.ksql.api.server.LoggingHandler:111)


[2021-11-04 16:57:28,274] INFO 192.168.208.5 - - [Thu, 4 Nov 2021 16:57:28 GMT] "GET /info HTTP/2.0" 200 133 "-" "armeria/1.7.2" 0 (io.confluent.ksql.api.server.LoggingHandler:113)


[2021-11-04 16:57:47,724] INFO 192.168.208.5 - - [Thu, 4 Nov 2021 16:57:47 GMT] "GET /info HTTP/2.0" 200 133 "-" "armeria/1.7.2" 0 (io.confluent.ksql.api.server.LoggingHandler:113)`

**Comment by DmytroMelnyk** [comment]
I run ksqldb with docker

[ksqldb-0.21.txt](https://github.com/confluentinc/ksql/files/7476722/ksqldb-0.21.txt)

**Comment by jzaralim** [comment]
That's weird, `MIGRATION_SCHEMA_VERSIONS` is a table created with a CTAS statement and should be queryable. 

@DmytroMelnyk do you mind opening a new ticket? We have not seen this bug before.

If you have logs for the error from 0.19, I'm interested in seeing those as well.

**Comment by DmytroMelnyk** [comment]
Hi @jzaralim. Here are logs from ksqldb and ksqldb-cli for 0.1
[ksqldb-0.19_ksqldbcli-0.19.txt](https://github.com/confluentinc/ksql/files/7482362/ksqldb-0.19_ksqldbcli-0.19.txt)
9
