### ISSUE TITLE
KsMaterializedWindowTableTest fails with JDK 11

### ISSUE THREAD

**Issue by martin-g** [confluentinc/ksql#8336]
**Describe the bug**

Building ksql with Java 11 fails with:
```
[INFO] Running io.confluent.ksql.execution.streams.materialization.KsqlMaterializationTest
[ERROR] Tests run: 26, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.563 s <<< FAILURE! - in io.confluent.ksql.execution.streams.materialization.KsqlMaterializationTest
[ERROR] io.confluent.ksql.execution.streams.materialization.KsqlMaterializationTest.shouldReturnSelectTransformedFromWindowed  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <Optional[Window{start=2021-10-29T09:34:40.270015Z, end=2021-10-29T09:34:40.280016Z}]>
     but: was <Optional[Window{start=2021-10-29T09:34:40.270Z, end=2021-10-29T09:34:40.280Z}]>
	at io.confluent.ksql.execution.streams.materialization.KsqlMaterializationTest.shouldReturnSelectTransformedFromWindowed(KsqlMaterializationTest.java:514)

[INFO] Running io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest
[ERROR] Tests run: 32, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 1.006 s <<< FAILURE! - in io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest
[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenStartBounds_fetchAll  Time elapsed: 0.914 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <false>
     but: was <true>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenStartBounds_fetchAll(KsMaterializedWindowTableTest.java:678)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedStartBounds_fetchAll  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <WindowedRow{key=[[0]@1635500080431/1635500140431], value=[ 'col0' ], rowTime=12345, schema=`K0` STRING KEY, `v0` STRING}>
     but: was <WindowedRow{key=[[1]@1635500090431/1635500150431], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedStartBounds_fetchAll(KsMaterializedWindowTableTest.java:499)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedEndBounds_fetchAll  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <true>
     but: was <false>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedEndBounds_fetchAll(KsMaterializedWindowTableTest.java:590)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenEndBounds  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing [<WindowedRow{key=[[0]@1635500020432/1635500080432], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>]
     but: Not matched: <WindowedRow{key=[[0]@1635500030431/1635500090431], value=[ 'col2' ], rowTime=987865, schema=`K0` STRING KEY, `v0` STRING}>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenEndBounds(KsMaterializedWindowTableTest.java:713)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedEndBounds  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing [<WindowedRow{key=[[0]@1635500020431/1635500080431], value=[ 'col0' ], rowTime=12345, schema=`K0` STRING KEY, `v0` STRING}>, <WindowedRow{key=[[0]@1635500020431/1635500080431], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>]
     but: No item matched: <WindowedRow{key=[[0]@1635500020431/1635500080431], value=[ 'col0' ], rowTime=12345, schema=`K0` STRING KEY, `v0` STRING}>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedEndBounds(KsMaterializedWindowTableTest.java:544)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenStartBounds  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing [<WindowedRow{key=[[0]@1635500080432/1635500140432], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>]
     but: Not matched: <WindowedRow{key=[[0]@1635500090431/1635500150431], value=[ 'col2' ], rowTime=987865, schema=`K0` STRING KEY, `v0` STRING}>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenStartBounds(KsMaterializedWindowTableTest.java:633)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedStartBounds  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing [<WindowedRow{key=[[0]@1635500080431/1635500140431], value=[ 'col0' ], rowTime=12345, schema=`K0` STRING KEY, `v0` STRING}>, <WindowedRow{key=[[0]@1635500090431/1635500150431], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>]
     but: item 0: was <WindowedRow{key=[[0]@1635500090431/1635500150431], value=[ 'col1' ], rowTime=45678, schema=`K0` STRING KEY, `v0` STRING}>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForClosedStartBounds(KsMaterializedWindowTableTest.java:457)

[ERROR] io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenEndBounds_fetchAll  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <false>
     but: was <true>
	at io.confluent.ksql.execution.streams.materialization.ks.KsMaterializedWindowTableTest.shouldReturnValuesForOpenEndBounds_fetchAll(KsMaterializedWindowTableTest.java:763)
```

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL: current `master` branch.
2. export JAVA_HOME=/path/to/jdk-11.
3. `./mvnw clean install`

**Expected behavior**

The build passes successfully.

**Comment by suhas-satish** [comment]
@martin-g , can you try with Java 8?

**Comment by martin-g** [comment]
It passes with JDK 1.8.
I have explained this in the linked issue (the one about Linux ARM64).

I'm not in front of my PC right now.

**Comment by agavra** [comment]
We currently only support development on JDK8, you may deploy it using JDK11 though if you desire.

**Comment by martin-g** [comment]
This is sad!
I hope my other tickets for JDK 8 + Linux ARM64 to be fixed soon!
