### ISSUE TITLE
Non-aggregate SELECT expression(s) not part of GROUP BY

### ISSUE THREAD

**Issue by outminder** [confluentinc/ksql#8349]
**Describe the bug**
I am seeing "Non-aggregate SELECT expression(s) not part of GROUP BY: TYPE" error when trying to create a table like this
`CREATE TABLE total WITH (VALUE_FORMAT='JSON', KEY_FORMAT='JSON') AS SELECT ID, TYPE, SUM(VAL) AS TOTAL_VAL FROM TYPES GROUP BY ID EMIT CHANGES;`

**To Reproduce**
This is failing in Confluent community version 6.2.0

**Expected behavior**
It should allow to select multiple columns

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output

2. Error messages
`Could not determine output schema for query due to error: Non-aggregate SELECT expression(s) not part of GROUP BY: TYPE
Either add the column(s) to the GROUP BY or remove them from the SELECT.
Statement: CREATE TABLE TOTAL WITH (KAFKA_TOPIC='TOTAL', KEY_FORMAT='JSON', PARTITIONS=13, REPLICAS=1, VALUE_FORMAT='JSON') AS SELECT
  TYPES.ID ID,
  TYPES.TYPE TYPE,
  SUM(TYPES.VAL) TOTAL_VAL
FROM TYPES TYPES
GROUP BY TYPES.ID
EMIT CHANGES;
`
3. KSQL logs
```
`Statement: CREATE TABLE TOTAL WITH (KAFKA_TOPIC='TOTAL', KEY_FORMAT='JSON', PARTITIONS=13, REPLICAS=1, VALUE_FORMAT='JSON') AS SELECT
  TYPES.ID ID,
  TYPES.TYPE TYPE,
  SUM(TYPES.VAL) TOTAL_VAL
FROM TYPES TYPES
GROUP BY TYPES.ID
EMIT CHANGES;
	at io.confluent.ksql.schema.ksql.inference.SchemaRegisterInjector.registerForCreateAs(SchemaRegisterInjector.java:129)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegisterInjector.inject(SchemaRegisterInjector.java:73)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:163)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:130)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:263)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:188)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$22(KsqlServerEndpoints.java:330)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$21(KsqlServerEndpoints.java:316)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.confluent.ksql.util.KsqlStatementException: Non-aggregate SELECT expression(s) not part of GROUP BY: TYPE
Either add the column(s) to the GROUP BY or remove them from the SELECT.
Statement: CREATE TABLE TOTAL WITH (KAFKA_TOPIC='TOTAL', KEY_FORMAT='JSON', PARTITIONS=13, REPLICAS=1, VALUE_FORMAT='JSON') AS SELECT
  TYPES.ID ID,
  TYPES.TYPE TYPE,
  SUM(TYPES.VAL) TOTAL_VAL
FROM TYPES TYPES
GROUP BY TYPES.ID
EMIT CHANGES;
	at io.confluent.ksql.engine.EngineExecutor.plan(EngineExecutor.java:286)
	at io.confluent.ksql.engine.SandboxedExecutionContext.plan(SandboxedExecutionContext.java:123)
	at io.confluent.ksql.schema.ksql.inference.SchemaRegisterInjector.registerForCreateAs(SchemaRegisterInjector.java:123)
	... 14 more
Caused by: io.confluent.ksql.util.KsqlException: Non-aggregate SELECT expression(s) not part of GROUP BY: TYPE
Either add the column(s) to the GROUP BY or remove them from the SELECT.
	at io.confluent.ksql.analyzer.AggregateAnalyzer$AggAnalyzer.enforceAggregateRules(AggregateAnalyzer.java:256)
	at io.confluent.ksql.analyzer.AggregateAnalyzer$AggAnalyzer.result(AggregateAnalyzer.java:238)
	at io.confluent.ksql.analyzer.AggregateAnalyzer.analyze(AggregateAnalyzer.java:62)
	at io.confluent.ksql.planner.LogicalPlanner.buildAggregateNode(LogicalPlanner.java:349)
	at io.confluent.ksql.planner.LogicalPlanner.buildPersistentLogicalPlan(LogicalPlanner.java:151)
	at io.confluent.ksql.engine.QueryEngine.buildQueryLogicalPlan(QueryEngine.java:69)
	at io.confluent.ksql.engine.EngineExecutor.planQuery(EngineExecutor.java:297)
	at io.confluent.ksql.engine.EngineExecutor.plan(EngineExecutor.java:248)
	... 16 more
[2021-11-10 16:14:35,010] WARN 127.0.0.1 - - [Wed, 10 Nov 2021 21:14:35 GMT] "POST /ksql HTTP/1.1" 400 774 "-" "-" 227 (io.confluent.ksql.api.server.LoggingHandler:111)

`
```

**Comment by starga2er** [comment]
I think this is a sentence that did not use Group by properly. Because, "TYPES".TYPE TYPE' did not belong to Group by. When the values are summarized as Group by, multiple values are grouped into one Group By variable. Therefore, it is better to choose between the two methods.

1. Remove "TYPES.TYPE TYPE".
```sql
CREATE TABLE total WITH (VALUE_FORMAT='JSON', KEY_FORMAT='JSON') AS SELECT 
ID, SUM(VAL) AS TOTAL_VAL 
FROM TYPES 
GROUP BY ID 
EMIT CHANGES;
```

2. Add "TYPES.TYPE TYPE" to "Group By".
```sql
CREATE TABLE total WITH (VALUE_FORMAT='JSON', KEY_FORMAT='JSON') AS SELECT 
ID, TYPE, SUM(VAL) AS TOTAL_VAL 
FROM TYPES 
GROUP BY ID, TYPE
EMIT CHANGES;
```

**Comment by outminder** [comment]
You are right, I ended up using the second option
