### ISSUE TITLE
"Received 500 response from server: No value present. Error code: 50000" when getting list of connectors

### ISSUE THREAD

**Issue by Yevhen-Voroniuk** [confluentinc/ksql#8379]
**Describe the bug**
In some rare cases when we call client.listConnectors() we get error: No value present. Error code: 50000. 

**To Reproduce**
The version of KSQL: docker image "confluentinc/ksqldb-server:0.19.0"

We create several connectors and after each quickly call:
client.listConnectors()
And sometimes this method returns error.

**Expected behavior**
Should return list of connectors without an error

**Actual behaviour**
Client error: KsqlClientException: Received 500 response from server: No value present. Error code: 50000
KSQL logs:
`io.confluent.ksql.api.client.exception.KsqlClientException: Received 500 response from server: No value present. Error code: 50000
java.util.concurrent.ExecutionException: io.confluent.ksql.api.client.exception.KsqlClientException: Received 500 response from server: No value present. Error code: 50000
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbService.getExistedConnectorsNames(KsqlDbService.java:192)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbService.dropOldConnectorAndStreamsAndTopics(KsqlDbService.java:62)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbService.createConnectorIfDoesNotExist(KsqlDbService.java:55)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbInitializer.initConnectors(KsqlDbInitializer.java:45)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbInitializer.init(KsqlDbInitializer.java:35)
at com.cantire.api.pricing.configurer.ksqldb.KsqlDbInitializerTest.testInit(KsqlDbInitializerTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
at`

**Comment by josephinekn** [comment]
+1
