### ISSUE TITLE
MAP reduce not work 

### ISSUE THREAD

**Issue by hcheng2002cn** [confluentinc/ksql#8390]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 0.17
2. Sample source data. (None)
3. Any SQL statements you ran
CREATE STREAM stream1 (
    id INT, name VARCHAR,
    exam_scores MAP<STRING, STRING>
) WITH (
    kafka_topic = 'topic1', partitions = 1,
    value_format = 'json'
);

CREATE STREAM reduced
    AS SELECT name,
    REDUCE(exam_scores, "" ,(s,k,v)=> (s+x+v)) AS total
FROM stream1 EMIT CHANGES;

**Expected behavior**
stream reduced created.
**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
ksql> CREATE STREAM stream1 (
>    id INT, name VARCHAR,
>    exam_scores MAP<STRING, STRING>
>) WITH (
>    kafka_topic = 'topic1', partitions = 1,
>    value_format = 'json'
>);
>

 Message        
----------------
 Stream created 
----------------
ksql> CREATE STREAM reduced
>    AS SELECT name,
>    REDUCE(exam_scores, "" ,(s,k,v)=> (s+x+v)) AS total
>FROM stream1 EMIT CHANGES;
Failed to prepare statement: name is empty
2. Error messages
Failed to prepare statement: name is empty
3. KSQL logs
ksqldb-server         | [2021-11-19 05:00:38,799] INFO Received: KsqlRequest{ksql='CREATE STREAM reduced
ksqldb-server         |     AS SELECT name,
ksqldb-server         |     REDUCE(exam_scores, "" ,(s,k,v)=> (s+x+v)) AS total
ksqldb-server         | FROM stream1 EMIT CHANGES;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional[50]} (io.confluent.ksql.rest.server.resources.KsqlResource:262)
ksqldb-server         | [2021-11-19 05:00:38,802] INFO Processed unsuccessfully: KsqlRequest{ksql='CREATE STREAM reduced
ksqldb-server         |     AS SELECT name,
ksqldb-server         |     REDUCE(exam_scores, "" ,(s,k,v)=> (s+x+v)) AS total
ksqldb-server         | FROM stream1 EMIT CHANGES;', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional[50]}, reason:  (io.confluent.ksql.rest.server.resources.KsqlResource:325)
ksqldb-server         | io.confluent.ksql.parser.exception.ParseFailedException: Failed to prepare statement: name is empty
ksqldb-server         | Statement: CREATE STREAM reduced
ksqldb-server         |     AS SELECT name,
ksqldb-server         |     REDUCE(exam_scores, "" ,(s,k,v)=> (s+x+v)) AS total
ksqldb-server         | FROM stream1 EMIT CHANGES;
ksqldb-server         | 	at io.confluent.ksql.parser.DefaultKsqlParser.prepare(DefaultKsqlParser.java:80)
ksqldb-server         | 	at io.confluent.ksql.engine.EngineContext.prepare(EngineContext.java:173)
ksqldb-server         | 	at io.confluent.ksql.engine.SandboxedExecutionContext.prepare(SandboxedExecutionContext.java:115)
ksqldb-server         | 	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:119)
ksqldb-server         | 	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:281)
ksqldb-server         | 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:204)
ksqldb-server         | 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$23(KsqlServerEndpoints.java:358)
ksqldb-server         | 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:344)
ksqldb-server         | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
ksqldb-server         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
ksqldb-server         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
ksqldb-server         | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
ksqldb-server         | 	at java.base/java.lang.Thread.run(Thread.java:829)
ksqldb-server         | Caused by: java.lang.IllegalArgumentException: name is empty
ksqldb-server         | 	at io.confluent.ksql.name.Name.<init>(Name.java:42)
ksqldb-server         | 	at io.confluent.ksql.name.ColumnName.<init>(ColumnName.java:33)
ksqldb-server         | 	at io.confluent.ksql.name.ColumnName.of(ColumnName.java:29)
ksqldb-server         | 	at io.confluent.ksql.parser.ColumnReferenceParser.resolve(ColumnReferenceParser.java:70)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitColumnReference(AstBuilder.java:1171)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitColumnReference(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$ColumnReferenceContext.accept(SqlBaseParser.java:6166)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:657)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:5827)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:946)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:5436)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitBooleanDefault(SqlBaseBaseVisitor.java:594)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:5222)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:580)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:5150)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitFunctionArgument(AstBuilder.java:1230)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitFunctionArgument(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$FunctionArgumentContext.accept(SqlBaseParser.java:6900)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
ksqldb-server         | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
ksqldb-server         | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ksqldb-server         | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visit(AstBuilder.java:1464)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitFunctionCall(AstBuilder.java:1216)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitFunctionCall(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$FunctionCallContext.accept(SqlBaseParser.java:6390)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:657)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:5827)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:946)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:5436)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitBooleanDefault(SqlBaseBaseVisitor.java:594)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:5222)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:580)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:5150)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitSelectSingle(AstBuilder.java:638)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitSelectSingle(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$SelectSingleContext.accept(SqlBaseParser.java:4303)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
ksqldb-server         | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
ksqldb-server         | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
ksqldb-server         | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ksqldb-server         | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visit(AstBuilder.java:1464)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitQuery(AstBuilder.java:430)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.lambda$visitCreateStreamAs$0(AstBuilder.java:316)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.withinPersistentQuery(AstBuilder.java:1528)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitCreateStreamAs(AstBuilder.java:316)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitCreateStreamAs(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$CreateStreamAsContext.accept(SqlBaseParser.java:752)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitSingleStatement(AstBuilder.java:247)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder$Visitor.visitSingleStatement(AstBuilder.java:218)
ksqldb-server         | 	at io.confluent.ksql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:365)
ksqldb-server         | 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder.build(AstBuilder.java:214)
ksqldb-server         | 	at io.confluent.ksql.parser.AstBuilder.buildStatement(AstBuilder.java:195)
ksqldb-server         | 	at io.confluent.ksql.parser.DefaultKsqlParser.prepare(DefaultKsqlParser.java:69)
ksqldb-server         | 	... 12 more

**Additional context**

**Comment by hcheng2002cn** [comment]
should use '' for empty. closed.
