### ISSUE TITLE
Incompatibility with Kafka version < 2.4.1

### ISSUE THREAD

**Issue by davidwmartines2** [confluentinc/ksql#8508]
**Describe the bug**
When the Kafka broker version is below 2.4.1, `GROUP BY` queries fail with error stating "brokers don't support configuration replication.factor=-1".

**To Reproduce**
ksqldb-server version 0.22.0

```
create stream test(val varchar) with (kafka_topic='test', value_format='delimited', partitions=1);
```

```
select 'x' as x, count(*) as record_count from test  group by 'x' emit changes;
```

**Expected behavior**
Creates the necessary internal topic, without error messages.

**Actual behaviour**
**Could not create topic _confluent-ksql-default_transient_transient_TEST_8970207927108243080_1639435896209-Aggregate-GroupBy-repartition, because brokers don't support configuration replication.factor=-1. You can change the replication.factor config or upgrade your brokers to version 2.4 or newer to avoid this error.**

```
[2021-12-13 22:53:51,385] ERROR stream-client [_confluent-ksql-default_transient_transient_TEST_8970207927108243080_1639435896209-103cde54-2df9-4483-9073-46254290b87b] Encountered the following exception during processing and Kafka Streams opted to SHUTDOWN_CLIENT. The streams client is going to shut down now.  (org.apache.kafka.streams.KafkaStreams:529)
ksql_1             | org.apache.kafka.streams.errors.StreamsException: Could not create topic _confluent-ksql-default_transient_transient_TEST_8970207927108243080_1639435896209-Aggregate-GroupBy-repartition, because brokers don't support configuration replication.factor=-1. You can change the replication.factor config or upgrade your brokers to version 2.4 or newer to avoid this error.
ksql_1             |    at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:463)
ksql_1             |    at org.apache.kafka.streams.processor.internals.RepartitionTopics.setup(RepartitionTopics.java:73)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.prepareRepartitionTopics(StreamsPartitionAssignor.java:494)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.assign(StreamsPartitionAssignor.java:373)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.performAssignment(ConsumerCoordinator.java:589)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.onJoinLeader(AbstractCoordinator.java:694)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.access$1000(AbstractCoordinator.java:112)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:598)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:561)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1194)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1169)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:602)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:427)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:366)
ksql_1             |    at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:508)
ksql_1             |    at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1262)
ksql_1             |    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1231)
ksql_1             |    at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:968)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:925)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:739)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:602)
ksql_1             |    at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:574)
```

**Additional context**
This was actually discovered trying to use **ksql-migrations**.  When running `initialize-metadata`,  saw the error in logs:
```
2021-12-13 21:06:08,031] ERROR stream-thread [CommandRunner] Unexpected error during topic creation for _confluent-ksql-default_query_CTAS_MIGRATION_SCHEMA_VERSIONS_31-Aggregate-Aggregate-Mater │
│ ialize-changelog.                                                                                                                                                                                  │
│ Error message was: org.apache.kafka.common.errors.UnsupportedVersionException: Creating topics with default partitions/replication factor are only supported in CreateTopicRequest version 4+. The │
│  following topics need values for partitions and replicas: [_confluent-ksql-default_query_CTAS_MIGRATION_SCHEMA_VERSIONS_31-Aggregate-Aggregate-Materialize-changelog] (org.apache.kafka.streams.p │
│ rocessor.internals.InternalTopicManager:451)                                                                                                                                                       │
│ [2021-12-13 21:06:08,035] ERROR Unhandled exception caught in streams thread _confluent-ksql-default_query_CTAS_MIGRATION_SCHEMA_VERSIONS_31-438404bf-ff87-4cd0-98a7-a8a33b153718-StreamThread-1.  │
│ (UNKNOWN) (io.confluent.ksql.util.QueryMetadataImpl:196)                                                                                                                                           │
│ org.apache.kafka.streams.errors.StreamsException: Could not create topic _confluent-ksql-default_query_CTAS_MIGRATION_SCHEMA_VERSIONS_31-Aggregate-Aggregate-Materialize-changelog, because broker │
│ s don't support configuration replication.factor=-1. You can change the replication.factor config or upgrade your brokers to version 2.4 or newer to avoid this error.                             │
│     at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:459)
```

**What I tried**
setting `ksql.internal.topics.replicas=1` .  No luck.

**Comment by mjsax** [comment]
Can you try setting `ksql.streams.replication.factor` config in the server properties files.

For more details compare https://cwiki.apache.org/confluence/display/KAFKA/KIP-733%3A+change+Kafka+Streams+default+replication+factor+config
