### ISSUE TITLE
can not to drop table

### ISSUE THREAD

**Issue by chengang2** [confluentinc/ksql#860]
drop table CGAAA;
io.confluent.ksql.util.KsqlException: No topic with name true was registered.

**Comment by big-andy-coates** [comment]
Hi @chengang2,

You can see the list of known tables by running `Show tables`.  Is the table you're trying to drop listed? If its not, then the create table statement probably failed.

If this resolves your problem please close this issue. Otherwise, response with more information.

**Comment by apurvam** [comment]
Closing this issue. If the table shows up in the `show tables;` output, and if you still cannot drop it. Please reopen and provide all the CLI output so that we can help diagnose.

**Comment by rchady** [comment]
I ran in to this as well:

```
ksql> SHOW TABLES;

 Table Name     | Kafka Topic    | Format | Windowed
-----------------------------------------------------
 PROXY_REQUESTS | PROXY_REQUESTS | AVRO   | true
-----------------------------------------------------
ksql> DROP TABLE PROXY_REQUESTS;
io.confluent.ksql.util.KsqlException: No topic with name true was registered.
	at io.confluent.ksql.metastore.MetaStoreImpl.deleteTopic(MetaStoreImpl.java:79)
	at io.confluent.ksql.ddl.commands.DropTopicCommand.run(DropTopicCommand.java:37)
	at io.confluent.ksql.ddl.commands.DropSourceCommand.run(DropSourceCommand.java:58)
	at io.confluent.ksql.ddl.commands.DDLCommandExec.executeOnMetaStore(DDLCommandExec.java:60)
	at io.confluent.ksql.ddl.commands.DDLCommandExec.execute(DDLCommandExec.java:54)
	at io.confluent.ksql.rest.server.resources.KsqlResource.executeDDLCommand(KsqlResource.java:606)
	at io.confluent.ksql.rest.server.resources.KsqlResource.lambda$registerDdlCommandTasks$11(KsqlResource.java:583)
	at io.confluent.ksql.rest.server.resources.KsqlResource.getStatementExecutionPlan(KsqlResource.java:450)
	at io.confluent.ksql.rest.server.resources.KsqlResource.validateStatement(KsqlResource.java:256)
	at io.confluent.ksql.rest.server.resources.KsqlResource.executeStatement(KsqlResource.java:232)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:148)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:408)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:583)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:524)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:461)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by apurvam** [comment]
Thanks for the update. Is this a problem with all your tables? Can you provide the relevant portion of `ksql.log` when you create a table?

**Comment by rchady** [comment]
Nope, only that one.  I haven't run in to it since that one either.  I posted the update on here 'cause I had experienced it like the original poster had.

**Comment by apurvam** [comment]
Ok. It could be that the original topic creation failed and the error was not propagated back to the cli. We have fixed a bunch of issue related to topic creation and error reporting recently. Please reopen if this continues to be an issue with the latest master.

**Comment by big-andy-coates** [comment]
Interestingly, the error message talks about a topic named `true`!!!

> io.confluent.ksql.util.KsqlException: No topic with name true was registered.

However, as @apurvam says, there have been a lot of changes in this area. Specially, we no longer 'register' topics.  So I'm confident this issue has been fixed.
