### ISSUE TITLE
example pom file need add dependency

### ISSUE THREAD

**Issue by AMJASH** [confluentinc/ksql#8799]
https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/java-client/#getting-started

when i run example for test , it show **Caused by: java.lang.ClassNotFoundException: org.apache.kafka.streams.errors.StreamsException**
add the dependency can work. 
```xml
<dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>0.10.0.1</version>
</dependency>
```
 maybe other version for you choose

**Comment by nuschandra** [comment]
Hi @agavra I face the same issue as described above when executing the synchronous streamQuery method. Is this a known issue and if so, is there any additional dependency that needs to be included?

Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/streams/errors/StreamsException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.confluent.ksql.api.client.impl.ClientImpl.streamQuery(ClientImpl.java:131)
	at io.confluent.ksql.api.client.impl.ClientImpl.streamQuery(ClientImpl.java:123)
