### ISSUE TITLE
Make HISTOGRAM function more general.

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#8916]
**Is your feature request related to a problem? Please describe.**
Presently, HISTOGRAM only operates on String columns.

**Describe the solution you'd like**
Extend HISTOGRAM to support more column types.  This may require some discussion.

**Comment by jnh5y** [comment]
When I tried this briefly...  I added the following to `histogram.json`:

```   {
      "name": "histogram with multiple types",
      "format": ["AVRO", "PROTOBUF"],
      "statements": [
        "CREATE STREAM INPUT (ID BIGINT KEY, F0 INT, F1 BIGINT, F2 DOUBLE, F3 BOOLEAN, F4 STRING, F5 TIMESTAMP, F6 TIME, F7 DATE, F8 BYTES, F9 ARRAY<INT>) WITH (kafka_topic='test_topic', value_format='JSON');",
        "CREATE TABLE OUTPUT AS SELECT ID, HISTOGRAM(F0) AS L0, HISTOGRAM(F1) AS L1, HISTOGRAM(F2) AS L2, HISTOGRAM(F3) AS L3, HISTOGRAM(F4) AS L4, HISTOGRAM(F5) AS L5, HISTOGRAM(F6) AS L6, HISTOGRAM(F7) AS L7, HISTOGRAM(F8) AS L8, HISTOGRAM(F9) AS L9 FROM INPUT GROUP BY ID;"
      ],
      "inputs": [
        {"topic": "test_topic", "key": 0, "value": {"F0": {"COUNTS": {"12": 1}}, "F1": 1000, "F2": 1.23, "F3": true, "F4": "foo", "F5": 12, "F6": 123, "F7": 1234, "F8": "YQ==", "F9": [0,0,1,0,-1]}},
        {"topic": "test_topic", "key": 1, "value": {"F0": 12, "F1": 1000, "F2": 1.23, "F3": true, "F4": "foo", "F5": 12, "F6": 123, "F7": 1234, "F8": "YQ==", "F9": [0,0,1,0,-1]}},
        {"topic": "test_topic", "key": 0, "value": {"F0": 21, "F1": 2000, "F2": 2.23, "F3": false, "F4": "foo", "F5": 34, "F6": 234, "F7": 2345, "F8": "Yg==", "F9": [1,2,3,4,-1]}},
        {"topic": "test_topic", "key": 1, "value": {"F0": 21, "F1": 2000, "F2": 2.23, "F3": false, "F4": "foo", "F5": 34, "F6": 234, "F7": 2345, "F8": "Yg==", "F9": [1,2,3,4,-1]}}
      ],
      "outputs": [
        {"topic": "OUTPUT", "key": 0, "value": {"L0": 12, "L1": 1000, "L2": 1.23, "L3": true, "L4": "foo", "L5": 12, "L6": 123, "L7": 1234, "L8": "YQ==", "L9": [0,0,1,0,-1]}},
        {"topic": "OUTPUT", "key": 1, "value": {"L0": 12, "L1": 1000, "L2": 1.23, "L3": true, "L4": "foo", "L5": 12, "L6": 123, "L7": 1234, "L8": "YQ==", "L9": [0,0,1,0,-1]}},
        {"topic": "OUTPUT", "key": 0, "value": {"L0": 12, "L1": 1000, "L2": 1.23, "L3": true, "L4": "foo", "L5": 12, "L6": 123, "L7": 1234, "L8": "YQ==", "L9": [0,0,1,0,-1]}},
        {"topic": "OUTPUT", "key": 1, "value": {"L0": 12, "L1": 1000, "L2": 1.23, "L3": true, "L4": "foo", "L5": 12, "L6": 123, "L7": 1234, "L8": "YQ==", "L9": [0,0,1,0,-1]}}
      ]
    }```
    
    And updated `HistogramUdaf.java` with 
    ```      SqlType inputType;
      SqlType aggregateAndReturnType;
      @Override
      public void initializeTypeArguments(final List<SqlArgument> argTypeList) {
        inputType = argTypeList.get(0).getSqlTypeOrThrow();
        aggregateAndReturnType = SqlMap.of(inputType, SqlTypes.BIGINT);
      }

      @Override
      public Optional<SqlType> getAggregateSqlType() {
        return Optional.of(aggregateAndReturnType);
      }

      @Override
      public Optional<SqlType> getReturnSqlType() {
        return Optional.of(aggregateAndReturnType);
      }``` to return the type info.
      
      
      I got this error running the QTTs:
      
      ```java.lang.AssertionError: One of the functions used in the statement has an intermediate type that the value format can not handle. Please remove the function or change the format.
Consider up-voting https://github.com/confluentinc/ksql/issues/3950, which will resolve this limitation
....
Caused by: io.confluent.ksql.util.KsqlException: JSON only supports MAP types with STRING keys
	at io.confluent.ksql.serde.json.KsqlJsonDeserializer$1SchemaValidator.visitMap(KsqlJsonDeserializer.java:369)
	at io.confluent.ksql.serde.json.KsqlJsonDeserializer$1SchemaValidator.visitMap(KsqlJsonDeserializer.java:364)```
