### ISSUE TITLE
VALUE_SCHEMA_ID does not work with complex structure and optional fields

### ISSUE THREAD

**Issue by AdilHoumadi** [confluentinc/ksql#8919]
**Describe the bug**

New `VALUE_SCHEMA_ID` supported in ksqlDB 0.24.0 does not work with a complex structure and optional fields. 
The issue is composed of two different behaviors:
 - 1st one: ksqlDB is not able to serialize data to topic if the schema contains a complex structure.
 - 2nd issue: ksqlDB is not able to comprehend / parse optional fields in a complex schema.

**To Reproduce**
1. The version of KSQL. 0.24.0
2. Sample source data, produce this data to a topic (transaction)
```json
{"id": "1", "transaction": { "num_shares": 50000, "amount": 50044568, "txn_ts": "2020-11-18 02:31:43", "customer": { "first_name": "Jill", "last_name": "Smith", "id": 1234567, "email": "jsmith@gmail.com" }, "company": { "name": "ACME Corp", "ticker": "ACMC", "id": "ACME837275222752952", "address": "Anytown USA, 333333"}}}
{"id": "2", "transaction": { "num_shares": 30000, "amount": 5004, "txn_ts": "2020-11-18 02:35:43", "customer": { "first_name": "Art", "last_name": "Vandeley", "id": 8976612, "email": "avendleay@gmail.com" }, "company": { "name": "Imports Corp", "ticker": "IMPC", "id": "IMPC88875222752952", "address": "Anytown USA, 333333"}}}
{"id": "3", "transaction": { "num_shares": 3000000, "amount": 50045, "txn_ts": "2020-11-18 02:36:43", "customer": { "first_name": "John", "last_name": "England", "id": 456321, "email": "je@gmail.com" }, "company": { "name": "Hechinger", "ticker": "HECH", "id": "HECH8333785222752952", "address": "Anytown USA, 333333"}}}
{"id": "4", "transaction": { "num_shares": 10000, "amount": 80044, "txn_ts": "2020-11-18 02:37:43", "customer": { "first_name": "Fred", "last_name": "Pym", "id": 333567, "email": "fjone@gmail.com" }, "company": { "name": "PymTech", "ticker": "PYMT", "id": "PYME837275222714197419202020", "address": "Anytown USA, 333333"}}}
```
3. Register the following schema
```
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  --data '{"schema": "{\"name\":\"Transaction\",\"type\":\"record\",\"namespace\":\"com.acme.namespace\",\"fields\":[{\"name\":\"eventID\",\"type\":\"string\"},{\"name\":\"transaction\",\"type\":{\"name\":\"transaction\",\"type\":\"record\",\"fields\":[{\"name\":\"num_shares\",\"type\":\"int\"},{\"name\":\"amount\",\"type\":\"int\"},{\"name\":\"customer\",\"type\":{\"name\":\"customer\",\"type\":\"record\",\"fields\":[{\"name\":\"first_name\",\"type\":\"string\"},{\"name\":\"last_name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}]}}]}}]}"}' \
  http://localhost:8081/subjects/model-transaction-value/versions
```

4. Run the following statement

```sql
SET 'auto.offset.reset' = 'earliest';

# create the transaction stream
CREATE STREAM TXS (
  `id` VARCHAR,
  `transaction` VARCHAR
) WITH (
     KAFKA_TOPIC = 'transaction'
   , VALUE_FORMAT='JSON'
   , KEY_FORMAT='KAFKA'
);

# Rekey the stream to another topic
CREATE STREAM TXS_REKEY WITH (
    KAFKA_TOPIC='transaction-rekey',
    VALUE_FORMAT='JSON',
    KEY_FORMAT='KAFKA'
)
AS SELECT
`id`, `transaction`
FROM "TXS"
PARTITION BY `id`
EMIT CHANGES;

# model the stream by using an existing schema
CREATE STREAM MODEL_TXS_EVENT WITH  (
    KAFKA_TOPIC='model-transaction',
    KEY_FORMAT='KAFKA',
    VALUE_FORMAT='AVRO',
    VALUE_SCHEMA_ID='1'
)
AS
SELECT
`id`,
as_value(txs.`id`) AS `eventID`,
STRUCT(
    `num_shares` := CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.num_shares') AS INT),
    `amount` := CAST(EXTRACTJSONFIELD(txs.`transaction`, '$.amount') AS INT),
    `customer` := STRUCT(
        `first_name`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.first_name'),
        `last_name`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.last_name'),
        `email`:= EXTRACTJSONFIELD(txs.`transaction`, '$.customer.email')
    )
) AS `transaction`
FROM TXS_REKEY txs
EMIT CHANGES;

```

**Expected behavior**

1. 1st -> Being able to consume the modeled events in the last stream (MODEL_TXS_EVENT)
2. 2nd -> Run the same queries with another variant of the schema, the schema should contain optional fields.
The optional fields are not parsed as expected, the server will complain about the structure of the schema

```bash
ksql> show streams;

 Stream Name         | Kafka Topic                 | Key Format | Value Format | Windowed
------------------------------------------------------------------------------------------
 KSQL_PROCESSING_LOG | default_ksql_processing_log | KAFKA      | JSON         | false
 MODEL_TXS_EVENT     | model-transaction           | KAFKA      | AVRO         | false
 TXS                 | transaction                 | KAFKA      | JSON         | false
 TXS_REKEY           | transaction-rekey           | KAFKA      | JSON         | false
------------------------------------------------------------------------------------------
ksql> select * from MODEL_TXS_EVENT emit changes;
+----------------------------------------+----------------------------------------+----------------------------------------+
|id                                      |eventID                                 |transaction                             |
+----------------------------------------+----------------------------------------+----------------------------------------+
```

**Actual behaviour**
The streams has been created successfully, but once your start consuming the modeled event you get the following error in ksqldb server.

1st Error:
```
ror encountered sending record to topic model-transaction for task 0_0 due to:
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: model-transaction. Struct schemas do not match.
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:177)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:139)
        at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:85)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
        at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
        at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
        at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
        at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:780)
        at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:809)
        at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:780)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:711)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1296)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:800)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:620)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:584)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: model-transaction. Struct schemas do not match.
        at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)
        at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
        at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:186)
        at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:149)
        at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)
        at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)
        at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:157)
        ... 28 more
Caused by: org.apache.kafka.connect.errors.DataException: Struct schemas do not match.
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:249)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at io.confluent.ksql.serde.avro.AvroSRSchemaDataTranslator.toConnectRow(AvroSRSchemaDataTranslator.java:56)
        at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)
        ... 35 more
[2022-03-22 13:51:29,689] INFO stream-thread [_confluent-ksql-default_query_CSAS_MODEL_TXS_EVENT_65-2a4a55ed-9ebb-4bf3-afb3-bd6d82e8269a-StreamThread-5] Processed 0 total records, ran 0 punctuators, and committed 0 total tasks since the last update (org.apache.kafka.streams.processor.internals.StreamThread:874)
[2022-03-22 13:51:29,804] INFO Retrying request. Retry no: 1 Cause: 'org.apache.kafka.common.errors.GroupNotEmptyException: The group is not empty.' (io.confluent.ksql.util.ExecutorUtil:104)
```

2nd Error:
Try to modify the schema and introduce an optional field in the structure, you will get this kind of errors.

```
The following value columns are changed, missing or reordered: [`transaction` STRUCT<`num_shares` INTEGER, `amount` INTEGER, `customer` STRUCT<`first_name` STRING, `last_name` STRING, `email` STRING>>]. Schema from schema registry is [`eventID` STRING, `transaction` STRUCT<`num_shares` INTEGER, `amount` INTEGER, `customer` STRUCT<`first_name` STRING, `last_name` STRING, `email` STRING>>]
```

**Comment by lihaosky** [comment]
The exception happens because the logical schema for `customer` has optional fields but the physical schema in SR doesn't have optional fields. I think we can fix this.

**Comment by AdilHoumadi** [comment]
if the you want I can split the issues:
- Usecase with optional fields in SR
- Usecase to demonstrate the miss match to parse the schema when using: VALUE_SCHEMA_ID

**Comment by lihaosky** [comment]
There's nothing we can do about optional fields. I'll just try to fix it for `VALUE_SCHEMA_ID` case.

**Comment by szicari-streambit** [comment]
I am running into this issue on a locally running **Confluent Platform 7.1.1** with a schema that does not have optional fields.

This is the schema:

```json
{
    "type": "record",
    "name": "AngelDonationDonor",
    "fields": [
        {
            "name": "template_id",
            "type": "string"
        },
        {
            "name": "from_",
            "type": "string"
        },
        {
            "name": "to_",
            "type": {
                "type": "array",
                "items": {
                    "type": "record",
                    "name": "To",
                    "fields": [
                        {
                            "name": "email",
                            "type": "string"
                        },
                        {
                            "name": "name",
                            "type": "string"
                        }
                    ]
                },
                "name": "to_"
            }
        },
        {
            "name": "dynamic_data",
            "type": {
                "type": "record",
                "name": "DynamicData",
                "fields": [
                    {
                        "name": "num_votes",
                        "type": "long"
                    },
                    {
                        "name": "donor_email",
                        "type": "string"
                    }
                ]
            }
        }
    ]
}
```

I created a topic and associate the above schema, and then I create a stream with the following syntax:

```sql
CREATE STREAM angel_donations_donor_emails 
WITH (KAFKA_TOPIC='angel-donations-donor-emails', VALUE_FORMAT='avro', VALUE_SCHEMA_ID=1);
```

(I only have one schema in the local cluster, which is why the ID is 1.

Here is the insert statement:

```sql
INSERT INTO angel_donations_donor_emails
VALUES
(
  'd-84a1d60f335e4e6791b286458904a94e',
  'info@w4wkc.org',
  ARRAY[STRUCT(`name`:='Sean Z', `email`:='szicari@streambit.software')],
  STRUCT(`num_votes`:=5, `donor_email`:='szicari@streambit.software')
);
```

The error I get from the ksqlDB Console:

```
Failed to insert values into 'SOMETHING_DONATIONS_DONOR_EMAILS'. Could not serialize value: [ 'd-84a1d60f335e4e6791b286458904a94e' | 'info@w4wkc.org' | [Struct{email=szicari@streambit.software,name=Sean Z}] | Struct{num_votes=15,donor_email=szicari@streambit.software} ]. Error serializing message to topic: something-donations-donor-emails. Struct schemas do not match.
```

Attached is the stdout from ksqlDB around the time of the insert attempt.

[ksqldb.stdout.log](https://github.com/confluentinc/ksql/files/8613172/ksqldb.stdout.log)

**Comment by szicari-farmobile** [comment]
For what it's worth, I've tested primitive types successfully with pre-registered schemas and am going to redesign my events to exclude arrays, maps, and structs for the time being until this feature is fully baked. It's a very minor change overall - just a slightly less organized event structure but still the same result.

**Comment by suhas-satish** [comment]
@pgaref , unassigned you from this since it makes sense to wait on other related serialization issues as Sergio has noted in the comment below 
https://github.com/confluentinc/ksql/pull/9238#issuecomment-1189507274
