### ISSUE TITLE
[vert.x-eventloop-thread-0] io.confluent.ksql.api.server.ServerVerticle unhandledExceptionHandler - Unhandled exception javax.net.ssl.SSLException: Received fatal alert: internal_error

### ISSUE THREAD

**Issue by alxivanov** [confluentinc/ksql#9001]
ksqlDB functions are not impacted by this error as far as I can tell, though this message keeps appearing in k8s pod log. Might stem from the fact that we are using a self-signed certificate at the moment. Would be nice if someone could explain what is happening.

Here is the stack trace:
```
javax.net.ssl.SSLException: Received fatal alert: internal_error
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
        at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:92)
        at io.netty.handler.ssl.JdkAlpnSslEngine.unwrap(JdkAlpnSslEngine.java:163)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Our configuration:

```
  authentication:
    type: mtls
  dependencies:
    kafka:
      bootstrapEndpoint: ...
      authentication:
        type: mtls
      tls:
        enabled: true
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1

  configOverrides:
    server:
      ....
      - ssl.client.authentication=REQUIRED
      - ssl.keystore.location=/mnt/sslcerts/keystore.p12
      - ssl.keystore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - ssl.truststore.location=/mnt/sslcerts/truststore.p12
      - ssl.truststore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
```

**Comment by alxivanov** [comment]
This seems to be a problem when upgrading to v7.1.1 - Control Center and ksqlDB components are not able to establish a connection, leading to ksqlDB not being available from Control Center.
