### ISSUE TITLE
No Events when Pulling from Materialized View. Error: "Missing default value for required Avro field: [$ColumnName]. This field appears in Avro schema in Schema Registry"}"

### ISSUE THREAD

**Issue by prathamvasa123** [confluentinc/ksql#9212]
**Describe the bug**
When a STREAM is created using `VALUE_SCHEMA_ID`, the query errors out.

**To Reproduce**
**Register schema**
```
{
  "doc": "Sample schema to help you get started.",
  "fields": [
    {
      "doc": "The int type is a 32-bit signed integer.",
      "name": "f1",
      "type": "string"
    },
    {
      "doc": "The double type is a double precision (64-bit) IEEE 754 floating-point number.",
      "name": "f2",
      "type": "string"
    },
    {
      "doc": "The string is a unicode character sequence.",
      "name": "f3",
      "type": "string"
    }
  ],
  "name": "sampleRecord",
  "namespace": "com.mycorp.mynamespace",
  "type": "record"
}
```

**Set up the STREAM and run GROUP BY:**
```
ksql> create stream expstr with(kafka_topic='expavrotopic', value_schema_id=43, value_format='avro');

 Message        
----------------
 Stream created 
----------------

ksql> insert into expstr(`f1`,`f2`,`f3`) values('1','2','3');

ksql> select `f1`, count(*) from expstr group by `f1` emit changes;
+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
|f1                                                                                                     |KSQL_COL_0                                                                                             |
+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
Error in processing query. Check server logs for details.
Query terminated
```

**Expected Output:**
Data from GROUP BY query results

**Actual Output:**
```
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: _confluent-ksql-stdalonetransient_transient_EXPSTR_9014089044495426378_1655493549305-Aggregate-GroupBy-repartition. Schema from Schema Registry misses field with name: ROWTIME
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:177)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:139)
	at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:85)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
	at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:194)
	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:61)
	at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:146)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:275)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:254)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:213)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:780)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:809)
	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:780)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:711)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1296)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:800)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:620)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:584)
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: _confluent-ksql-stdalonetransient_transient_EXPSTR_9014089044495426378_1655493549305-Aggregate-GroupBy-repartition. Schema from Schema Registry misses field with name: ROWTIME
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)
	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:186)
	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:149)
	at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)
	at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:157)
	... 43 more
Caused by: io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: ROWTIME
	at io.confluent.ksql.serde.connect.ConnectSRSchemaDataTranslator.validate(ConnectSRSchemaDataTranslator.java:49)
	at io.confluent.ksql.serde.avro.AvroSRSchemaDataTranslator.toConnectRow(AvroSRSchemaDataTranslator.java:50)
	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)
	... 50 more
```

Workaround (is to CREATE STREAM without the value_schema_id):
```
ksql> CREATE STREAM EXP2STR (`f1` STRING, `f2` STRING, `f3` STRING) WITH (KAFKA_TOPIC='expavrotopic', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO');

 Message        
----------------
 Stream created 
----------------

ksql> select `f1`, count(*) from exp2str group by `f1` emit changes;
+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
|f1                                                                                                     |KSQL_COL_0                                                                                             |
+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+
|1                                                                                                      |1                                                                                                      |
^CQuery terminated
```

**Comment by agavra** [comment]
@suhas-satish this looks related to the value schema id work and I've actually seen this error pretty frequently in our cloud now, we should triage it with high priority.

**Comment by bvarghese1** [comment]
I have fixed something similar. Let me try this out on the latest master to see if its already fixed.

**Comment by bvarghese1** [comment]
I don't see this issue on the latest master. This has been fixed by this PR - https://github.com/confluentinc/ksql/pull/9552

**Comment by bvarghese1** [comment]
```
ksql> insert into expstr(`f1`,`f2`,`f3`) values('1','2','3');
ksql> insert into expstr(`f1`,`f2`,`f3`) values('1','2','3');
ksql> insert into expstr(`f1`,`f2`,`f3`) values('1','2','3');

ksql> select `f1`, count(*) from expstr group by `f1` emit changes;
+-------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
|f1                                                                             |KSQL_COL_0                                                                     |
+-------------------------------------------------------------------------------+-------------------------------------------------------------------------------+
|1                                                                              |3                                                                              |

Press CTRL-C to interrupt
```

**Comment by suhas-satish** [comment]
thanks for confirming @bvarghese1 , closing this
