### ISSUE TITLE
Variable Substitions 'not yet implemented' Error in REST API

### ISSUE THREAD

**Issue by nbonavia** [confluentinc/ksql#9495]
**Describe the bug**
I am trying to use variable substitution in a ksqldb where clause on ksqldb version 0.27.1. The script works as expected when executed from the ksql-client (version 0.27.1) but when invoked trough the ksql rest endpoint, I get an error code 50000 with a 'not yet implemented' message.

**To Reproduce**
Run the below curl command: -

```
curl --location --request POST 'http://<ksqldb url> /ksql' \
--header 'Accept: application/vnd.ksql.v1+json' \
--header 'Content-Type: application/vnd.ksql.v1+json' \
--data-raw '{
    "ksql": "define partitions='\''1'\'';define user_profile_wallet_updated_rekeyed_checkpoint = '\''1660833633855'\''; CREATE OR REPLACE STREAM user_profile_wallet_updated_rekeyed WITH (    kafka_topic='\''user_profile_wallet_updated_rekeyed'\'',    partitions=${partitions},    value_format='\''AVRO'\'') AS    SELECT        *    FROM user_profile_wallet_updated    WHERE        ROWTIME>=CAST(${user_profile_wallet_updated_rekeyed_checkpoint} as BIGINT)    PARTITION BY transactionid;"
}'
```

The response I received from the KSQLDB server was : -
```
{
    "@type": "statement_error",
    "error_code": 50000,
    "message": "not yet implemented",
    "statementText": "define partitions='1';\ndefine user_profile_wallet_updated_rekeyed_checkpoint = '1660833633855';\nCREATE OR REPLACE STREAM user_profile_wallet_updated_rekeyed WITH (    kafka_topic='user_profile_wallet_updated_rekeyed',    partitions=${partitions},    value_format='AVRO') AS    SELECT        *    FROM user_profile_wallet_updated    WHERE        ROWTIME>=CAST(${user_profile_wallet_updated_rekeyed_checkpoint} as BIGINT)    PARTITION BY transactionid;",
    "entities": []
}
```

**Expected behavior**
The expected Behaviour is that the stream will be created with the appropriate defined variables substituted.

**Actual behaviour**
The stream does not get created

**Additional context**
The stacktrace observed on the server log
```
java.lang.UnsupportedOperationException: not yet implemented
	at io.confluent.ksql.parser.AstBuilder$Visitor.aggregateResult(AstBuilder.java:1396)
	at io.confluent.ksql.parser.AstBuilder$Visitor.aggregateResult(AstBuilder.java:227)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:47)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitVariableLiteral(SqlBaseBaseVisitor.java:1014)
	at io.confluent.ksql.parser.SqlBaseParser$VariableLiteralContext.accept(SqlBaseParser.java:8737)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitLiteralExpression(SqlBaseBaseVisitor.java:839)
	at io.confluent.ksql.parser.SqlBaseParser$LiteralExpressionContext.accept(SqlBaseParser.java:6971)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:713)
	at io.confluent.ksql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:6360)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:978)
	at io.confluent.ksql.parser.AstBuilder$Visitor.visitPredicated(AstBuilder.java:227)
	at io.confluent.ksql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:5969)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitBooleanDefault(SqlBaseBaseVisitor.java:650)
	at io.confluent.ksql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:5742)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:636)
	at io.confluent.ksql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:5670)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.parser.AstBuilder.build(AstBuilder.java:223)
	at io.confluent.ksql.parser.AstBuilder.buildExpression(AstBuilder.java:208)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitExpression(QueryAnonymizer.java:478)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitExpression(QueryAnonymizer.java:115)
	at io.confluent.ksql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:5670)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitCast(SqlBaseBaseVisitor.java:797)
	at io.confluent.ksql.parser.SqlBaseParser$CastContext.accept(SqlBaseParser.java:6822)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:713)
	at io.confluent.ksql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:6360)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitComparison(SqlBaseBaseVisitor.java:671)
	at io.confluent.ksql.parser.SqlBaseParser$ComparisonContext.accept(SqlBaseParser.java:6039)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitBooleanDefault(QueryAnonymizer.java:501)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitBooleanDefault(QueryAnonymizer.java:115)
	at io.confluent.ksql.parser.SqlBaseParser$BooleanDefaultContext.accept(SqlBaseParser.java:5742)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitQuery(QueryAnonymizer.java:826)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitQuery(QueryAnonymizer.java:115)
	at io.confluent.ksql.parser.SqlBaseParser$QueryContext.accept(SqlBaseParser.java:2951)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitCreateStreamAs(QueryAnonymizer.java:573)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitCreateStreamAs(QueryAnonymizer.java:115)
	at io.confluent.ksql.parser.SqlBaseParser$CreateStreamAsContext.accept(SqlBaseParser.java:805)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitSingleStatement(QueryAnonymizer.java:136)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitStatements(QueryAnonymizer.java:128)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer$Visitor.visitStatements(QueryAnonymizer.java:115)
	at io.confluent.ksql.parser.SqlBaseParser$StatementsContext.accept(SqlBaseParser.java:220)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer.build(QueryAnonymizer.java:112)
	at io.confluent.ksql.engine.rewrite.QueryAnonymizer.anonymize(QueryAnonymizer.java:108)
	at io.confluent.ksql.logging.query.QueryLogger.log(QueryLogger.java:66)
	at io.confluent.ksql.logging.query.QueryLogger.info(QueryLogger.java:102)
	at io.confluent.ksql.rest.server.resources.KsqlResource.lambda$handleKsqlStatements$0(KsqlResource.java:316)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:311)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:183)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$23(KsqlServerEndpoints.java:341)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:327)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-08-25 05:09:11,952] ERROR 10.42.0.127 - - [Thu, 25 Aug 2022 05:09:11 GMT] "POST /ksql HTTP/1.1" 500 563 "-" "PostmanRuntime/7.29.2" 467 (io.confluent.ksql.api.server.LoggingHandler:140)
[2022-08-25 05:09:16,007] INFO Retrying request. Retry no: 2 Cause: 'org.apache.kafka.common.errors.GroupNotEmptyException: The group is not empty.' (io.confluent.ksql.util.ExecutorUtil:104)
```

**Comment by nbonavia** [comment]
I checked again, and all I had to do is to include the quotes around the declared variable since it is a string.

```
curl --location --request POST 'http://ksqldb.localhost/ksql' \
--header 'Accept: application/vnd.ksql.v1+json' \
--header 'Content-Type: application/vnd.ksql.v1+json' \
--data-raw '{
    "ksql": "define partitions='\''1'\'';define user_profile_wallet_updated_rekeyed_checkpoint = '\''1660833633855'\'';CREATE OR REPLACE STREAM user_profile_wallet_updated_rekeyed WITH (    kafka_topic='\''user_profile_wallet_updated_rekeyed'\'',    partitions=${partitions},    value_format='\''AVRO'\'') AS    SELECT        *    FROM user_profile_wallet_updated    WHERE        ROWTIME>=CAST('\''${user_profile_wallet_updated_rekeyed_checkpoint}'\'' as BIGINT)    PARTITION BY transactionid;"
}'
```
