### ISSUE TITLE
UnknownTopicOrPartitionException caused by high latency

### ISSUE THREAD

**Issue by xavsan** [confluentinc/ksql#9613]
**Describe the bug**
When introducing high latency to my system, I'm running into this UnknownTopicOrPartitionException that causes errors all throughout my program execution.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL = 0.28.2
2. A simple create stream command followed by a series of inserts following the tutorial here https://ksqldb.io/quickstart.html
3. A deliberate introduction of high latency, to test how the ksql system performs under stress

**Expected behavior**
I expected the system to be able to deal with high latency, or at least let me configure the max timeout

**Actual behaviour**

Due to the high latency, my program can't find the topic it should be creating when I send the first CREATE ksql command. And for the rest of the execution of the program, I get this same unknown topic error when trying to insert into the stream. 

Here's what I'm seeing in the logs:

```
[  397759] [    43.404189] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:01,230] INFO Received: KsqlRequest{ksql='CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE) WITH (kafka_topic='locations', value_format='json', partitions=3);', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:279) 

[  398007] [    52.540246] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:10,366] INFO Creating topic 'locations' (ONLY VALIDATE) (io.confluent.ksql.services.KafkaTopicClient:113) 

[  398036] [    53.622853] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:11,449] INFO Creating topic 'locations'  (io.confluent.ksql.services.KafkaTopicClient:113) 
[  398944] [    84.695773] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:42,522] INFO Retrying request. Retry no: 0 Cause: 'org.apache.kafka.common.errors.TimeoutException: The request timed out.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399004] [    85.692425] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:43,518] INFO Retrying request. Retry no: 0 Cause: 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399064] [    86.350735] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:44,177] INFO Retrying request. Retry no: 1 Cause: 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399094] [    87.016029] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:44,842] INFO Retrying request. Retry no: 2 Cause: 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399094] [    87.634852] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:45,461] INFO Retrying request. Retry no: 3 Cause: 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399094] [    88.208375] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:46,034] INFO Retrying request. Retry no: 4 Cause: 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' (io.confluent.ksql.util.ExecutorUtil:104) 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] [2022-09-23 15:25:46,035] INFO Processed unsuccessfully: KsqlRequest{ksql='CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE) WITH (kafka_topic='locations', value_format='json', partitions=3);', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty}, reason:  (io.confluent.ksql.rest.server.resources.KsqlResource:347) 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to Describe Kafka Topic(s): [locations] 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.services.KafkaTopicClientImpl.describeTopics(KafkaTopicClientImpl.java:212) 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.services.KafkaTopicClient.describeTopic(KafkaTopicClient.java:162) 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.services.KafkaTopicClientImpl.validateTopicProperties(KafkaTopicClientImpl.java:388) 
[  399094] [    88.208987] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:133) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.services.KafkaTopicClient.createTopic(KafkaTopicClient.java:102) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.topic.TopicCreateInjector.createTopic(TopicCreateInjector.java:211) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.topic.TopicCreateInjector.createTopic(TopicCreateInjector.java:197) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.topic.TopicCreateInjector.injectForCreateSource(TopicCreateInjector.java:132) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:91) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:75) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42) 
[  399094] [    88.208988] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.computation.DistributingExecutor.execute(DistributingExecutor.java:176) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.execution.RequestHandler.lambda$executeStatement$0(RequestHandler.java:123) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.execution.RequestHandler.executeStatement(RequestHandler.java:127) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.execution.RequestHandler.execute(RequestHandler.java:93) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:320) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:183) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$23(KsqlServerEndpoints.java:341) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:327) 
[  399094] [    88.208989] [service_primary-ksqldb-server] [I] 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313) 
[  399094] [    88.208990] [service_primary-ksqldb-server] [I] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
[  399094] [    88.208990] [service_primary-ksqldb-server] [I] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
[  399094] [    88.208990] [service_primary-ksqldb-server] [I] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
[  399094] [    88.208990] [service_primary-ksqldb-server] [I] 	at java.base/java.lang.Thread.run(Thread.java:829) 
[  399094] [    88.208990] [service_primary-ksqldb-server] [I] Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

**Additional context**
The first column represents the current state of the system. The second column represents the current v-time of the system. The third column represents the source from which the log is coming from.

**Comment by xavsan** [comment]
I believe the error is coming from the kafka nodes timing out earlier which prompts a series of errors and exceptions most prominently ``` org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists ``` :

``` 
[  398550] [    66.954086] [service_kafka-3] [I] [2022-09-23 15:25:24,780] WARN Client session timed out, have not heard from server in 12001ms for session id 0x100000045930005 (org.apache.zookeeper.ClientCnxn) 
[  398550] [    66.954601] [service_kafka-3] [I] [2022-09-23 15:25:24,780] WARN Session 0x100000045930005 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn) 
[  398550] [    66.954601] [service_kafka-3] [I] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 12001ms for session id 0x100000045930005 
[  398550] [    66.954601] [service_kafka-3] [I] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) 
[  398581] [    68.329913] [service_kafka-3] [I] [2022-09-23 15:25:26,156] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn) 
[  398581] [    68.587898] [service_kafka-2] [I] [2022-09-23 15:25:26,414] INFO [GroupCoordinator 2]: Member sr-1-ec96281a-bc28-4324-9719-32a55e60577f in group schema-registry has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator) 
[  398581] [    68.588149] [service_kafka-2] [I] [2022-09-23 15:25:26,414] INFO [GroupCoordinator 2]: Preparing to rebalance group schema-registry in state PreparingRebalance with old generation 1 (__consumer_offsets-29) (reason: removing member sr-1-ec96281a-bc28-4324-9719-32a55e60577f on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator) 
[  398581] [    68.588352] [service_kafka-2] [I] [2022-09-23 15:25:26,414] INFO [GroupCoordinator 2]: Group schema-registry with generation 2 is now empty (__consumer_offsets-29) (kafka.coordinator.group.GroupCoordinator) 
[  398612] [    69.512821] [service_kafka-3] [I] [2022-09-23 15:25:27,339] INFO Socket connection established, initiating session, client: /10.20.20.45:35118, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn) 
[  398612] [    69.626375] [service_kafka-3] [I] [2022-09-23 15:25:27,452] INFO Session establishment complete on server zookeeper/10.20.20.10:2181, session id = 0x100000045930005, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn) 
[  398612] [    69.952980] [service_kafka-2] [I] [2022-09-23 15:25:27,779] WARN Client session timed out, have not heard from server in 12004ms for session id 0x100000045930004 (org.apache.zookeeper.ClientCnxn) 
[  398612] [    69.953484] [service_kafka-2] [I] [2022-09-23 15:25:27,779] WARN Session 0x100000045930004 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn) 
[  398612] [    69.953484] [service_kafka-2] [I] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 12004ms for session id 0x100000045930004 
[  398612] [    69.953484] [service_kafka-2] [I] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) 
[  398643] [    70.738232] [service_kafka-2] [I] [2022-09-23 15:25:28,564] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group schema-registry in Empty state. Created a new member id sr-1-11495942-f40b-4c77-8ff3-024a619d2aa3 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator) 
[  398674] [    70.853137] [service_kafka-2] [I] [2022-09-23 15:25:28,679] INFO [GroupCoordinator 2]: Preparing to rebalance group schema-registry in state PreparingRebalance with old generation 2 (__consumer_offsets-29) (reason: Adding new member sr-1-11495942-f40b-4c77-8ff3-024a619d2aa3 with group instance id None; client reason: rebalance failed due to 'The group member needs to have a valid member id before actually entering a consumer group.' (MemberIdRequiredException)) (kafka.coordinator.group.GroupCoordinator) 
[  398704] [    71.535784] [service_kafka-2] [I] [2022-09-23 15:25:29,362] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn) 
[  398704] [    71.696896] [service_kafka-2] [I] [2022-09-23 15:25:29,523] INFO Socket connection established, initiating session, client: /10.20.20.40:59588, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn) 
[  398704] [    71.848668] [service_kafka-2] [I] [2022-09-23 15:25:29,675] INFO Session establishment complete on server zookeeper/10.20.20.10:2181, session id = 0x100000045930004, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn) 
[  398704] [    72.642079] [service_kafka] [I] [2022-09-23 15:25:30,468] WARN Client session timed out, have not heard from server in 12030ms for session id 0x100000045930002 (org.apache.zookeeper.ClientCnxn) 
[  398704] [    72.642611] [service_kafka] [I] [2022-09-23 15:25:30,468] WARN Session 0x100000045930002 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn) 
[  398704] [    72.642611] [service_kafka] [I] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 12030ms for session id 0x100000045930002 
[  398704] [    72.642611] [service_kafka] [I] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) 
[  398704] [    72.742931] [service_kafka] [I] [2022-09-23 15:25:30,569] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient) 
[  398704] [    72.742972] [service_kafka] [I] [2022-09-23 15:25:30,569] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient) 
[  398734] [    73.749049] [service_kafka] [I] [2022-09-23 15:25:31,575] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn) 
[  398734] [    73.854017] [service_kafka-2] [I] [2022-09-23 15:25:31,680] INFO [GroupCoordinator 2]: Stabilized group schema-registry generation 3 (__consumer_offsets-29) with 1 members (kafka.coordinator.group.GroupCoordinator) 
[  398734] [    73.912482] [service_kafka] [I] [2022-09-23 15:25:31,739] INFO Socket connection established, initiating session, client: /10.20.20.15:37134, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn) 
[  398734] [    74.019887] [service_kafka-2] [I] [2022-09-23 15:25:31,846] INFO [GroupCoordinator 2]: Assignment received from leader sr-1-11495942-f40b-4c77-8ff3-024a619d2aa3 for group schema-registry for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator) 
[  398734] [    74.077586] [service_kafka] [I] [2022-09-23 15:25:31,904] INFO Session establishment complete on server zookeeper/10.20.20.10:2181, session id = 0x100000045930002, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn) 
[  398734] [    74.307799] [service_kafka] [I] [2022-09-23 15:25:32,134] ERROR [Controller id=1 epoch=1] Controller 1 epoch 1 failed to change state for partition locations-0 from NewPartition to OnlinePartition (state.change.logger) 
[  398734] [    74.307799] [service_kafka] [I] org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists 
[  398734] [    74.307799] [service_kafka] [I] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.logFailedStateChange(PartitionStateMachine.scala:520) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$10(PartitionStateMachine.scala:314) 
[  398734] [    74.307799] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563) 
 
[  398734] [    74.307799] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561) 
[  398734] [    74.307799] [service_kafka] [I] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:304) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:230) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:161) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:661) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1668) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.KafkaController.process(KafkaController.scala:2544) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:52) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:130) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:133) 
[  398734] [    74.307799] [service_kafka] [I] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:133) 
[  398734] [    74.307799] [service_kafka] [I] 	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96) 
[  398734] [    74.308095] [service_kafka] [I] [2022-09-23 15:25:32,134] ERROR [Controller id=1 epoch=1] Controller 1 epoch 1 failed to change state for partition locations-1 from NewPartition to OnlinePartition (state.change.logger) 
[  398734] [    74.308095] [service_kafka] [I] org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists 
[  398734] [    74.308095] [service_kafka] [I] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.logFailedStateChange(PartitionStateMachine.scala:520) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$10(PartitionStateMachine.scala:314) 
[  398734] [    74.308095] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563) 
[  398734] [    74.308095] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561) 
[  398734] [    74.308095] [service_kafka] [I] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:304) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:230) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:161) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:661) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1668) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.KafkaController.process(KafkaController.scala:2544) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:52) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:130) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:133) 
[  398734] [    74.308095] [service_kafka] [I] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:133) 
[  398734] [    74.308095] [service_kafka] [I] 	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96) 
[  398734] [    74.308189] [service_kafka] [I] [2022-09-23 15:25:32,134] ERROR [Controller id=1 epoch=1] Controller 1 epoch 1 failed to change state for partition locations-2 from NewPartition to OnlinePartition (state.change.logger) 
[  398734] [    74.308189] [service_kafka] [I] org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists 
[  398734] [    74.308189] [service_kafka] [I] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.logFailedStateChange(PartitionStateMachine.scala:520) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$10(PartitionStateMachine.scala:314) 
[  398734] [    74.308189] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563) 
[  398734] [    74.308189] [service_kafka] [I] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561) 
[  398734] [    74.308189] [service_kafka] [I] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926) 
 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:304) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:230) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:161) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:661) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1668) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.KafkaController.process(KafkaController.scala:2544) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:52) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:130) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:133) 
[  398734] [    74.308189] [service_kafka] [I] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:133) 
[  398734] [    74.308189] [service_kafka] [I] 	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96) 
[  398734] [    74.308277] [service_kafka] [I] [2022-09-23 15:25:32,134] INFO [Controller id=1 epoch=1] Sending UpdateMetadata request to brokers HashSet() for 0 partitions (state.change.logger) 
[  398734] [    74.308383] [service_kafka] [I] [2022-09-23 15:25:32,134] TRACE [Controller id=1 epoch=1] Changed state of replica 1 for partition locations-1 from NewReplica to OnlineReplica (state.change.logger) 
[  398734] [    74.308486] [service_kafka] [I] [2022-09-23 15:25:32,135] TRACE [Controller id=1 epoch=1] Changed state of replica 2 for partition locations-2 from NewReplica to OnlineReplica (state.change.logger) 
[  398734] [    74.308524] [service_kafka] [I] [2022-09-23 15:25:32,135] TRACE [Controller id=1 epoch=1] Changed state of replica 3 for partition locations-0 from NewReplica to OnlineReplica (state.change.logger) 
[  398734] [    74.308556] [service_kafka] [I] [2022-09-23 15:25:32,135] INFO [Controller id=1 epoch=1] Sending UpdateMetadata request to brokers HashSet() for 0 partitions (state.change.logger) 
```
