### ISSUE TITLE
Issue when creating a table from stream with protobuf schema id

### ISSUE THREAD

**Issue by nicoga97** [confluentinc/ksql#9797]
**Describe the bug**
Hi! I am creating a table using a stream that is using protobuf schema with defined schema id, when I produce data to the stream topic  I got this error on KSQL db logs: ``io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: account_id``  

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL.
0.28.2
4. Any SQL statements you ran
First create the schema in schema registry for ``test1``:
```
syntax = "proto3";
package account;

message AccountCommandEvent {
  int64 timestamp = 2;
  double amount = 3;
}
```
Then create the stream:
```
CREATE
STREAM IF NOT EXISTS ACCOUNT_EVENTS(
    `account_id` STRING KEY
)WITH (
  KAFKA_TOPIC='test1',
  KEY_FORMAT='KAFKA',
  VALUE_SCHEMA_ID= 14, -- Id of the previously created schema
  VALUE_FORMAT='PROTOBUF'
);
```
Then create the table:
```
CREATE
OR REPLACE TABLE ACCOUNT WITH (
        KAFKA_TOPIC='test2',
        PARTITIONS=10,
        REPLICAS=1,
        KEY_FORMAT='KAFKA',
        VALUE_FORMAT='PROTOBUF'
        ) AS
SELECT "account_id",
        SUM("amount") AS "current_balance",
       COLLECT_LIST(STRUCT(
               "timestamp":= "timestamp",
               "amount":= "amount"
           )) AS "events_list"
FROM ACCOUNT_EVENTS
GROUP BY "account_id" EMIT CHANGES;
```
Then just produce a message to ``test1`` with any key:
```
{
	"timestamp": 79379929,
	"amount": 1000.00
}
```

**Expected behavior**
The message produced to the stream should be aggregated on the table with the stream data.

**Actual behaviour**
No data is produced to the table and an error shows up on ksqldb logs.
1. CLI output
No changes are shown on the table.
2. KSQL logs
```
Exception in thread "_confluent-ksql-default_query_CTAS_ACCOUNT_25-b51e718b-a5ea-405e-bd29-e5340939eef3-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=test1, partition=0, offset=2, stacktrace=io.confluent.ksql.serde.KsqlSerializationException: Error serializing message to topic: _confluent-ksql-default_query_CTAS_ACCOUNT_25-Aggregate-Aggregate-Materialize-changelog. Schema from Schema Registry misses field with name: account_id

	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)

	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)

	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:188)

	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:151)

	at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)

	at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:83)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:74)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:31)

	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:195)

	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$put$6(MeteredKeyValueStore.java:330)

	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)

	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.put(MeteredKeyValueStore.java:330)

	at org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator$KeyValueStoreReadWriteDecorator.put(AbstractReadWriteDecorator.java:127)

	at org.apache.kafka.streams.kstream.internals.KStreamAggregate$KStreamAggregateProcessor.process(KStreamAggregate.java:121)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)

	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:793)

	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)

	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:793)

	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:724)

	at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:100)

	at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:81)

	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1182)

	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:768)

	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:588)

	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:550)

Caused by: io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: account_id

	at io.confluent.ksql.serde.connect.ConnectSRSchemaDataTranslator.validate(ConnectSRSchemaDataTranslator.java:48)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.convertStruct(ProtobufSRSchemaDataTranslator.java:74)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.compatibleWithSchema(ProtobufSRSchemaDataTranslator.java:64)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.toConnectRow(ProtobufSRSchemaDataTranslator.java:40)

	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)

	... 39 more


	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:750)

	at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:100)

	at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:81)

	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1182)

	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:768)

	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:588)

	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:550)

Caused by: io.confluent.ksql.serde.KsqlSerializationException: Error serializing message to topic: _confluent-ksql-default_query_CTAS_ACCOUNT_25-Aggregate-Aggregate-Materialize-changelog. Schema from Schema Registry misses field with name: account_id

	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:56)

	at io.confluent.ksql.serde.tls.ThreadLocalSerializer.serialize(ThreadLocalSerializer.java:37)

	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:188)

	at io.confluent.ksql.serde.connect.ConnectFormat$ListToStructSerializer.serialize(ConnectFormat.java:151)

	at io.confluent.ksql.serde.GenericSerializer.serialize(GenericSerializer.java:62)

	at io.confluent.ksql.logging.processing.LoggingSerializer.serialize(LoggingSerializer.java:47)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:83)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:74)

	at org.apache.kafka.streams.state.internals.ValueAndTimestampSerializer.serialize(ValueAndTimestampSerializer.java:31)

	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:195)

	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$put$6(MeteredKeyValueStore.java:330)

	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)

	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.put(MeteredKeyValueStore.java:330)

	at org.apache.kafka.streams.processor.internals.AbstractReadWriteDecorator$KeyValueStoreReadWriteDecorator.put(AbstractReadWriteDecorator.java:127)

	at org.apache.kafka.streams.kstream.internals.KStreamAggregate$KStreamAggregateProcessor.process(KStreamAggregate.java:121)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.kstream.internals.KStreamTransformValues$KStreamTransformValuesProcessor.process(KStreamTransformValues.java:66)

	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)

	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)

	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)

	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:793)

	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)

	at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:793)

	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:724)

	... 6 more

Caused by: io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: account_id

	at io.confluent.ksql.serde.connect.ConnectSRSchemaDataTranslator.validate(ConnectSRSchemaDataTranslator.java:48)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.convertStruct(ProtobufSRSchemaDataTranslator.java:74)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.compatibleWithSchema(ProtobufSRSchemaDataTranslator.java:64)

	at io.confluent.ksql.serde.protobuf.ProtobufSRSchemaDataTranslator.toConnectRow(ProtobufSRSchemaDataTranslator.java:40)

	at io.confluent.ksql.serde.connect.KsqlConnectSerializer.serialize(KsqlConnectSerializer.java:52)

	... 39 more
```
 Thanks!

**Comment by mjsax** [comment]
Can you `DESCRIBE` the stream `ACCOUNT_EVENTS` -- what is the key-format? Maybe you can expliclity specify key-format as `KAFKA` to avoid the issue?

**Comment by nicoga97** [comment]
Thanks for your response @mjsax  I added the ``KEY_FORMAT='KAFKA'`` on the ``ACCOUNT_EVENTS`` stream and ``ACCOUNT`` table  but got the same error ``io.confluent.ksql.util.KsqlException: Schema from Schema Registry misses field with name: account_id``, here I describe the stream and the table:
Stream:
```
Name                 : ACCOUNT_EVENTS
Type                 : STREAM
Timestamp field      : Not set - using <ROWTIME>
Key format           : KAFKA
Value format         : PROTOBUF
Kafka topic          : test1 (partitions: 3, replication: 1)
Statement            : CREATE STREAM IF NOT EXISTS ACCOUNT_EVENTS (`account_id` STRING KEY, `timestamp` BIGINT, `amount` DOUBLE) WITH (KAFKA_TOPIC='test1', KEY_FORMAT='KAFKA', VALUE_FORMAT='PROTOBUF', VALUE_SCHEMA_FULL_NAME='account.AccountCommandEvent', VALUE_SCHEMA_ID=14);

 Field      | Type
-------------------------------------
 account_id | VARCHAR(STRING)  (key)
 timestamp  | BIGINT
 amount     | DOUBLE
-------------------------------------

Sources that have a DROP constraint on this source
--------------------------------------------------
ACCOUNT

Queries that read from this STREAM
-----------------------------------
CTAS_ACCOUNT_69 (RUNNING) : CREATE OR REPLACE TABLE ACCOUNT WITH (KAFKA_TOPIC='test2', KEY_FORMAT='KAFKA', PARTITIONS=10, REPLICAS=1, VALUE_FORMAT='PROTOBUF') AS SELECT   ACCOUNT_EVENTS.`account_id` `account_id`,   SUM(ACCOUNT_EVENTS.`amount`) `current_balance`,   COLLECT_LIST(STRUCT(`timestamp`:=ACCOUNT_EVENTS.`timestamp`, `amount`:=ACCOUNT_EVENTS.`amount`)) `events_list` FROM ACCOUNT_EVENTS ACCOUNT_EVENTS GROUP BY ACCOUNT_EVENTS.`account_id` EMIT CHANGES;

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------
```
Table:
```
Name                 : ACCOUNT
Type                 : TABLE
Timestamp field      : Not set - using <ROWTIME>
Key format           : KAFKA
Value format         : PROTOBUF
Kafka topic          : test2 (partitions: 10, replication: 1)
Statement            : CREATE OR REPLACE TABLE ACCOUNT WITH (KAFKA_TOPIC='test2', KEY_FORMAT='KAFKA', PARTITIONS=10, REPLICAS=1, VALUE_FORMAT='PROTOBUF') AS SELECT
  ACCOUNT_EVENTS.`account_id` `account_id`,
  SUM(ACCOUNT_EVENTS.`amount`) `current_balance`,
  COLLECT_LIST(STRUCT(`timestamp`:=ACCOUNT_EVENTS.`timestamp`, `amount`:=ACCOUNT_EVENTS.`amount`)) `events_list`
FROM ACCOUNT_EVENTS ACCOUNT_EVENTS
GROUP BY ACCOUNT_EVENTS.`account_id`
EMIT CHANGES;

 Field           | Type
------------------------------------------------------------------
 account_id      | VARCHAR(STRING)  (primary key)
 current_balance | DOUBLE
 events_list     | ARRAY<STRUCT<timestamp BIGINT, amount DOUBLE>>
------------------------------------------------------------------

Queries that write from this TABLE
-----------------------------------
CTAS_ACCOUNT_69 (RUNNING) : CREATE OR REPLACE TABLE ACCOUNT WITH (KAFKA_TOPIC='test2', KEY_FORMAT='KAFKA', PARTITIONS=10, REPLICAS=1, VALUE_FORMAT='PROTOBUF') AS SELECT   ACCOUNT_EVENTS.`account_id` `account_id`,   SUM(ACCOUNT_EVENTS.`amount`) `current_balance`,   COLLECT_LIST(STRUCT(`timestamp`:=ACCOUNT_EVENTS.`timestamp`, `amount`:=ACCOUNT_EVENTS.`amount`)) `events_list` FROM ACCOUNT_EVENTS ACCOUNT_EVENTS GROUP BY ACCOUNT_EVENTS.`account_id` EMIT CHANGES;

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------
```
Thanks

**Comment by lihaosky** [comment]
Hi @nicoga97 , re:

> Then just produce a message to test1 with any key:
{
	"timestamp": 79379929,
	"amount": 1000.00
}

how did you produce this to `test1`? Via `kafka-consule-proder`?

**Comment by nicoga97** [comment]
Hi @lihaosky I produced the message using kafka-ui

**Comment by lihaosky** [comment]
OK. I'll try to reproduce it

**Comment by lihaosky** [comment]
Hi @nicoga97 , I suspect there's some problem when you produce to `test1` directly using `kafka-ui`. I was able to insert into `account_events` stream using ksql and then select from `account` table:

```
ksql> insert into ACCOUNT_EVENTS values ('some_id', 123, 12.0);
ksql> select * from account;
+---------------------------------------------------------------+---------------------------------------------------------------+---------------------------------------------------------------+
|account_id                                                     |current_balance                                                |events_list                                                    |
+---------------------------------------------------------------+---------------------------------------------------------------+---------------------------------------------------------------+
|some_id                                                        |12.0                                                           |[{timestamp=123, amount=12.0}]                                 |
Query terminated
ksql>
```

If the schema is created with protobuf, when ksql serialize data into kafka `test1`, there's some header to be set with extra information such as schema id. If you simply insert into `test1` using kafka client directly, those information will be missed causing deserialization problem in downstream. Can you try insertion using ksql?

**Comment by lihaosky** [comment]
Closing because of inactivity.
