### ISSUE TITLE
Error: BindException: Address already in use

### ISSUE THREAD

**Issue by Rap70r** [confluentinc/ksql#9832]
Hello,

I have a Kafka cluster running with Zookeeper, Kafka Broker and Kafka Connect. I followed this quickstart tutorial: https://ksqldb.io/quickstart-standalone-rpm.html#quickstart-content
However, when I try to run below command:

`sudo /usr/bin/ksql-server-start /etc/ksqldb/ksql-server.properties`

I'm getting below error:
```
[2023-03-15 16:24:56,705] INFO ProcessingLogConfig values: 
	ksql.logging.processing.rows.include = false
	ksql.logging.processing.stream.auto.create = false
	ksql.logging.processing.stream.name = KSQL_PROCESSING_LOG
	ksql.logging.processing.topic.auto.create = false
	ksql.logging.processing.topic.name = 
	ksql.logging.processing.topic.partitions = 1
	ksql.logging.processing.topic.replication.factor = 1
 (io.confluent.ksql.logging.processing.ProcessingLogConfig:376)
[2023-03-15 16:24:56,914] ERROR Unhandled exception in server startup (io.confluent.ksql.rest.server.KsqlServerMain:156)
io.confluent.ksql.util.KsqlException: Failed to start API server
	at io.confluent.ksql.api.server.Server.start(Server.java:165)
	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:372)
	at io.confluent.ksql.rest.server.KsqlServerMain.runExecutable(KsqlServerMain.java:152)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:115)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:94)
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.confluent.ksql.api.server.Server.start(Server.java:160)
	... 4 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:459)
	at java.base/sun.nio.ch.Net.bind(Net.java:448)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:426)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:375)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-03-15 16:24:56,915] INFO Server shutting down (io.confluent.ksql.rest.server.KsqlServerMain:159)
[2023-03-15 16:24:56,915] INFO ksqlDB shutdown called (io.confluent.ksql.rest.server.KsqlRestApplication:481)
[2023-03-15 16:25:11,944] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:96)
java.lang.IllegalStateException: Not started
	at io.confluent.ksql.api.server.Server.stop(Server.java:178)
	at io.confluent.ksql.rest.server.KsqlRestApplication.shutdown(KsqlRestApplication.java:528)
	at io.confluent.ksql.rest.server.KsqlServerMain.runExecutable(KsqlServerMain.java:160)
	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:115)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:94)
```

Not sure which port is referring to that is in use. Can you please suggest a possible solution for above issue? Maybe switch the port number somewhere in the configs.

Thank you

**Comment by Rap70r** [comment]
It looks like it was a service running on my machine that was consuming a port used in the configs. I switched machines and I was able to make it work. I'm closing this ticket.

Thank you
