### ISSUE TITLE
KSQLDB server: No LoginModule found for $org.apache.kafka.common.security.scram.ScramLoginModule on startup

### ISSUE THREAD

**Issue by jslusher** [confluentinc/ksql#9927]
**Provide details of the setup you're running**
I'm running the latest docker image of the KSQLdb server and I'm trying to get it to work using SASL/SCRAM authentication. Here's the relevant configuration:
```
  KSQL_BOOTSTRAP_SERVERS: strimzi-kafka-bootstrap.example.com:9096
  KSQL_CONFIG_PROVIDERS: file
  KSQL_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
  KSQL_SASL_JAAS_CONFIG: $${file:/opt/kafka/sasl-auth:sasl-auth}
  KSQL_SASL_MECHANISM: SCRAM-SHA-512
  KSQL_SECURITY_PROTOCOL: SASL_SSL
```

**Outline your question**
On startup, the server is complaining about the ScramLoginModule. Do I have to point it somewhere to see the module or should it be included by default?

```
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:552)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:143)
	at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getAdmin(DefaultKafkaClientSupplier.java:34)
	at io.confluent.ksql.services.ServiceContextFactory.lambda$create$1(ServiceContextFactory.java:62)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at io.confluent.ksql.services.DefaultServiceContext$MemoizedSupplier.get(DefaultServiceContext.java:176)
	at io.confluent.ksql.services.DefaultServiceContext.getAdminClient(DefaultServiceContext.java:116)
	at io.confluent.ksql.services.LazyServiceContext.getAdminClient(LazyServiceContext.java:33)
	at io.confluent.ksql.services.KafkaClusterUtil.getKafkaClusterId(KafkaClusterUtil.java:102)
	... 5 more
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for $org.apache.kafka.common.security.scram.ScramLoginModule
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:523)
	... 13 more
Caused by: javax.security.auth.login.LoginException: No LoginModule found for $org.apache.kafka.common.security.scram.ScramLoginModule
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
```

**Comment by jslusher** [comment]
This turned out to be a misconfigured SASL_JAAS setting:  

```
KSQL_SASL_JAAS_CONFIG: $${file:/opt/kafka/sasl-auth:sasl-auth}
```
Notice the extra `$` there. Originally this configuration was in a kubernetes `spec.env` section and it was necessary. I moved all of the environment variables into a configMap using `envFrom` and there it's not necessary.
